### ISSUE TITLE
Ubuntu install (README) experience is broken / disjointed

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk#1032]
Please see attached PDF of experience.  Essentially, following the existing READMEs with the new changes to link to Ansible README, you would never complete the install without a lot of guess work and redundancy.

Primarily you jump off the ubuntu install to create a DB and get linked to the middle of Ansible README which has no idea you came from Ubuntu README, and has you deploy, without knowing that you were placed in the middle of the text (and never takes you back).  

Also, tried to use default of ephemeral (fastest/easiest) and many times was never sure why I was setting up things that should have already been built/installed already by the time I was linked there.  Sometimes there were CouchDB instructions that I was not 100% sure applied to ephemeral.  Overall a much worse experience from the previous 1/2 page (single page no links or jump offs) with simple ant "build. run. deploy" that existed before Ansible was inserted and at all places am hyperlinked there.

[Ubuntu OpenWhisk Install experience.pdf](https://github.com/openwhisk/openwhisk/files/411549/Ubuntu.OpenWhisk.Install.experience.pdf)

**Comment by rabbah** [comment]
Related to our discussion in #800 @csantanapr.

**Comment by rabbah** [comment]
Other useful things that are buried in arguable the wrong place or deserve promotion: adding users to a deployment, and replace SSL certificates with valid ones. These are currently in the Vagrant README file but that's the wrong place for them (it took me a few minutes to find them and had to resort to a command line grep to do that).

**Comment by rabbah** [comment]
To be replaced by standalone controller docs.
