### ISSUE TITLE
migrate node examples to use destructured parameters

### ISSUE THREAD

**Issue by sjfink** [apache/openwhisk#1244]
@csantanapr showed a way to use ES6 destructuring for more informative parameters:

function main( { name: name} ) { console.log(name); }

proposal: 
- [ ] migrate all our example actions to use this pattern
- [ ] update documentation
- [ ] feature this in a blog

**Comment by csantanapr** [comment]
Reference implementation: https://github.com/csantanapr/openwhisk-demos/blob/master/email/sendEmail.js
