### ISSUE TITLE
Investigate Possibility of Caching Docker Images in TravisCI

### ISSUE THREAD

**Issue by dubee** [apache/openwhisk#1256]
It looks like caching Docker images in Travis builds may be possible. This would speed up build times significantly. For doc on this see: https://gist.github.com/hc2p/9e284cee3d585eefbc59454e44cc247a.

**Comment by sjfink** [comment]
One issue is "sterilize" -- if we don't do something, the docker cache will grow without bound.

One possibility is to introduce a conditional size-based sterilize task to the build-- e.g. if /var/lib/docker exceeds N MB, wipe it.
