### ISSUE TITLE
Support private repository from docker / bluemix

### ISSUE THREAD

**Issue by ValentinOdier** [apache/openwhisk#1362]
Hi, 

I just tried OpenWhisk and i have to say it looks really good.

I think you should support private repository (even if it is just docker.io but adding bluemix repository might be a wonderfull idea too). 
At this point i want to use OpenWhisk but i just can't because my code can't be in a public repository. 

shortly : 
- Allow us to pull from private cloud docker repository
- Allow us to pull from our bluemix collection (maybe even selecting from the dropdown in bluemix UI)

Thanks for reading, have a nice day.

**Comment by krook** [comment]
There was another request for this from an attendee at the Serverless NYC meetup last night.

**Comment by rabbah** [comment]
One way to support this is by pulling images from the private registry to a whisk managed registry at action create time. This would avoid some the challenges around key management for docker login. In general I think this is a good approach for docker actions as it will make it easier for vetting images.

**Comment by andre2007** [comment]
What is the current state of this issue? Is it still not possible to use private docker registries?

**Comment by rabbah** [comment]
This is an ibm feature deficiency.
