### ISSUE TITLE
[Docker SDK] Feature request: Interactive tool to create new Docker actions

### ISSUE THREAD

**Issue by krook** [apache/openwhisk#1380]
The most flexible way to extend OpenWhisk to a use a new programming language (from an end user point of view) is to use the Docker skeleton.

However, doing this requires that the developer carry out additional steps beyond the simpler process of just writing an action file, implementing main(), and uploading it to OpenWhisk.

To make writing Docker actions as easy as writing native actions, the developer should have access to tooling - such as a wizard - that can generate the boilerplate needed to implement the OpenWhisk contract on their behalf.

This wizard or set of templates should provide them with a way to do some or all of the following:
- Choose a different base image for the openwhisk/dockerskeleton, in addition to Alpine Linux, so they can easily install additional packages in their Dockerfile, such as those provided by Ubuntu.
- Give them clear steps on what proxy app code they need to add to their own non-skeleton Dockerfile to implement the necessary `/init` and `/run` HTTP contract.
- Start with a basic `action/exec` example for Go, PHP, Scala, etc in addition to the current examples for C and Python that are found elsewhere in tutorials and blog posts outside this repo.

An additional benefit of tooling is that it can be updated as the underlying OpenWhisk project evolves, abstracting any underlying changes and helping developers avoid outdated documentation on how to implement the `/init` and `/run` contract.

**Comment by csantanapr** [comment]
I think there should be template for nodejs, where user have specific requirements like node modules that contain binaries (i.e. c modules), or they require some utility or operating system tool (i.e. jql).
The action will be almost identical to the actionProxy for nodejs, where node is ran once, and then on every /run the action runs in memory without the need to run a new node process.

**Comment by jthomas** [comment]
This is a great idea @krook. 
Docker Actions are one of the features that people are most impressed with but the developer experience often leaves people confused. 

I experimented with getting Go binaries running as OpenWhisk Actions and ended up provided a Go library that did everything for the user.
https://github.com/jthomas/openwhisk_go_action
https://github.com/jthomas/ow

It would be good to compile a list of popular languages and work out the "fast path" for those developers to go from finishing their microservice to having it running as a Docker Action. This might mean providing new Docker images or libraries that implement the OpenWhisk Action APIs that can use. 

**It would also be useful to document the OpenWhisk Action API using Swagger.** This would make it much easier to implement new runtimes without digging through existing code.

**Comment by rabbah** [comment]
tooling issue.
