### ISSUE TITLE
Error "Registry returned more than one result for consul:v0.7.0" during install

### ISSUE THREAD

**Issue by pjdurai** [apache/openwhisk#1575]
Greetings.

I am trying to build/deploy openwhisk in an Ubuntu Trusty VM using a separate CouchDB instance running on the same VM. 

I have tried in an AWS instance as well as a virtual machine instance (On Windows). Same result.

## Environment details:

* native ubuntu 14.04, Locally installed CouchDB instance.   
* version of docker, vagrant, ubuntu, ...
    Docker: Docker version 1.12.0, build 8eab29e
    Ubuntu: 14.04
     Ansible: ansible 2.1.2.0
## Steps to reproduce the issue:
Follow the instructions to install a Native Ubuntu using a locally installed CouchDB instance.

## Provide the expected results and outputs:

```
output comes here
```

During the step
$ ansible-playbook  openwhisk.yml

I am running into this error.
TASK [consul : ensure consul log directory is created with permissions] ********
Thursday 01 December 2016  09:31:58 +0000 (0:00:00.180)       0:00:03.649 *****
changed: [172.17.0.1]

TASK [consul : (re)start consul server/agent] **********************************
Thursday 01 December 2016  09:31:59 +0000 (0:00:00.113)       0:00:03.762 *****
fatal: [172.17.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Registry returned more than one result for consul:v0.7.0"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
172.17.0.1                 : ok=4    changed=3    unreachable=0    failed=1
ansible                    : ok=2    changed=1    unreachable=0    failed=0

Thursday 01 December 2016  09:31:59 +0000 (0:00:00.492)       0:00:04.255 
setup ------------------------------------------------------------------- 1.52s
setup ------------------------------------------------------------------- 1.37s
consul : (re)start consul server/agent ---------------------------------- 0.49s
write whisk.properties template to openwhisk_home ----------------------- 0.36s
consul : ensure consul config directory exists -------------------------- 0.20s
consul : copy template from local to remote in consul config directory --- 0.18s
consul : ensure consul log directory is created with permissions -------- 0.11s
```

## Additional information you deem important:

This is basically what I am trying to execute  for the installation. CouchDB is already installed and configured through OW_ environment variables.

```
cd
git clone https://github.com/openwhisk/openwhisk.git

cd openwhisk
(cd tools/ubuntu-setup && source all.sh)

sudo pip install --upgrade setuptools

cd ~/openwhisk/ansible
ansible-playbook setup.yml
ansible-playbook prereq.yml

cd ~/openwhisk
./gradlew distDocker

cd ~/openwhisk/ansible
ansible-playbook  initdb.yml
ansible-playbook  wipe.yml
ansible-playbook  openwhisk.yml
#ansible-playbook  postdeploy.yml

```

**Comment by rabbah** [comment]
@csantanapr I think this is related to your recent change?

**Comment by csantanapr** [comment]
@rabbah maybe related.
@pjdurai pull down latest from master, and run ansible-playbook prereq.yml and report back.

I think this should be fix now.

**Comment by csantanapr** [comment]
Fixed by #1571

**Comment by pjdurai** [comment]
Hi Guys
Thanks for the quick help.
It got past that problem but it errored out further down.

```
TASK [cli : pull the latest image of cli] **************************************
Friday 02 December 2016  21:55:13 +0000 (0:00:00.139)       0:20:44.417 *******
skipping: [172.17.0.1]

TASK [cli : run Docker] ********************************************************
Friday 02 December 2016  21:55:13 +0000 (0:00:00.041)       0:20:44.458 *******
fatal: [172.17.0.1]: FAILED! => {"changed": true, "cmd": "docker run --name cli whisk/cli:latest", "delta": "0:00:03.306232", "end": "2016-12-02 21:55:17.092378", "failed": true, "rc": 125, "start": "2016-12-02 21:55:13.786146", "stderr": "Unable to find image 'whisk/cli:latest' locally\nPulling repository docker.io/whisk/cli\ndocker: Error: image whisk/cli:latest not found.\nSee 'docker run --help'.", "stdout": "", "stdout_lines": [], "warnings": []}
[FAILED]
> docker run --name cli whisk/cli:latest
Unable to find image 'whisk/cli:latest' locally
Pulling repository docker.io/whisk/cli
docker: Error: image whisk/cli:latest not found.
See 'docker run --help'.
```

The last commit I am seeing is 0b5b3687b25f02a3853683514add7f571d1edf47

Thanks
Appreciate your help.

pj

**Comment by rabbah** [comment]
consul is gone.
