### ISSUE TITLE
API Gateway - Support updating API definitions.

### ISSUE THREAD

**Issue by jthomas** [apache/openwhisk#1658]
*This is a feature request for the experimental API Gateway service.*

Add a new command `wsk api update` which will modify the API definitions. For example, this would allow people to change the Action bound to a route, supporting "[blue/green deployments](http://martinfowler.com/bliki/BlueGreenDeployment.html)".

Currently, the user has to delete the entire API definition and re-create as new, which leads to a new URL endpoint.

**Comment by rabbah** [comment]
@mdeuser @csantanapr done?

**Comment by mdeuser** [comment]
@rabbah - no, not yet.
