### ISSUE TITLE
More API GW test automation

### ISSUE THREAD

**Issue by mdeuser** [apache/openwhisk#1693]
Create API
- add a new operation to an exiting API basepath/path.  validate.
- add a new path + operation to an existing API basepath.  validate.
- use a swagger file with >1 paths, > 1 operations per path, and a title.  validate.
- Invalid swagger file
  - missing basepath 
  - no paths under the basepath
  - no operations under a path

Delete API
- delete just a single operation from existing API basepath/path/operation(s).  validate other existing operations are left alone.
- delete entire path from existing API basepath/path.  validate other existing paths are left alone.

Delete API
-Two basepaths and delete a path from each one

**Comment by nwspeete-ibm** [comment]
@mdeuser  can you please provide a sample swagger file for your point : use a swagger file with >1 paths, > 1 operations per path, and a title. validate.

**Comment by mdeuser** [comment]
@nwspeete-ibm - the `wsk` CLI can create the swagger for you.  Just use the CLI to create the API as usual, then issue `wsk api get .... > myapi.swagger.json` to export the API in swagger format

**Comment by rabbah** [comment]
@mdeuser @csantanapr done?
