### ISSUE TITLE
Running openwhisk behind a corporate proxy

### ISSUE THREAD

**Issue by pjdurai** [apache/openwhisk#1700]
Greetings

I need some expert advise on how to get OpenWhisk installed and running behind a corporate proxy.
I find it surprisingly hard to figure out how to get Docker Containers working behind a http/https proxy server.

Here are some of the things I tried so far.

   - Setting options like in /etc/default/docker, /etc/environment etc.
   - Running squid as a local proxy to route traffic that comes via 'docker0' interface. I believe http can be achieved this way. How about https?
   - Passing 'Environment' variables in the Dockerfiles. I haven't tried this since docker operations are nicely abstracted by OpenWhisk and I don't want to break the abstraction yet.

So.. is there a good way to accomplish this? Does OpenWhisk offer a way to pass Environment variables into the containers (short of modifying Dockerfiles directly)

Appreciate your time.

Thanks
pj

## Environment details:

* ubuntu 14.04 with embedded couch DB

**Comment by rabbah** [comment]
@pjdurai Did I understand your issue correctly: you're deploying openwhisk behind a firewall and want to route API traffic from outside to the openwhisk router on the inside? (Or do you have some hybrid deployment of the openwhisk container?)

**Comment by pjdurai** [comment]
Actually my concern is the other way round. I am trying to install/run openwhisk behind a corporate proxy server (All out-going traffic in my network goes through this one proxy server, usually specified in  https_proxy environment variable).

I am unable to complete openwhisk installation in an Ubuntu 14.04 VM because it halts when the containers try to download packages from internet. I haven't found a good way to specify this proxy to applications running inside the docker containers.

Thus I was wondering how others are doing it.

Thanks
pj

**Comment by rabbah** [comment]
The cli does support http proxies but that won't help with your build. Maybe @domdom82 can help.

**Comment by hsane2001** [comment]
I am in the same problem. I went in and added ENV proxy setting to all dicker build files and got the build working, but when I run openwhisk with any triggers, all come back with econnreset error unable to connect socket. did you find an answer?

**Comment by rabbah** [comment]
Likely your API host is not set correctly. Closing as stale.
