### ISSUE TITLE
Environment variables aren't defined until invocation.

### ISSUE THREAD

**Issue by jthomas** [apache/openwhisk#1751]
## Environment details:

IBM Bluemix (US-South). 

## Steps to reproduce the issue:

This action demonstrates the issue. 

```
var openwhisk = require('openwhisk');

console.log(process.env['__OW_API_KEY']);
// blows up here....
var ow = openwhisk(); 

function main(params) {
   console.log(process.env['__OW_API_KEY']);
  // ...but this would work.
   var ow = openwhisk(); 
  return { message: 'Hello World' };
}
```

## Additional information you deem important:

`__OW_API_KEY` is [not defined until](https://github.com/openwhisk/openwhisk/blob/master/core/nodejsActionBase/src/service.js#L150-L154) the the invocation occurs. 

The user cannot define the openwhisk client outside the handler function without explicitly providing both the api key and host endpoint.

*Would it be possible to move the variables apart from `deadline` and `activation_id` to the handler init section?* 

If this isn't possible, this behaviour should be documented.

**Comment by jthomas** [comment]
I've just helped another user who ran into this issue. I'm going to add a note to the client library README to call this behaviour out but I can imagine it's going to continue to trip people up.

**Comment by sjfink** [comment]
This also seems somewhat related to #1728 -- in general we need to revamp how we initialize global state of all kinds.

I agree that defining _OW_API_KEY during init() for javascript actions seems like a good idea.   I can't think of any reason not to.

**Comment by homerjam** [comment]
+1

**Comment by rabbah** [comment]
This is now fixed.
