### ISSUE TITLE
Openwhisk native compiler service?

### ISSUE THREAD

**Issue by chadbrewbaker** [apache/openwhisk#1755]
Docker is too much overhead. OpenWhisk needs a native compiler service.

Shelling out is how I got C/Haskell working on AWS Lambda before official support, https://github.com/chadbrewbaker/introToAWSLambda

OpenWhisk has some samples of shelling out to native binaries:
https://github.com/openwhisk/openwhisk-catalog/blob/master/packages/samples/curl/javascript/curl.js

The rub is you need a native compiler as an OpenWhisk service.  Preferably XLC if the service is on a Power architecture. Dare I say COBOL too if IBM wants to have customer retention.

**Comment by jthomas** [comment]
Hello @chadbrewbaker, have you seen this blog post about running binaries on OpenWhisk using the `openwhisk/dockerskeleton` image? 
https://www.ibm.com/blogs/bluemix/2017/01/docker-bluemix-openwhisk/

This approach allows you to easy execute any binary on the platform (that's compatible with the architecture) as shown here: http://jamesthom.as/blog/2017/01/16/openwhisk-docker-actions/

**Comment by rabbah** [comment]
The action loop proxy already takes care of much of this "Serverless compilation and build".
