### ISSUE TITLE
should triggers be available through api gateway?

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk#1805]
```
> wsk trigger create apigw
ok: created trigger apigw
> wsk api-experimental create /hello /trigger post apigw
ok: created API /hello/trigger POST for action /_/apigw
https://$HOST/hello/trigger
> curl https://$HOST/hello/trigger -X POST
{
  "error": "Resource by this name exists but is not in this collection.",
  "code": ...
}
```

That's expected I suppose since the gateway hard codes the collection (and the response above doesn't validate that `apigw` is an action or trigger). Should the gateway allow triggers to be surfaced as well?

**Comment by csantanapr** [comment]
@rabbah cool find !, we should allow user to configure triggers since they are fire and forget, only actions. today the routemgmt actions that configure doesn't have validation for the action value, we should cover this with a test case once we add validation that in the backend for different things:
1. action is an action and not a trigger
2. action exist
3. action can be invoke with provided ow auth key

cc @mdeuser

**Comment by rabbah** [comment]
> we should allow user to configure triggers since they are fire and forget, only actions. 

you mean should NOT?

**Comment by csantanapr** [comment]
Ah I just read the Slack and Rays post now it make sense. https://www.raymondcamden.com/2017/02/02/working-with-openwhisk-triggers
It helps hide the OW auth key, and create 1 - many solutions.

So in theory it should work, why it didn't work again?
It's the same API, a POST to the url provided. Or maybe the construction of the url assumes {actions} 

We need to dig into it, and make it a feature I agree and not block.

**Comment by csantanapr** [comment]
@rabbah hum, that I think about it it might be confusing in some aspect exposing triggers with apigw, what if we start with an experimental web api, allow to add annotation `web-export` to triggers and you get an url that you can fire a trigger anonymous with a GET or POST.

**Comment by csantanapr** [comment]
We can always revisit after we take apigw out of experimental and revisit how to properly expose triggers from end to end including APIGW interface experience.

**Comment by mdeuser** [comment]
The current design/implementation did not take into account using triggers as the API backend.  It's possible to relax this restriction though.

**Comment by rabbah** [comment]
closing as duplicate of #3558.
