### ISSUE TITLE
can't get a list of namespaces in CLI : internal system error

### ISSUE THREAD

**Issue by kerryspchang** [apache/openwhisk#1819]
Environment: MacOS

Issue: the command 

`wsk namespace list`
returns the error
 
`error: Unable to obtain list of available namspaces: Request failure: There was an internal server error. (code 4002301)`

**Comment by mdeuser** [comment]
@kerryspchang - try re-configuring your `wsk` CLI with a new auth key.  Log into Bluemix and then head over to https://console.ng.bluemix.net/openwhisk/learn/cli and issue the `wsk` commands listed in step 2.

**Comment by kerryspchang** [comment]
That works. Thanks!

**Comment by sjfink** [comment]
re-opening: "internal system error" is by definition a bug, no matter what the user does

**Comment by rabbah** [comment]
@markusthoemmes will this go away when you nuke namespaces?

**Comment by rabbah** [comment]
@markusthoemmes assigning to you since I think nuking namespaces is on your radar. Feel free to reassign.

**Comment by pjdurai** [comment]
> nuking namespaces
Could someone provide some insight into what this means?

Thanks
pj

**Comment by rabbah** [comment]
See this pr https://github.com/openwhisk/openwhisk/pull/1914.
