### ISSUE TITLE
scanCode.py must support different standard License headers per-project (per-repo)

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk#1892]
Currently, the scanCode.py scripts accepts "hardcoded" LICENSE headers it scans for (i.e, you have to add them to the actual Python script).  However, different languages (compiled or interpreted) have different spacing or pre-processor directives (such as she-bangs).  In order, for the tool to be more robust it is suggested that we allow a command line parameterized (perhaps pointing to one or more LICENSE files in some standard directory) to be loaded dynamically to check against.  This would make the tool more generally useful for ANY future project. 

In addition, we would like an indicator that allows "fuzzy" matching where the header could be found to appear (start) in the first 'x' characters of the file allowing for she-bangs, etc.  Again, this could be parameterized.  The first targets for this feature would be Python, JavaScript, and Bash scripts.

The end goal would be to allow each project's repo. to setup Travis where they could pass in the list of valid headers for the languages/coding conventions they need to use (as long as they contain the approved Apache ASF header text as required in each of the associated files).

**Comment by cclauss** [comment]
Is this issue closed?

**Comment by rabbah** [comment]
@mrutkows close?

**Comment by rabbah** [comment]
@mrutkows can we enforce that all new files in this repo are now apache licenses or not yet?
i think we can at least do that for java and scala code.

can you enable that?
