### ISSUE TITLE
Support returning metadata about activations 

### ISSUE THREAD

**Issue by cfjedimaster** [apache/openwhisk#2096]
The CLI lets me fetch activations and do basic paging/skipping, but does not provide a way to let me know how many activations exist as a whole. So for example, I want to get all activations for action Foo. I suppose I could keep fetching until I get no results, but I'd like to be able to get basic metadata, for ex, how many activations match that action and when the first/last one was created.

**Comment by rabbah** [comment]
Related to https://github.com/openwhisk/openwhisk/issues/1414#issuecomment-291145174

**Comment by rabbah** [comment]
There is a count API now.
