### ISSUE TITLE
couchdb-snapshot docker image is missing `subjects` and `whisks` DBs

### ISSUE THREAD

**Issue by ddragosd** [apache/openwhisk#2117]
Steps to reproduce:
```docker run -p 5984:5984 openwhisk/couchdb-snapshot```

```
$ curl "http://localhost:5984/local_subjects/_all_docs?include_docs=true"
{"error":"not_found","reason":"no_db_file"}

$ curl "http://localhost:5984/local_whisks/_all_docs?include_docs=true"
{"error":"not_found","reason":"no_db_file"}
```

Where `local` represents the `couchdbPrefix`.

**Comment by duynguyen** [comment]
The issue with `couchdb-snapshot` image still remains. I've seen related discussions in https://github.com/apache/incubator-openwhisk/pull/1928 and https://github.com/apache/incubator-openwhisk-devtools/pull/20. @csantanapr , @ddragosd how should we make progress on this?

**Comment by rabbah** [comment]
I think that we've settled on the design - might you be interested in taking this forward?

**Comment by duynguyen** [comment]
yes I will look into it and create PR.

**Comment by duynguyen** [comment]
@csantanapr I would need to run and test my build script on a similar environment as https://builds.apache.org/view/OpenWhisk/job/OpenWhisk-DockerHub/.
Can I have access to the above, or is there an image to run the same jenkins server locally?

**Comment by csantanapr** [comment]
I think you need to be a committer to get access to jenkins maybe Dragos can help out. 
What image are you referring ? The job runs on Ubuntu 16 on an user jenkins with no root or sido access 
I think the first problem to tackle would be to be able to deploy OpenWhisk and populate the db with everything including catalog l, right now we can't since ansible brakes trying to use the docker rest API using http instead of using unix socket located in /var/...

**Comment by duynguyen** [comment]
ok, thanks for giving the details.
I will try with the environment above.
Currently I'm using the approach by Dragos in https://github.com/apache/incubator-openwhisk/pull/1928. It works manually, now we would just automate it in jenkins.

**Comment by duynguyen** [comment]
I've got the jenkins job working on my local setup.
Before a PR can be opened for it, we need to know where the dependency files are located: `Dockerfile`, `init.sh` and `import.sh` from #1928.
@ddragosd wdyt? would you proceed with #1928 with those 3 files only?

**Comment by rabbah** [comment]
@dgrove-oss is this fixed now (since it's needed for kube)?

**Comment by dgrove-oss** [comment]
Travis (for the deploy-kube project) is building an openwhisk/kube-couchdb image and publishing on docker hub.
