### ISSUE TITLE
Performance comparision

### ISSUE THREAD

**Issue by sridhard** [apache/openwhisk#2164]
Hi,

Is there any performance reports available for openwhisk. I want to know the performance of openwhisk compared to lambda/google-functions. Mainly the response time for different languages, max execution time

**Comment by rabbah** [comment]
Thanks for the question and interest in doing a comparison. We have not yet published benchmarks or a benchmarking methodology. This is however something of interest for the community and the question has come up before in various pull request discussions.

**Comment by sridhard** [comment]
Any plan to measure performance?

**Comment by flux627** [comment]
Also interested in this.

**Comment by rabbah** [comment]
There is no concerted effort yet that I'm aware of to provide a benchmark suite for openwhisk although there are some examples of load generators and tests for AWS and cross platform comparisons. In my view we will need to establish a methodology for measuring the container pool performance (throughout and latency), and load balancer performance. 

There is some initial experimentation for a framework for these which were mentioned on our dev list but we need to elaborate this further. See https://github.com/markusthoemmes/openwhisk-performance for example.

Tagging this related to #2360.

**Comment by rabbah** [comment]
OpenWhisk is the closest open source FaaS platform to AWS lambda in terms of cold start and execution life cycle. In fact in some cases it's even faster. Any performance comparison will be against a hosted deployment and configuration that requires both a benchmarking methodology and a calibration for comparable resources (can't compare an openwhisk deployment with 2 invokers to AWS lambda with hundreds of servers). So a meaningful head to head will be against a hosted provider. 

That said, we have added performance benchmarks in the tests folder (using gatling and owperf). There are several academic papers that also look at the performance of openwhisk. Send a note to the Apache dev list for references.
