### ISSUE TITLE
Improve invoker's log file reading of action containers

### ISSUE THREAD

**Issue by sven-lange-last** [apache/openwhisk#2179]
This issue is a follow-up from reviewing PR #2161 - also check the [discussion](https://github.com/openwhisk/openwhisk/pull/2161#discussion_r113152529) for an improvement proposal.

At the moment, the implementation is using `var` and a `while` loop which makes it rather Java-oriented. Only using `val` and recursion would make it more Scala-idiomatic. In addition, the proposal allows for fine grained unit testing of error conditions and scattered reading because mock reading functions can be injected.

Furthermore, a more robust solution for resource allocation is desired.

**Comment by rabbah** [comment]
Word of caution: let's not blindly trade off being scala-idiomatic vs being performant. Caveat: I have not read the latest discussion on this.
