### ISSUE TITLE
Highly available and scalable deployment how to?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [apache/openwhisk#2239]
Are there any docs on how to deploy OpenWhisk with high availability and scalability? For that, I'd like to use kubernetes but I do not know if this would be optimal or even possible? Also, are there any documentation on how ro manually deploy OpenWhisk (not using ansible)?

Thank you!

**Comment by rabbah** [comment]
In this repo https://github.com/apache/incubator-openwhisk-devtools, you will find alternate deployments support including kubernetes.

**Comment by rabbah** [comment]
The ansible and kube deployments are intended for high availability and scalability. They are used at scale in a number of organizations. We can probably do better with documentation. I'll open a separate issue with actionable work after some more consolidation.
