### ISSUE TITLE
Compile Swift (& Java?) binaries once

### ISSUE THREAD

**Issue by akrabat** [apache/openwhisk#2243]
As it takes so long to compile a Swift (and Java?) action, it would would be useful if they could be compiled once (preferably on upload) and stored so that all invocations used the binary and didn't suffer from the 1-2 second compile time.

**Comment by rabbah** [comment]
as a further generalization, we've discussed the idea of "init" actions which receive a manifest of dependencies, install them locally inside an action runtime container, archive the result and create the intended action as a result. For swift, this included compiling the binary, for Java, pulling the dependencies, pruning and creating the Jar. For node, receiving a package.json, running npm install, and zipping up the dependencies, and for python, creating and sealing the virtual env.

**Comment by akrabat** [comment]
That makes a lot of sense - for Swift we could then use a Package.json to collect dependencies as well.

**Comment by pritidesai** [comment]
Here is the first draft of design. I don't have much experience with creating actions in other runtimes than nodejs so adding only nodejs for now. Will add other runtimes as I finish experimenting with them. Any feedback will be highly appreciated.

# Using the init action

The `/whisk.system/init` action offers a convenient way to deploy an action with its dependencies to OpenWhisk.

The action accepts following parameters:

Parameters 

Parameters    | Description
------------- | -------------
name | Name of the action to be created
location  | Directory containing action files
kind  | Action runtime for example: nodejs:default, swift:default

## Creating action with nodejs runtime

To create an action in nodejs runtime, you must have `index.js` and `package.js` for any dependencies. `/whisk.system/init` installs dependencies locally using `npm install` followed by zipping up the action and its dependencies and creates an action using that zip file.

```
ls -1 helloworld/src/
index.js
package.json
cd helloworld/src/
npm install
zip -rq action.zip *
wsk action create helloworld --kind nodejs:6 action.zip
```

All you have to run is:

```
wsk action invoke /whisk.system/init --param name helloworld --param location helloworld/src --param kind nodejs --blocking
```

### Question: 

Should `/whisk.system/init` be worried about cleaning up after creating helloworld action?

**Comment by mrutkows** [comment]
Perhaps we should not call the action "init" as this has meaning in the context of the CLI.  Perhaps we should (as most actions should) name it according to its granular function.

Also, this would be better as an "implicit" action (not explicit) where we would possible do this as part of create perhaps?

**Comment by csantanapr** [comment]
Yeah I think it would be a package instead, with an action per runtime, since the action would need the runtime anyway to compile, might as well be in the target language
```
whisk.system/compile/nodejs
whisk.system/compile/java
whisk.system/compile/swift
whisk.system/compile/python
```

There is no need for parameter kind

I would make the action accept two modes.
Give it a git info to get the source code from, or a zip

@pritidesai 
I don't follow why you do a `npm install` to create the zip to send to the action, that's what the action is suppose to do so any binaries from npm install are done in the correct runtime.

There should be specific parameters for each kind.
For example for nodejs, I might now that there is no binaries and is all pure js, so using webpack or something similar should be allow, maybe allow for a custom npm script like instead of npm install and zip you could run a npm run script.

**Comment by pritidesai** [comment]
I have implemented solution for nodejs and seeking your feedback, please find details on the solution on GitHub:

https://github.com/pritidesai/incubator-package-build#package-and-deploy-third-party-modules---nodejs

**Comment by rabbah** [comment]
Another issue mentioned a builder service - the action loop proxy makes this easier.
