### ISSUE TITLE
Follow the SPM Paradigm to Configure and Unit Test Your Swift Action 

### ISSUE THREAD

**Issue by ahalls** [apache/openwhisk#2253]
>If you are reporting an enhancement request, please include information on what you are trying to achieve and why that enhancement would help you.

This is an enhancement request.  I would like to use the same approach as the Swift Package Manager uses to configure a project with several actions.  This would support having  multiple source files in an action as well as include the ability to add frameworks. 

However, I don't want to have to have the whole SPM project boiler plate in place for each action.  Actions will be fairly light weight.  I would like to have all the actions for an application to be in the same overall project.  It should be easy to share common code between actions. 

In addition I would like to use the SPM testing facility to unit test my actions. Without the overhead of placing test in a docker container.  So an Xcode jockey like myself can can use familiar tools.

**Comment by rabbah** [comment]
@paulcastro thoughts?
