### ISSUE TITLE
Doc issue with "Get activation IDs"

### ISSUE THREAD

**Issue by cfjedimaster** [apache/openwhisk#2271]
The REST API docs for "Get activation IDs" (https://console.ng.bluemix.net/apidocs/98-ibm-bluemix-openwhisk?&language=node#get-activation-ids) include this argument:

Name: Name of item

But what is an item? If it means the action name, then it should be rewritten to say that:

Name: Name of action

Also, it should clarify if it will support partial matches. Imagine I've got 3 actions called doFoo, doGoo, doZoo. Can I match "do" to all 3? Or imagine I've got somepackage/doFoo. Would me asking for doFoo match or must I provide the package too?

Of course, that's all assuming I'm right that 'item' is action. If I'm not, well, it still needs explaining. :) 

If you do change it to action, don't forget to change the code sample text too.

**Comment by rabbah** [comment]
ibm doc issue.
