### ISSUE TITLE
Update nodejs6 runtime with utilities to allow building node_modules binaries

### ISSUE THREAD

**Issue by csantanapr** [apache/openwhisk#2311]
Some npm packages need binaries to be compiled
The nodejs6action should have everything required for an user to use it to build a nodejs action zip.

This is applicable to packages like [ibm_db](https://www.npmjs.com/package/ibm_db)

For example python, make, zip, g++

Errors with node-gyp
```
{ Error: Command failed: node-gyp configure build 
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```
```
{ Error: Command failed: node-gyp configure build --IBM_DB_HOME="$IBM_DB_HOME" --IS_DOWNLOADED=true
gyp ERR! build error
gyp ERR! stack Error: not found: make
```
```
{ Error: Command failed: node-gyp configure build 
make: g++: Command not found
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
```

**Comment by csantanapr** [comment]
In addition we should look into reducing the amount of disk space consume by the nodejs runtime

- Using `--production` when running `npm install` will avoid installing `devDependencies`
- Going over the node_modules, and write a script to delete any test directories or installer directories
  For example if adding `ibm_db` it adds 80MB of installer code `node_modules/ibm_db/installer` not required for execution
- Have all the `RUN` statements in a single `RUN` encapsulated in a single script ~setup.sh
- Any others :-)

**Comment by rabbah** [comment]
I'd also consider an approach like the one intended for https://github.com/apache/incubator-openwhisk/issues/2300

**Comment by michaelmarth** [comment]
>  The nodejs6action should have everything required for an user to use it to build a nodejs action zip.

Trying to grok your proposal... Do you mean some development-time mechanism (so that compiled binaries get uploaded with the action) or compilation at runtime or installation-time?
When I previously discussed this use case with @ddragosd and @sandeep-paliwal we thought that we would provide tooling that allows developers to compile to the right environment ("right" == "the targeted OW instance") and package the binary along with their NPMs (zip file)

**Comment by csantanapr** [comment]
@michaelmarth This issue will enable such tooling you describe.

This allows to have the "the targeted OW instance" docker image to be use for both purposes to create the zip and also to run it.

Then the tooling can use the docker image to build. Adding git to the docker image will also be beneficial.

I'm hoping that's the end of most common dependencies to add to be able to have a single image for both purposes, and not go to a dual image one for build and another to run the action.

**Comment by sjfink** [comment]
Hmm -- I can't imagine that I want g++ in the docker image for the runtime.    I predict that for performance reasons, we will inevitably have to move to separate images for build and run.

**Comment by csantanapr** [comment]
@sjfink what are the performance problems you referring?

The only changes to the image would be size. 
I was going to look into optimizations we can do to the currrent image trying to make the gain in size minimal.

**Comment by csantanapr** [comment]
I think we found a better way to handle this
Increasing the size of the runtime image is the wrong direction we want to go, I'm actually looking into decreasing the size of the nodejs image.


We will going to make it easier to add new kinds for the languages we already have in place.
This PR #2383 will take the list from group vars manifest in ansbile and docker pull those images into the invoker.

The way we can easily create an image that has a few packages more than the base nodejs, and be deploy in your environment, this would be something for operators to benefit, and then for users you would provide a new kind like `nodejs-acme:6` where this image extend `FROM` the base nodejs image but have more npm packages custom for acme.

There is a related PR #2112, that would allow users to use their own docker images that could extend one of the language ones and create actions with a docker image and a zip, not requiring the operator to pre-populate the images to the invokers. It would be giving an user to create their own kinds

In terms of nodejs actions use for building actions, they would require g++, git, and such so we are thinking on creating a new kind i.e. `action-nodejs-build-v6` were it doesn't matter if the image is bit big as it's not that critical for performance and is more important functionality for deployment time.
We are thinking instead of creating this new image on this repo, we start the process and create a new repo `openwhisk-runtimes` were we build the images from starting with the init/build actions per language.


cc @rabbah
