### ISSUE TITLE
wsk api authentication issues

### ISSUE THREAD

**Issue by akrabat** [apache/openwhisk#2317]
When you use the `api` commands , such as `wsk api list` you get this error:

```
error: Unable to obtain the API list: Unable to obtain API(s) from the API Gateway (status code 400): {"error":{"statusCode":400,"message":"User access token is required"}}`
```

This is confusing as the rest of the `wsk` tool authorises using the `--auth {key}` value that you set with `wsk property set`.

It turns out that API gateway on Bluemix (haven't tested any other installations yet) requires a `wsk bluemix login` command to be issued. I'm unclear why API Gateway needs a separate login from the standard `wsk` authentication system, but if it does, then:

1. The [API Gateway documentation](https://github.com/apache/incubator-openwhisk/blob/master/docs/apigateway.md) needs to be updated to reflect that this part of the project has proprietary authentication.
2. The IBM specific version of `wsk` needs to provide a better error message indicating that `wsk bluemix login` is required.
3. The OpenSource version of `wsk` needs to provide a better error message indicating that a proprietary cli binary version is required for this functionality and the user should obtain this from their OpenWhisk provider.

Obviously, a better solution would be for `wsk api` to just work with the standard OpenWhisk authentication key.

**Comment by rabbah** [comment]
@mdeuser can you comment on this issue?

**Comment by yadavvipinsonu** [comment]
I am getting this error while trying to list  api. everything else action, rule ,trigger is working fine 

command ran :  ./wsk api list -i
Error :   error: Unable to obtain the API list: The requested resource does not exist. (code 247)

can you please suggest what could be the possible reason for this,

**Comment by mdeuser** [comment]
yikes.. just now seeing this issue.. apologies for the very late response @akrabat .  some thoughts..
- the openwhisk apigateway does not require any authentication, so i believe we won't surface this kind of error message in a totally open source environment
- the `wsk bluemix login` command is an ibm cloud functions enhancement and has been deprecated in favor of the `wsk` plugin to the `bx` command.  the api gw required token is handled transparently by the plugin working in conjunction with the `bx login` artifacts.  consequently, the error messages should be more context friendly.

as for the comment from @yadavvipinsonu, are you running against an apache openwhisk backend?  if so, did you deploy the `apimgmt` package?  you can obtain extra debug information by using the `-v` to see the cli's invocation of the backend rest apis to see which one failed.  my guess is that the command to run one of the apimgmt actions was not present.

**Comment by yadavvipinsonu** [comment]
@mdeuser  Thanks for your response!

yes i am working on apache openwhisk backend. 

Below is the error and output that i get when i tried to debug further

[root@cvricapi01 bin]# ./wsk api list -d -v -i
[-go/whisk.addRouteOptions]:051:[Inf] Adding options &{ApiOptions:{ActionName: ApiBasePath: ApiRelPath: ApiVerb: ApiName: SpaceGuid:23bc46b1-71f6-4ed5-8c54-816aa4f8c502 AccessToken:DUMMY TOKEN ResponseType:} Limit:30 Skip:0 Docs:false} to route 'web/whisk.system/apimgmt/getApi.http'
[-go/whisk.addRouteOptions]:076:[Inf] Returning route options 'web/whisk.system/apimgmt/getApi.http?accesstoken=DUMMY+TOKEN&limit=30&skip=0&spaceguid=23bc46b1-71f6-4ed5-8c54-816aa4f8c502' from input struct &{ApiOptions:{ActionName: ApiBasePath: ApiRelPath: ApiVerb: ApiName: SpaceGuid:23bc46b1-71f6-4ed5-8c54-816aa4f8c502 AccessToken:DUMMY TOKEN ResponseType:} Limit:30 Skip:0 Docs:false}
[/whisk.(*ApiService).List]:329:[Inf] Api GET/list route with api options: web/whisk.system/apimgmt/getApi.http?accesstoken=DUMMY+TOKEN&limit=30&skip=0&spaceguid=23bc46b1-71f6-4ed5-8c54-816aa4f8c502
[k.(*Client).NewRequestUrl]:701:[Inf] basepath: https://172.17.0.1/api, version/namespace path: v1, resource path: web/whisk.system/apimgmt/getApi.http?accesstoken=DUMMY+TOKEN&limit=30&skip=0&spaceguid=23bc46b1-71f6-4ed5-8c54-816aa4f8c502
[k.(*Client).addAuthHeader]:298:[Inf] Adding basic auth header; using authkey
REQUEST:
[GET]   https://172.17.0.1/api/v1/web/whisk.system/apimgmt/getApi.http?accesstoken=DUMMY+TOKEN&limit=30&skip=0&spaceguid=23bc46b1-71f6-4ed5-8c54-816aa4f8c502
Req Headers
{
  "Authorization": [
    "Basic MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1A="
  ],
  "User-Agent": [
    "OpenWhisk-CLI/1.0 (2018-04-09T03:50:54.484+0000)"
  ]
}
RESPONSE:Got response with code 404
Resp Headers
{
  "Connection": [
    "keep-alive"
  ],
  "Content-Length": [
    "70"
  ],
  "Content-Type": [
    "application/json"
  ],
  "Date": [
    "Wed, 11 Apr 2018 18:26:03 GMT"
  ],
  "Server": [
    "nginx/1.12.2"
  ]
}
Response body size is 70 bytes
Response body received:
{
  "error": "The requested resource does not exist.",
  "code": 430
}
[o/whisk.PrintResponseInfo]:499:[Inf] Response body received (ASCII quoted string):
"{\n  \"error\": \"The requested resource does not exist.\",\n  \"code\": 430\n}"
[/whisk.parseErrorResponse]:514:[Inf] HTTP failure 404 + body
[/whisk.parseErrorResponse]:525:[Inf] HTTP failure 404; server error The requested resource does not exist. (code 430)
[/whisk.(*ApiService).List]:344:[Err] s.client.Do() error - HTTP req https://172.17.0.1/api/v1/web/whisk.system/apimgmt/getApi.http?accesstoken=DUMMY+TOKEN&limit=30&skip=0&spaceguid=23bc46b1-71f6-4ed5-8c54-816aa4f8c502; error 'The requested resource does not exist. (code 430)'
[whisk-cli/commands/api.go]:526:[Err] Client.Apis.List(&whisk.ApiListRequestOptions{ApiOptions:whisk.ApiOptions{ActionName:"", ApiBasePath:"", ApiRelPath:"", ApiVerb:"", ApiName:"", SpaceGuid:"23bc46b1-71f6-4ed5-8c54-816aa4f8c502", AccessToken:"DUMMY TOKEN", ResponseType:""}, Limit:30, Skip:0, Docs:false}) error: The requested resource does not exist. (code 430)
[main.main                ]:068:[Inf] err object type: *whisk.WskError
[main.main                ]:072:[Err] Got a *whisk.WskError error: &whisk.WskError{RootErr:(*errors.errorString)(0xc4202fc6a0), ExitCode:1, DisplayMsg:true, MsgDisplayed:false, DisplayUsage:false, DisplayPrefix:true, ApplicationError:false, TimedOut:false}
error: Unable to obtain the API list: The requested resource does not exist. (code 430) 

I am able to create action with web=true and get the accessible url .

**Comment by yadavvipinsonu** [comment]
@mdeuser  thansk for your response !
 Based on your comments i tried to install routemgmt.yml file and got below error 

TASK [cli-install : Grab the local CLI from the binaries unarchived into nginx] *************************
Thursday 12 April 2018  16:07:52 -0400 (0:00:02.050)       0:00:07.612 ********
fatal: [ansible]: FAILED! => {"changed": false, "dest": "/home/mparuthickal/openwhisk/ansible/../bin", "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed", "owner": "mparuthickal", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 30040, "url": "**https://172.17.0.1/cli/go/download/linux/amd64/wsk**"}

Request failed

PLAY RECAP **********************************************************************************************
ansible                    : ok=4    changed=1    unreachable=0    failed=1

Thursday 12 April 2018  16:07:52 -0400 (0:00:00.493)       0:00:08.106 ********
===============================================================================
Gathering Facts --------------------------------------------------------------------

and one more error i get when trying to run openwhisk.yml file 

TASK [cli : Download release archive to build directory ...] ********************************************
Thursday 12 April 2018  16:19:49 -0400 (0:00:00.359)       0:01:31.037 ********
fatal: [172.17.0.1]: FAILED! => {"changed": false, "msg": "Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com at port 443: [Errno -2] Name or service not known"}

Failed to connect to github-production-release-asset-
2e65be.s3.amazonaws.com at port 443: [Errno -2] Name or service not known

PLAY RECAP **********************************************************************************************
172.17.0.1                 : ok=10   changed=2    unreachable=0    failed=1

In first error its trying to download somefile from 172.17.0.1 --- which i believe is the cause of error ? where and what should i change to avoid this error.

**Comment by yadavvipinsonu** [comment]
@mdeuser  Thanks for your response! 

I tried all the steps using the -i enviornments/local option in both cent-os 7 and ubuntu 16.04.

In Ubuntu 16.04 every thing ran fine. i am able to create , invoke action , rule , triggers. 
but here also i am not able to create/list api's .
while installation steps every thing ran fine. 
if i run docker ps command , i am able to see all the components up and running including apigateway. 

command ran : ./wsk api list -i
Error : error: Unable to obtain the API list: The requested resource does not exist. (code 247)

**Comment by yadavvipinsonu** [comment]
@mdeuser  thanks !

CLI is not installed correctly. when i run 

ansible-playbook -i environments/local openwhisk.yml

Monday 16 April 2018  11:00:41 -0400 (0:00:00.574)       0:00:49.831 **********
fatal: [controller0]: FAILED! => {"changed": false, "msg": "Error pulling image whisk/controller:latest - 404 Client Error: Not Found (\"{\"message\":\"pull access denied for whisk/controller, repository does not exist or may require 'docker login'\"}\")"}

Error pulling image whisk/controller:latest - 404 Client Error: Not Found
("{"message":"pull access denied for whisk/controller, repository does not exist
or may require 'docker login'"}")

i tried running routemgmnt.yml also , it failed with connection refused error 

ansible-playbook  -i environments/local   routemgmt.yml

TASK [cli-install : Grab the local CLI from the binaries unarchived into nginx] ****************************************************************************************
Monday 16 April 2018  11:16:18 -0400 (0:00:03.486)       0:00:10.615 **********
fatal: [ansible]: FAILED! => {"changed": false, "dest": "/home/mparuthickal/openwhisk/ansible/../bin", "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed: <urlopen error [Errno 111] Connection refused>", "owner": "root", "size": 4096, "state": "directory", "uid": 0, "url": "https://172.17.0.1/cli/go/download/linux/amd64/wsk"}

Request failed: <urlopen error [Errno 111] Connection refused>

------
Tried on cent-os 7 and ubuntu16.04 both. 
It will be great if you can share some specific page you know which i can follow to get openwhisk up and running including api mgmt .

**Comment by yadavvipinsonu** [comment]
Hi @mdeuser @akrabat @rabbah @jthomas @jcrossley3 

I tried to run installRouteMgmt.sh , by passing all the parameters required to it in both(ubuntu and cent-OS ) environments

AUTH="23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
APIHOST="https://10.123.70.204"
NAMESPACE="guest"
OPENWHISK_HOME="/home/ubuntu/incubator-openwhisk-devtools/docker-compose/openwhisk-master"
WSK_CLI="/home/ubuntu/incubator-openwhisk-devtools/docker-compose/openwhisk-master/bin/wsk"
GW_USER=""
GW_PWD=""
GW_HOST_V2="https://10.123.70.204:9000/v1"

then ran below command 

$WSK_CLI -i --apihost "$APIHOST" package update --auth "$AUTH"  --shared no "$NAMESPACE/apimgmt" -a description "This package manages the gateway API configuration." -p gwUser "$GW_USER" -p gwPwd "$GW_PWD" -p gwUrlV2 "$GW_HOST_V2" -d -v 

Output ------------

ubuntu@ip-10-123-70-204:~/incubator-openwhisk-devtools/docker-compose/openwhisk-master/bin$ $WSK_CLI -i --apihost "$APIHOST" package update --auth "$AUTH"  --shared no "$NAMESPACE/apimgmt" -a description "This package manages the gateway API configuration." -p gwUser "$GW_USER" -p gwPwd "$GW_PWD" -p gwUrlV2 "$GW_HOST_V2" -d -v
[commands.NewQualifiedName]:132:[Inf] Qualified pkg+entity (EntityName): guest/apimgmt
[commands.NewQualifiedName]:133:[Inf] Qualified namespace: guest
[commands.NewQualifiedName]:134:[Inf] Qualified package: guest
[commands.NewQualifiedName]:135:[Inf] Qualified entity: apimgmt
[-cli/commands.parseShared]:988:[Err] Sharing is 'false'
[k-cli/commands/package.go]:224:[Inf] Parsing parameters: []string{"{\"gwUser\": \"\"}", "{\"gwPwd\": \"\"}", "{\"gwUrlV2\": \"https://10.123.70.204:9000/v1\"}"}
[mmands.getJSONFromStrings]:058:[Inf] Convert content to JSON: []string{"{\"gwUser\": \"\"}", "{\"gwPwd\": \"\"}", "{\"gwUrlV2\": \"https://10.123.70.204:9000/v1\"}"}
[mmands.getJSONFromStrings]:068:[Inf] Created map 'map[gwUser:]' from '{"gwUser": ""}'
[mmands.getJSONFromStrings]:068:[Inf] Created map 'map[gwUser: gwPwd:]' from '{"gwPwd": ""}'
[mmands.getJSONFromStrings]:068:[Inf] Created map 'map[gwUser: gwPwd: gwUrlV2:https://10.123.70.204:9000/v1]' from '{"gwUrlV2": "https://10.123.70.204:9000/v1"}'
[.getKeyValueFormattedJSON]:091:[Inf] Created key/value format '[{gwUser } {gwPwd } {gwUrlV2 https://10.123.70.204:9000/v1}]' from 'map[gwPwd: gwUrlV2:https://10.123.70.204:9000/v1 gwUser:]'
[k-cli/commands/package.go]:235:[Inf] Parsing annotations: []string{"{\"description\": \"This package manages the gateway API configuration.\"}"}
[mmands.getJSONFromStrings]:058:[Inf] Convert content to JSON: []string{"{\"description\": \"This package manages the gateway API configuration.\"}"}
[mmands.getJSONFromStrings]:068:[Inf] Created map 'map[description:This package manages the gateway API configuration.]' from '{"description": "This package manages the gateway API configuration."}'
[.getKeyValueFormattedJSON]:091:[Inf] Created key/value format '[{description This package manages the gateway API configuration.}]' from 'map[description:This package manages the gateway API configuration.]'
[k.(*Client).addAuthHeader]:298:[Inf] Adding basic auth header; using authkey
REQUEST:
[PUT]   https://10.123.70.204/api/v1/namespaces/guest/packages/guest/apimgmt?overwrite=true
Req Headers
{
  "Authorization": [
    "Basic MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1A="
  ],
  "Content-Type": [
    "application/json"
  ],
  "User-Agent": [
    "OpenWhisk-CLI/1.0 (2018-04-17T03:17:54.816+0000)"
  ]
}
Req Body
{"namespace":"guest","name":"guest/apimgmt","publish":false,"annotations":[{"key":"description","value":"This package manages the gateway API configuration."}],"parameters":[{"key":"gwUser","value":""},{"key":"gwPwd","value":""},{"key":"gwUrlV2","value":"https://10.123.70.204:9000/v1"}]}

[go/whisk.PrintRequestInfo]:458:[Inf] Req Body (ASCII quoted string):
"{\"namespace\":\"guest\",\"name\":\"guest/apimgmt\",\"publish\":false,\"annotations\":[{\"key\":\"description\",\"value\":\"This package manages the gateway API configuration.\"}],\"parameters\":[{\"key\":\"gwUser\",\"value\":\"\"},{\"key\":\"gwPwd\",\"value\":\"\"},{\"key\":\"gwUrlV2\",\"value\":\"https://10.123.70.204:9000/v1\"}]}\n"
RESPONSE:Got response with code 404
Resp Headers
{
  "Connection": [
    "keep-alive"
  ],
  "Content-Length": [
    "64"
  ],
  "Content-Type": [
    "application/json"
  ],
  "Date": [
    "Tue, 17 Apr 2018 21:41:26 GMT"
  ],
  "Server": [
    "openwhisk/api-gateway-1.9.3.1"
  ]
}
Response body size is 64 bytes
Response body received:
{"error":"The requested resource could not be found.","code":24}
[o/whisk.PrintResponseInfo]:499:[Inf] Response body received (ASCII quoted string):
"{\"error\":\"The requested resource could not be found.\",\"code\":24}"
[/whisk.parseErrorResponse]:514:[Inf] HTTP failure 404 + body
[/whisk.parseErrorResponse]:525:[Inf] HTTP failure 404; server error The requested resource could not be found. (code 24)
[.(*PackageService).Insert]:201:[Err] s.client.Do() error - HTTP req https://10.123.70.204/api/v1/namespaces/guest/packages/guest/apimgmt?overwrite=true; error: 'The requested resource could not be found. (code 24)'
[k-cli/commands/package.go]:258:[Err] Client.Packages.Insert((*whisk.Package)(nil), true) failed: The requested resource could not be found. (code 24)
[main.main                ]:068:[Inf] err object type: *whisk.WskError
[main.main                ]:072:[Err] Got a *whisk.WskError error: &whisk.WskError{RootErr:(*errors.errorString)(0xc42035a450), ExitCode:148, DisplayMsg:true, MsgDisplayed:false, DisplayUsage:false, DisplayPrefix:true, ApplicationError:false, TimedOut:false}
error: Package update failed: The requested resource could not be found. (code 24)

can you please check what's wrong here , what should i do to make it run ?

We are still facing issues with api list, api create .

**Comment by mdeuser** [comment]
@yadavvipinsonu - have you been following these instructions? https://github.com/apache/incubator-openwhisk/blob/master/tools/ubuntu-setup/README.md

there's also an openwhisk slack project you might want to consider for more interactive help with your issue.  `openwhisk-team.slack.com`
