### ISSUE TITLE
OpenWhisk & Uberjars

### ISSUE THREAD

**Issue by johnament** [apache/openwhisk#2459]
I was wondering, are there any guides on using OpenWhisk to run an uber-jar?  Can I use my own drop in webserver runtime (e.g. jetty) and have that run on OpenWhisk?

**Comment by rabbah** [comment]
Can you clarify further what you're trying to do?

In general actions cannot receive incoming connections - so running an action as a server is not in scope.

The reason there's a server proxy inside an action is for internal communication with the control system.

**Comment by rabbah** [comment]
The standalone controller FTW.
