### ISSUE TITLE
Nodejs web actions do not support multiple occurences of the same request parameter

### ISSUE THREAD

**Issue by cjelger** [apache/openwhisk#2471]
Calling a nodejs web action with multiple occurences of the same request parameter is not supported. For example, calling

`/api/v1/web/guest/default/hello.http?foo=bar&foo=bar2`

ends up with `foo` being set to `bar2` in the JSON object passed to the web action function.

I would have expected to receive an array with all the values of the request parameters, something like `foo: ['bar', 'bar2']`.

**Comment by rabbah** [comment]
This isn't supported by the akka layer we're using. It will be difficult for us to do without upstreaming changes to akka-http.
