### ISSUE TITLE
If a web action emits CORS header but does not specify the "web-custom-options" annotation, it results in duplicate headers

### ISSUE THREAD

**Issue by l2fprod** [apache/openwhisk#2478]
I have one action that I expose as a web action.

The action returns:
```
  {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Content-Type': 'application/json'
        },
        body: new Buffer(JSON.stringify(result)).toString('base64')
      }
```

When doing a curl, I'm seeing this as the Access-Control-Allow-Origin:
```
< Access-Control-Allow-Origin: *,*
```

Notice the double star. It leads to an error when calling the web action with AJAX from Chrome. You get the error `XMLHttpRequest cannot load https://openwhisk.ng.bluemix.net/api/v1/web/mynamespace/default/fibonacci?iteration=500. The 'Access-Control-Allow-Origin' header contains multiple values '*,*', but only one is allowed. Origin 'http://deployment-options-tester.mybluemix.net' is therefore not allowed access.`

I guess I wrote this action before OW started to emit default CORS headers (https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md#options-requests) and before the introduction of the "web-custom-options" annotation.

If I change my code to not emit the Access-Control-Allow-Origin then it works. OW should report a warning, or not set its default headers if I set them explicitly, or ignore mine.

**Comment by rabbah** [comment]
The cleanest solution is to ignore the user defined headers. @dubeejw thoughts wrt akka port?

**Comment by l2fprod** [comment]
@rabbah if OW ignores my headers, it should let me know it did so and educate me on what to do to make it right. Otherwise I'll have a hard-time figuring out where my headers went.

**Comment by rabbah** [comment]
warn you how?

the annotations are not available inside the action: so we can't easily generate a log message for the action.

the headers are generated during the http request termination; so at that point, a warning can be generated but how do we communicate it back to the user? we could fail the activation with a 40x level status code.

the more involved solution is to accept the action specified headers and override the default ones; this makes the custom cors annotation almost unnecessary.

**Comment by csantanapr** [comment]
I think this one is more about the other verbs and not `OPTIONS`, that we are adding default CORS headers.
I can see how `web-custom-options` can only be applied to `OPTIONS` where it says to the system let the request reach the action and the action will handle the response.

For the other verbs (i.e. GET, POST, etc..), I guess I can see a valid case to say that if the action response contains a header the controller should not add this header and respect the action response as priority, meaning only add the any of the 3 CORS headers only if they are missing.

**Comment by rabbah** [comment]
I don't see how we can make it consistent unless we ignore the response from the action wrt headers - since without the annotation the OPTIONS response will be X and the actually response from the non-OPTIONS verb may be Y. Or we design something else entirely.
