### ISSUE TITLE
Deploy kafka cluster for high-availability

### ISSUE THREAD

**Issue by devbv** [apache/openwhisk#2516]
Currently, we can deploy single kafka node only with ansible script.
So I edited ansible script, whisk configs, and load balancer for deploying kafka cluster with multiple hosts.
If no one is dealing with this issue, can I make a pull-request for it?

**Comment by jeremiaswerner** [comment]
@devbv that awesome and I'am looking forward to see your pull-request. 👍 from my side!

**Comment by rabbah** [comment]
This is now possible. Thanks @devbv.
