### ISSUE TITLE
issue about deploy openwhisk with ansible 

### ISSUE THREAD

**Issue by zhy989** [apache/openwhisk#2586]
When I run CLI  "ansible-playbook -i environments/local openwhisk.yml",there is an error as below:

- TASK [controller : wait until the Controller in this host is up and running] ******************************************************************
Tuesday 08 August 2017  06:44:15 +0000 (0:00:00.910)       0:01:13.509 ******** 
FAILED - RETRYING: wait until the Controller in this host is up and running (22 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (21 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (20 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (19 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (18 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (17 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (16 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (15 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (14 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (13 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (12 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (11 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (10 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (9 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (8 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (7 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (6 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (5 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (4 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (3 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (2 retries left).
FAILED - RETRYING: wait until the Controller in this host is up and running (1 retries left).
fatal: [172.17.0.1]: FAILED! => {"attempts": 22, "changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:10001/ping"}

PLAY RECAP ************************************************************************************************************************************
172.17.0.1                 : ok=23   changed=13   unreachable=0    failed=1   
ansible                    : ok=2    changed=1    unreachable=0    failed=0   

Tuesday 08 August 2017  06:47:59 +0000 (0:03:44.358)       0:04:57.868 ******** 
=============================================================================== 
controller : wait until the Controller in this host is up and running - 224.36s
consul : wait until the Consul Server/Agent in this host is up and running -- 12.61s
kafka : (re)start kafka ------------------------------------------------ 11.03s
consul : pull the consul:0.7.0 image ----------------------------------- 10.00s
kafka : wait until the Zookeeper in this host is up and running --------- 7.22s
kafka : pull the zookeeper:3.4 image ------------------------------------ 5.97s
kafka : pull the ches/kafka:0.10.0.1 image ------------------------------ 5.71s
kafka : wait until the kafka server started up -------------------------- 5.33s
kafka : create the active-ack and health topic -------------------------- 4.64s
kafka : create the invoker topics --------------------------------------- 1.89s
kafka : (re)start zookeeper --------------------------------------------- 1.50s
consul : (re)start consul server/agent ---------------------------------- 1.38s
consul : fill consul kv ------------------------------------------------- 1.06s
controller : (re)start controller --------------------------------------- 0.91s
Gathering Facts --------------------------------------------------------- 0.59s
write whisk.properties template to openwhisk_home ----------------------- 0.55s
Gathering Facts --------------------------------------------------------- 0.45s
consul : start registrator using docker cli ----------------------------- 0.44s
Gathering Facts --------------------------------------------------------- 0.43s
Gathering Facts --------------------------------------------------------- 0.36s

**Comment by spattewar** [comment]
@zhy989 
I was facing the same error and the issue was with the couchdb setup. Did you do the couchDB setup before you ran the openwhisk.yml

Follow the steps given here https://github.com/apache/incubator-openwhisk/blob/master/tools/db/README.md

And then you can follow this section
https://github.com/apache/incubator-openwhisk/blob/master/ansible/README.md#deploying-using-couchdb

Note that as per the experts consul is no longer a part of openwhisk and I could see it in your logs. So it might be better to pull the code again and compile it.

**Comment by dottorsaimon** [comment]
Same problem on Ubuntu 14.04, i tried a lot of times but i arrived alwais at the same error:

Fatal: [172.17.0.1]: FAILED! => {"attempts": 22, "changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:10001/ping"}

My last try was this:

apt-get install git -y
cd /
git clone https://github.com/apache/incubator-openwhisk.git openwhisk
cd /openwhisk
echo "deb http://cz.archive.ubuntu.com/ubuntu trusty main" >> /etc/apt/sources.list
apt-get update
(cd tools/ubuntu-setup && ./all.sh)
apt-get install couchdb -y
curl -X PUT localhost:5984/_config/admins/admin -d '"pass"'
curl -X PUT localhost:5984/_config/query_server_config/reduce_limit -d '"false"' -u admin:pass
printf "[db_creds]\ndb_provider=CouchDB\ndb_username=admin\ndb_password=pass\ndb_protocol=http\ndb_host=127.0.0.1\ndb_port=5984" > /openwhisk/ansible/db_local.ini
sed -i 's/;bind_address = 127.0.0.1/bind_address = 0.0.0.0/g' /etc/couchdb/local.ini
cd /openwhisk
./gradlew distDocker
cd /openwhisk/ansible
ansible-playbook -i environments/local setup.yml
ansible-playbook -i environments/local couchdb.yml --tags ini
ansible-playbook -i environments/local prereq.yml
ansible-playbook -i environments/local initdb.yml
ansible-playbook -i environments/local wipe.yml
ansible-playbook -i environments/local apigateway.yml
ansible-playbook -i environments/local openwhisk.yml
ansible-playbook -i environments/local postdeploy.yml

**Comment by rabbah** [comment]
Check your controllers logs for an exception. 

wskadmin syslog get controller0

**Comment by rkhunter** [comment]
For those doing docker setup and installed couchdb on localhost instead of docker, assign DB to host's docker ip address. Docker logs controller won't show anything
