### ISSUE TITLE
Nginx component doesn't support HA

### ISSUE THREAD

**Issue by ningyougang** [apache/openwhisk#2629]
###  The current situation for nginx
Currently, nginx component doesn't support HA which means if the unique nginx shutdowns, the openwhisk can't work well.

### How to support it.
Use keepalive to support it. please refer to:
https://www.nginx.com/resources/admin-guide/nginx-ha-keepalived/

So we can introduce keepalived for nginx node, and configure a vip to point the active nginx node, if the nginx node shutdowns, the vip will drifts to the slave node.
 
### Everyone's opinion
Has any plan to support this?
Has any other better solution?

**Comment by ningyougang** [comment]
Currently, i know `couchdb` and `kafka` themself support cluster.
But in openwhisk,  they don't support.
Has any plan to support them?

**Comment by rabbah** [comment]
It's possible to deploy multiple nginx instances and load balance between them but usually you need an LB in front. Going to close as stale.
