### ISSUE TITLE
issue about deploy openwhisk with ansible

### ISSUE THREAD

**Issue by zhy989** [apache/openwhisk#2651]
when I run the CLI " ansible-playbook -i environments/local  openwhisk.yml
", there is an error as below:
- TASK [invoker : pull runtime action images with tag latest] **************************************************************************************************************************
Saturday 19 August 2017  14:28:37 +0800 (0:00:00.034)       0:01:01.348 *******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TemplateRuntimeError: no test named 'equalto'
fatal: [172.17.0.1]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP ***************************************************************************************************************************************************************************
172.17.0.1                 : ok=15   changed=10   unreachable=0    failed=1

Saturday 19 August 2017  14:28:37 +0800 (0:00:00.018)       0:01:01.367 *******
===============================================================================
kafka : pull the zookeeper:3.4 image ----------------------------------- 11.11s
controller : wait until the Controller in this host is up and running -- 10.83s
kafka : pull the ches/kafka:0.10.2.1 image ----------------------------- 10.15s
kafka : wait until the Zookeeper in this host is up and running --------- 7.35s
kafka : wait until the kafka server started up -------------------------- 5.36s
kafka : (re)start kafka ------------------------------------------------- 3.64s
kafka : (re)start zookeeper --------------------------------------------- 3.29s
controller : (re)start controller --------------------------------------- 2.06s
kafka : create the invoker topics --------------------------------------- 1.71s
kafka : create the health topic ----------------------------------------- 1.69s
kafka : create the active-ack topics ------------------------------------ 1.68s
Gathering Facts --------------------------------------------------------- 0.83s
Gathering Facts --------------------------------------------------------- 0.53s
Gathering Facts --------------------------------------------------------- 0.48s
controller : ensure controller log directory is created with permissions --- 0.29s
controller : remove controller log directory ---------------------------- 0.03s
invoker : pull invoker image with tag latest ---------------------------- 0.03s
kafka : remove zookeeper ------------------------------------------------ 0.03s
invoker : docker login -------------------------------------------------- 0.03s
controller : docker login ----------------------------------------------- 0.03s

**Comment by markusthoemmes** [comment]
@zhy989 make sure to install the defined version of jinja: `sudo pip install jinja2==2.9.6`

**Comment by zhy989** [comment]
@markusthoemmes thanks

When I installed jinja2==2.9.6 , there is another error as below:

- TASK [invoker : determine docker root dir] ****************************************************************************************************************************************************************
Saturday 19 August 2017  17:15:10 +0800 (0:00:00.030)       0:01:26.095 *******
fatal: [172.17.0.1]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.1:4243/info"}

PLAY RECAP ************************************************************************************************************************************************************************************************
172.17.0.1                 : ok=15   changed=8    unreachable=0    failed=1

Saturday 19 August 2017  17:15:10 +0800 (0:00:00.202)       0:01:26.297 *******
===============================================================================
kafka : pull the ches/kafka:0.10.2.1 image ----------------------------- 19.74s
kafka : pull the zookeeper:3.4 image ----------------------------------- 13.65s
controller : (re)start controller -------------------------------------- 12.23s
kafka : (re)start kafka ------------------------------------------------ 11.96s
kafka : wait until the Zookeeper in this host is up and running --------- 7.35s
controller : wait until the Controller in this host is up and running --- 5.64s
kafka : wait until the kafka server started up -------------------------- 5.44s
kafka : (re)start zookeeper --------------------------------------------- 2.47s
kafka : create the invoker topics --------------------------------------- 1.73s
kafka : create the active-ack topics ------------------------------------ 1.72s
kafka : create the health topic ----------------------------------------- 1.69s
Gathering Facts --------------------------------------------------------- 0.73s
Gathering Facts --------------------------------------------------------- 0.50s
Gathering Facts --------------------------------------------------------- 0.48s
controller : ensure controller log directory is created with permissions --- 0.29s
invoker : determine docker root dir ------------------------------------- 0.20s
invoker : pull runtime action images with tag latest -------------------- 0.08s
invoker : pull invoker image with tag latest ---------------------------- 0.03s
controller : remove controller log directory ---------------------------- 0.03s
controller : docker login ----------------------------------------------- 0.03s

I try to deploy openwhisk with ansible on "CentOS Linux (3.10.0-514.26.2.el7.x86_64) " , is it feasible?

**Comment by rabbah** [comment]
@zhy989 did you succeed on centos?
