### ISSUE TITLE
Default Python actions to use Python 3

### ISSUE THREAD

**Issue by brylie** [apache/openwhisk#2725]
The documentation says the following about Python actions:

> can also create an action that runs with Python 3.6 by explicitly specifying the parameter --kind python:3.

By this point, Python 3 is established as the recommended Python version. The OpenWhisk platform can align with Python 3 by using as default.

Where projects need to use Python 2.7, they can specify `--kind python:2`

**Comment by rabbah** [comment]
It is the default already now.
