### ISSUE TITLE
What is the purpose of each component in openwhisk??

### ISSUE THREAD

**Issue by spattewar** [apache/openwhisk#2894]
Hello Experts,

I have done local openwhisk installation and after checking the docker container i could see many components run as part of openwhisk. do these toghether form the openwhisk architecture?.
for e.g.
nginx
kafka
zookeeper
registrator
apigateway
redis
couchdb

Can someone provide functions of each component above? Sometimes understanding the basics in depth helps to understand how to system is working and trouble shoot issues. I can run action and get response but understanding what is happening behind the scenes is really helpful.

I really appreciate your help in answering my questions.

Regards
Swapnil

**Comment by markusthoemmes** [comment]
Hi,

for a starter you might want to read [my article on the general architecture](https://medium.com/openwhisk/uncovering-the-magic-how-serverless-platforms-really-work-3cb127b05f71). Take consul out of this picture, it's gone by now. So is registrator.

**Comment by spattewar** [comment]
Hi @markusthoemmes 
thank you for your response and the information document. It is nice.

But it does not talk about redis or zookeeper. Why are these components used? Apigateway?

Appreciate time and support
Regards

**Comment by markusthoemmes** [comment]
APIGateway is an API building facade in front of the OpenWhisk API. It facilitates creating APIs that map, say, a `GET /animals` request to a GET `/api/v1/namespaces/zoo/actions/animals` (pseudo urls, but maybe that transfers the idea).

Zookeeper is solely used by Kafka to keep track of its internal state.

Redis is used by APIGateway for its internal state and also by the Invoker to get a unique identifier for itself (if you choose to use that option)

**Comment by spattewar** [comment]
@markusthoemmes 
Thank you very much for your inputs!!
