### ISSUE TITLE
Proposal to to reorganize core/ and root(openwhisk/) folders to reflect existing architecture better

### ISSUE THREAD

**Issue by ServoKvd** [apache/openwhisk#2911]
(Please find attached the png with the proposed directory structure)
![routemgmt](https://user-images.githubusercontent.com/10113782/33883709-2944e4aa-df80-11e7-8916-da1d01bc5528.png)
![routemgmt](https://user-images.githubusercontent.com/10113782/33883728-40622e90-df80-11e7-95e5-95cae28ac70e.png)

Current  core folder:
actionProxy   javaAction       python2Action  swift3.1.1Action 
controller      nodejs6Action pythonAction    swift3Action 
invoker          php7.1Action  routemgmt 

rename actionProxy --> dockerAction

New core folder:
controller  invoker

Move " dockerAction javaAction python2Action pythonAction  swift3.1.1Action swift3Action nodejs6Action " to "../actionProxies" folder 
Move "routemgmt" to "../apigw" folder. 

So 2 new folders to be created in the root folder for 'runtimes" & "apigw" functionality.

**Comment by bwmcadams** [comment]
I'd be concerned with naming the folder to hold the actions `runtimes`, since there are separate openwhisk-runtime folders which define the actual docker images for the actions. For pure confusion sake, is there a different term that could be used for that folder?

**Comment by ServoKvd** [comment]
I agree, it makes sense for "runtimes folder: to contain the docker images for supported runtimes rather than the  "supported-runtime-action-proxies". 
However I did not see the "runtimes" folder in incubator-openwhisk, which folder are you referring to ?

**Comment by bwmcadams** [comment]
The actual runtime "base" for each language is a separate repo…

- Python: [https://github.com/apache/incubator-openwhisk-runtime-python]()
- Java: [https://github.com/apache/incubator-openwhisk-runtime-java]()
- Swift: [https://github.com/apache/incubator-openwhisk-runtime-swift]() 
- etc, etc.

This is the actual code that runs in the docker container for a given language, with the user provided action code loaded onto that. That's what I mean by the confusion (I suspect someone else may be able to add more detail to this than I have provided…)

**Comment by ServoKvd** [comment]
I see - Thank you for the reference. I will upload a patch with above proposed names.

**Comment by ServoKvd** [comment]
I looked at all the build & test folders, looks like " acitonContainers" may be more appropriate name for this folder with all action docker skeletons, as also referred to in the  "tools/build/redo" to make individual components.

**Comment by ServoKvd** [comment]
Affected files with moving the action skeletons 
from  incubator-openwhisk/core --> incubator-openwhisk/actionContainers:

1. settings.gradle
2. bin/wskdev
3. tests/build.gradle
4. tests/dat/blackbox/badaction/build.gradle
5. tests/dat/blackbox/badproxy/build.gradle
6. tools/travis/build.sh
7. tools/build/redo

compilation goes thru fine ( though some files are not touch in the main build- will do some container tests with new images and submit the change list) . 

-

**Comment by ServoKvd** [comment]
Hi All,
Pushed a patch for above @bwmcadams https://github.com/apache/incubator-openwhisk/pull/2933
however the ' Reviewer's tab is not active ( no link) for me to pick up reviewiers from there.
Any idea?

**Comment by bwmcadams** [comment]
@ServoKvd I'm not able to review; one of the committers would have to review and/or assign reviewers. You may want to raise the issue on the mailing list and/or slack?

**Comment by ServoKvd** [comment]
The runtimes are moved to actionRuntimes from core/
Regarding the correct place for routemgmt, still discussing if it belongs in https://github.com/apache/incubator-openwhisk-catalog or a separate repo that can pulled in and installed as part of post-deploy or something like that.

**Comment by csantanapr** [comment]
@ServoKvd I’m debating between the catalog repo or move it into the CLI repo. 
This actions should not exist they exist as CLI helpers for the CLI api command. 
Or move them to the apigateway repo. 


Would like to get input from @mdeuser which is the main contributor and maintainer of this code and associated test cases. 

We have to take into consideration that CLI and CLI tests are moving to its own repo.

**Comment by rabbah** [comment]
Why not api gw repo? Would that work?

**Comment by csantanapr** [comment]
Like I said that would be my two options on the table CLI or agigw
Regardless we need to when we decide todo the following:
1. configure Travis in the receiving repo to deploy from same repo for PR testing
2. Update ansible deployment in this repo to git clone a hash/tag of those action and installed them in a way that be leverage by 1. By passing hash/tag via ansible override

**Comment by ServoKvd** [comment]
Hi csantanapr, rabbah, 

I looked at the current  "incubator-openwhisk-cli" repo -  to me looks like "routemgmt get/deletecreate apis",  may belong with the "test" repo rather than the cli or apigw repos.
The tests that make calls to the routemgmt apis are:
-- **tests/src/test/scala/whisk/core/cli**/test/WskApiGwTests.scala
-- **tests/src/test/scala/whisk/core/apigw**/actions/test
-- **tests/src/test/scala/common/rest**/WskRest.scala

Are there any plans to have a separate "tests" repo? In that case, I think  routemagmt install scritps belong there, as a pre-req to test-setup. 
Could you comment on where the above "tests" folder in the incubator-openwhisk might end up?

Thank you,

**Comment by csantanapr** [comment]
Hi @ServoKvd 

There should not be a "tests" repo, each component in whisk has a corresponding repo and that repo contains the source code for the component and the associated tests for that component.

For the tests:
1. **tests/src/test/scala/common/rest/WskRest.scala**
Should remain on this repo as is the base framework to run tests using REST API instead of using cli

2. **tests/src/test/scala/whisk/core/apigw/actions/test**
Should be remove once the apiwg source for the actions are moved the CLI repo
They are already duplicated in CLI repo https://github.com/apache/incubator-openwhisk-cli/tree/master/tests/src/test/scala/whisk/core/apigw/actions/test/

3. **tests/src/test/scala/whisk/core/cli/test/WskApiGwTests.scala**
This one is using **common.Wsk**, and is testing the CLI apigw feature, this tests is already in the CLI repo here https://github.com/apache/incubator-openwhisk-cli/blob/master/tests/src/test/scala/whisk/core/cli/test/WskApiGwTests.scala
@houshengbo is this correct? That it should be removed, and also any tests using **common.Wsk** instead of **common.Wsk**

**Comment by ServoKvd** [comment]
Hi Carlos ,
Thank you for the quick reply. All the tests require the "routemgmt apis" to be installed - so I was wondering where the "install of routemgmt apis" should be. if above test cases are in different repos, each of those need to call installroutemgmt.sh - I was wondering if I  should just move the routemgmt code to the apigw repo or to a new repo all together and all test cases can run the install script from here, as "test-setup" or something.   And in future if more such install scripts are there, they can belong in this repo. Or perhaps just leave them in the main repo as it is now- so that other repos can use  from here.

**Comment by mdeuser** [comment]
Some considerations.
1. testing the `wsk api` commands will require a backend, api gw, and the apimgmt package
2. currently, the the `wsk api` commands must be built as part of the cli build - since cli is not pluggable.
3. currently, an openwhisk installation includes the installation of the apimgmt package (routemgmt.yml)

Possible organizations
A. separate api gw repo.  cli repo clones this repo and thoughtfully overlays the `wsk api` code onto the cli repo code.  agi gw repo also includes the apimgmt package install/uninstall scripts.  openwhisk deployment defines the api gw and apimgmt deployment scripts that leverage the apimgmt install/uninstall scripts.  api gw repo also includes api gw tests.  these tests could be run as part of api gw repo travis (need to build cli, deploy openwhisk which includes api gw and install apimgmt package).  or only runs tests as part of cli repo test

B. keep `wsk api` code (cli source, install/uninstall scripts, tests) as part of the cli repo. openwhisk deployment defines the api gw and apimgmt deployment scripts that leverage the apimgmt install/uninstall scripts.  `wsk api` tests run as part of cli test (requires deployed openwhisk which includes api gw and install apimgmt package)

**Comment by ServoKvd** [comment]
B is more or less how it is today - ie. hosted in main repo and executed, as part of deploy scripts. 
Looks like (A) may be the way to go - based on the comments from @csantanapr and @rabbah as well and the deploy scripts will overlay with apigw and cli repos as needed.

**Comment by rabbah** [comment]
I’d think the cli can stay as is wrt wsk api. It should assume these components are there and the Travis build can install the routes etc. you could consider a build flag for the cli to enable it disable the api gw commands if concerned about building a cli with api gw cmds but not deploying the api gw.

**Comment by ServoKvd** [comment]
Yes - I guess the Install can happen in setup.sh of the Travis build.  I will submit the CL along these lines.

**Comment by csantanapr** [comment]
I will prefer we don't do a one off for setup.sh in Travis.
I propose we keep using ansible, this allows for similar integrations and deployments we have today in different environments.

Blueprint:
1. Move core/routemgmt to cli repo openwhisk-cli/routemgmt/
2. Move ansible/role/routemgmt/[installRouteMgmt.sh, uninstallRouteMgmt] to cli repo openwhisk-cli/routemgmt/
Adjust scripts based on new location and how they are called from ansible now (i.e. no need for OPENWHISK HOME
3. Update ansible/group_vars/all with location of routemgmt actions/package
```yaml
routemgt:
  url: https://github.com/apache/incubator-openwhisk-cli.git
  # Set the local location as the same level as openwhisk home, but it can be changed.
  location: "{{ openwhisk_home }}/../openwhisk-cli-apigw"
  version: "HEAD"
  repo_update: "no"
```
4. Update ansible/role/routemgmt/deploy.yml to git clone and run install script
```yaml
- name: download the catalog repository to the catalog location if necessary
  git:
    repo: "{{ routemgmt.url }}"
    dest: "{{ routemgmt.location }}"
    update: "{{ routemgmt.repo_update }}"
    version: "{{ routemgmt.version }}"

- name: install route management actions
  shell: ./installRouteMgmt.sh {{ catalog_auth_key }} {{ api_host }} {{ cli.path }} chdir="{{ routemgmt.location }}/routemgmt"
```
5. Update ansible/role/routemgmt/clean.yml to call uninstall script from cloned location
```
- name: remove route management actions
  shell: ./uninstallRouteMgmt.sh {{ catalog_auth_key }} {{ api_host }} {{ cli.path }} chdir="{{ routemgmt.location }}/routemgmt"
```
6. Refactor deploy.yml and installRouteMgm.sh to not depend on file whisk.properties, instead pass in to script more arguments with ansible variables {{apigw_auth_user}} {{apigw_auth_pwd}} {{apigw_host_v2}}
```
- name: install route management actions
  shell: ./installRouteMgmt.sh {{ catalog_auth_key }} {{ api_host }} {{ cli.path }} {{apigw_auth_user}} {{apigw_auth_pwd}} {{apigw_host_v2}} chdir="{{ routemgmt.location }}/routemgmt"
```

Doing this will not require any changes to Travis deployment  in apigateway repo, cli repo, or openwhisk repo.

**Comment by rabbah** [comment]
Seems wrong to put a backend/server side deployment in a client repo. Why not the API gw repo?

**Comment by ServoKvd** [comment]
I was leaning towards keeping core/routemanagement ( the code for get/delete/create) in apigw repo and put the install scripts in cli, that means cli will have to do a "git clone on the apigw" repo to get to the modules to install.
Had a lengthy discussion offline with Carlos - if we view "routemgmt code" as part of cli interface to install some actions, needed for tests rather than apigw or backend functionality, then Carlos proposal makes sense, but if "routemgmt apis" are to be viewed as apigw functionality ( like I was also inclined to view them), then atleast core/routemgm belongs to apigw.
Also is "incubator-openwhisk-cli"  a client repo? , in the sense, is it on par with  "js-client" "python-client"  repos?

**Comment by ServoKvd** [comment]
I guess carol's main concern was with "ansible scripts" instead of moving install to setup.sh - So I will stick to  moving core/routemgmt to apigw and clone this repo in the ansible scripts
Testing now - Should be able to push the patch tomorrow

**Comment by ServoKvd** [comment]
Just a heads up-
I created 2 new pull requests in apigw & incubator-openwhisk, The pull request is merging some other commits that I didnt intend to - I guess this is bcz I was just working off of master insted of a new branch for each change- i was tryign to see if I can change my master to a later commit - will figure it out.
