### ISSUE TITLE
De-link Kafka-topic from Invoker-Id

### ISSUE THREAD

**Issue by ServoKvd** [apache/openwhisk#2913]
Today, there is one-to-one mapping between Kafka topics and Invoker_ids.
I think  Kafka topics should be agnostic of the Invokers. 
The Controller can route the messages to a specific Kafka-topic ( say, c-functions, nodejs-functions, python-functions, heath-topic etc.)  
The Loadbalancer can subscibe to a specific Kafka topic and route the messages to  available Invokers.

This issue proposes to rewrite the Controller & LoadBalancer to be Kafka-Message-Producer & Kafka-Message-Consumer respectively, instead of the Invoker-Id being the topic ( hence topic-consumer directly).

**Comment by dgrove-oss** [comment]
Could you provide some background on the problem you are trying to solve by proposing this change?  Why is it desirable to split the incoming actions into per-language runtime topics that are separately load balanced?  At first glance it seems like this would add additional latency to the system (an extra level of queuing) with no obvious benefit.  Could you motivate why splitting the incoming workload into multiple streams before it hits the load balancing layer is needed?

Thanks!

**Comment by ServoKvd** [comment]
Hi Dave,

Kafka-topics are for  "payload/message categories" and Invokers are Architectural entity instances,
So  making the categories/topics to directly(1-1) map to Invoker-Ids is inflexible, Architecturally, I think. 

As we know the Invokers can keep coming and going down and when an Invoker goes down the remaining messages in the partition should be automatically picked up by an Invoker with the same capabilities (eg. runtime, size of payloadetc.) ,  because an Invoker subscribes to a specific topic, based on its capabilities, so I think a topic should be tied to "capabilities - e.g runtime" than an Invoker-Id.

I'm expecting the latency may be more or less same, as the load-balancing is done by automatic subscription and the number of partitions  in Kafka. But there should be a  clear Kakfa Message Producer &   Kafka Message Consumer", and the "Controller" & "LoadBalancer" can be Producer & Consume respectively.

Also of the 3 models for Kafka mentioned  @ https://kafka.apache.org/intro probably, in openwhisk context,  it is a  a bit of "storage -system" for the messages, until they are addressed/consumer" , along with being a Messaging system (for other topics like Health and Invoker Registration) 

This is my thinking -  please correct/add as you see fit. 

Thank you,

**Comment by markusthoemmes** [comment]
There is quite a bit of history of the loadbalancer. There is one specific issue which prevents OpenWhisk to be auto-loadbalanced by Kafka's partitioning: locality.

Our loadbalancer has a very strong locality constraint. We need to make use of warm containers as much as possible to keep performance numbers anywhere acceptable. Balancing via consumer groups won't give us that locality necessarily. Do you know how if it's possible to implement that constraint on consumer groups?

@tysonnorris proposed a change to our topic design which is being implemented on the dev list. You might want to look that up for some more context.

**Comment by ServoKvd** [comment]
Hi Markus,
thank you for the info. Could you explain a bit more what u mean by " locality"? - some kind of cache, where u request for prewarm/specific containers?  I will grep on the dev-list for messages from "tysonmorris".

**Comment by tysonnorris** [comment]
@ServoKvd there is a thread here: https://lists.apache.org/thread.html/bb94eb7bb9cd29b9fef2515936e031bcb36357b8ec5ec55dfc03ed26@%3Cdev.openwhisk.apache.org%3E

What Markus is getting at is that regardless of which invoker an activation is routed to for the first execution of the action, subsequent executions of the same action should be routed to some invoker where the action is already running in a container (since container startup and init is relatively expensive). While I agree its possible to use unique consumer groups + partitions instead of unique toipcs, I think this will be a moot point once the scheduling is done at execution time (and flexibility of NOT using partition keys can be maintained). 

Separately, there's some other issues you are adding to the mix, like "action priority" where different actions may be queued in separate topics - currently the queues (or single queue, ultimately) operate strictly as FIFO ordering, and I don't think there is a good reason to change that based on action or kind. It may be nice at some point to allow more configuration options for prewarm/warm containers, but this is a change for invokers and not the loadbalancer, I think.

**Comment by ServoKvd** [comment]
Hi Tysonnorris,
Thank you for the link.  IMO, Kafka should be used only for queuing, not for routing; routing should be done by the LoadBalancer.  The "kafka topics" may be used to define " priority-topic", "overflow-topic" etc.   so that LB can prioritize by consuming messages in one topic over the other.  And we could have as many topics as needed. 
But "caching"  to use pre-warm, warm containers  should be considered, as dgrove mentioned on one of the threads, that can be dealt with at the Invoker, we should not ring that logic into Kafka-topics I think.

**Comment by ServoKvd** [comment]
I was thinking along the followign lines- diagram, as per the previous diagrams, but with load balancer doing the switching to Invokers. 
![image](https://user-images.githubusercontent.com/10113782/32372689-48fdfc2a-c0d9-11e7-8832-ac0376d104a8.png)

**Comment by markusthoemmes** [comment]
In your picture, how does the loadbalancer handle communication to the Invoker?

**Comment by ServoKvd** [comment]
I need to prototype and see how it works in terms of code, but I'm thinking along the following lines: 

Say, add a function, say schedule() that chooses an Invoker for a topic, in LoadBalancerService.scala,:
def  scheudle(action  ExecutableWhiskAction, msg ActivationMessage){
....
chooseInvoker().sendActivationToInvoker()
....
//Inside above  sendActivationToInvoker() copy the following code from InvokerReactive.scala: 
val consumer = msgProvider.getConsumer(config, "invokers", topic, maximumContianers, maxPollInterval = TimeLimit.MAX_DURATION + 1.minute)
val activationFeed = actotSystem.actorOf(Props {
    new MessageFeed("activation", logging, consumer, maximumContainers, 500.milliseconds, processActivationMessage)})
 ...
---------------------------------------------------------

**Comment by markusthoemmes** [comment]
That's fine, the Invoker and the Loadbalancer are two separate components though. If you take Kafka communication out between them, how is work by the loadbalancer put into the invoker? HTTP? Akka? Some other protocol? Am I misunderstanding the proposal?

**Comment by ServoKvd** [comment]
Ah, Yes - that's right.  I did think of it, but lost the though there. 
It will have to be over the REST API then - I will code the details and check- am not that familiar with Akka yet, I will look it up, if it should be Actor etc.

**Comment by markusthoemmes** [comment]
I think this is entirely in line with @tysonnorris's proposal, which will only buffer to Kafka if the loadbalancer detects overload.

In @tysonnorris's proposal, LB -> Invoker communication stays over Kafka though. Are you proposing to get rid of that bit specifically?

Or taking one more step back rather: What concern are you trying to address?

**Comment by ServoKvd** [comment]
Hi Markus,

In today's implementation, the "mapping of  topic-name to invoker-id" is referred to as " fast-binding", for performance.  As I understand, TysonNorris's proposal is adding a bit of flexibility to this, by adding a overflow-topic, as a flow-control mechanism, since by the time an action-request reaches an Invoker, the Invoker state may change. 

The problem, I am trying to address is "topic-per-invoker" -  ie. get rid of 1-1 mapping of topic to Invoker. Partitions in the Kafka Bus are meant for addressing scalability & parallel-processing, topic is a higher-level construct like a queue. I think, with Kafka, the way to address scalability is to route a specific partition to an Invoker, dynamically - which is something that a LoadBalancer can do. In the worstcase, 1 partition has 1 action-request in it.  The LoadBalancer can put all the "action-requests" per Invoker to a queue, at the Invoker; Using Kafka for this communication may be a overkill. 

When it comes to solution, there may be a overlap between what Tyson is proposing and what I'm proposing and thru discussion perhaps we can design something that addresses both.

**Comment by tysonnorris** [comment]
I opened a PR #2932  with initial work on the overflow topic.

**Comment by ServoKvd** [comment]
I think it would be better if the LB can write to a Kafka ( zookkper) partition rather than a Kafka topic, thus
the number of Topics can be independent of Number of Invokers( scalability):
Partitions are supposed to address that scalability.
Found some links on how to write to a Kafka partition as opposed to Kafka topic.
https://stackoverflow.com/questions/18202986/kafka-partitioner-class-assign-message-to-partition-within-topic-using-key
https://dzone.com/articles/kafka-producer-architecture-picking-the-partition
http://www.jakubkorab.net/2015/12/message-distribution-and-topic-partitioning-in-kafka.html
Working on a WIP patch.

Also we could hav ea hybrid solution where there are 2 Load Balancers involved, 1 for high-pri actions and another for low-priority actions, where the Invoker assignment is done Lazily, by a 2ndary Load Balancer
![lb3](https://user-images.githubusercontent.com/10113782/33941690-cd6207f8-e056-11e7-922c-9232b4399aca.png)

**Comment by rabbah** [comment]
There are several proposals in the wiki for rethinking the work distribution. I'm going to close this as stale and hopefully we will soon have a better way for proposals.
