### ISSUE TITLE
Add more instructions for autocomplete on mac _get_comp_words_by_ref: command not found

### ISSUE THREAD

**Issue by csantanapr** [apache/openwhisk#2924]
I worked with an user that was constantly getting the following error when doing `wsk TAB`
```
_get_comp_words_by_ref: command not found
```
It looks that for Mac users in addition of installing the bash-completion
```
brew install bash-completion
```
The user also have to configure bash-completion package in their `~/.bash_profile` if they have one or in the `~/.profile`
By adding the following
```
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi
```

**Comment by yevgeniyo** [comment]
thank you
