### ISSUE TITLE
Missing document for wskadmin

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/openwhisk#2926]
There is no detail guidance about creating namespace and users using `wskadmin`. The usage of `wskadmin` is talked here and there in docs, but not systematically. I hope to have a separate doc for `wskadmin` usage. It will help set up a on premise serverless platform using OpenWhisk. 

Currently, `wskadmin` depends on the property file `whisk.properties`. `whisk.properties` will be created when installing openwhisk by ansible. If Openwhisk is not installed by ansible, there is no `whisk.properties`, I will meet with following errors when I try to use it:
```
./wskadmin --help
property "DB_WHISK_AUTHS" not found in environment or property file
property "WHISK_LOGS_DIR" not found in environment or property file
property "DB_PASSWORD" not found in environment or property file
property "DB_PORT" not found in environment or property file
property "DB_PROTOCOL" not found in environment or property file
property "DB_WHISK_ACTIONS" not found in environment or property file
property "DB_HOST" not found in environment or property file
property "DB_WHISK_ACTIVATIONS" not found in environment or property file
property "DB_USERNAME" not found in environment or property file
```

**Comment by daisy-ycguo** [comment]
I think we need a design for the admin features in a private OpenWhisk, i.e. what functions we want to provide to wsk admins, either by command line or by RESTful API.

Currently, `wskadmin` talk with database directly. It can provide below functions:
- management for users and limitations
- query of db and system log

I'm hoping I can do following works as a wsk admin
- create/delete/block/list users
- manage namespaces
- manage limitations

( will continue to add )

**Comment by fmaschler** [comment]
I came across this issue using the docker-compose quick-start. I guess it's deprecated with the new tool `wskadmin-next`? Since neither of the two works I provided the properties in `$OPENWHISK_PROJECT_HOME/whisk.properties` and got the following error:
 > Failed to get namespace key ({"error":"not_found","reason":"no_db_file"})

Any suggestions how to fix that?

**Comment by chetanmeh** [comment]
`wskadmin-next` is not deprecated. You need to have required properties in `whisk.properties` file. Can you share output of `wskadmin -v user get guest`. That would provide more details. 

Also as you have created a custom whisk.properties file can you provide that also.

**Comment by fmaschler** [comment]
Of course `wskadmin-next` ist not deprecated, I referred to `wskadmin`.

The verbose flag did help to find the mistake in the requested URL. `whisk.properties` contained a wrong DB name... Thanks @chetanmeh for the quick help!

**Comment by ali-raza-tariq** [comment]
Hi guys, I am trying to use wskadmin utility and facing some issues. First, I am testing docker-compose deployment and just want test wskadmin control. I tried to use the default executable at `/openwhisk-src/bin/wskadmin` which gave me the same error as @daisy-ycguo

**Comment by chetanmeh** [comment]
@ali-raza-tariq When using `wskadmin-next` you need to create a conf file and pass it as argument. See [setup instructions][1] for details

[1]: https://github.com/apache/openwhisk/blob/master/tools/admin/README-NEXT.md#setup

**Comment by ali-raza-tariq** [comment]
thanks for the quick response @chetanmeh, I did get it working using the -v flag for debug. Although I was already passing the config file as written in the instruction, the values for database were different (`local_subjects` instead of `whisk_local_subjects` and the same with others). One question though, why am I not able to use the existing executable `wskadmin` directly ... the same way I can use `wsk` in `source/bin/` directory? I had to build this Gradle for `wskadmin-next`.

**Comment by rabbah** [comment]
You can. If you set the environment variables it should be fine with wskadmin also.

**Comment by ali-raza-tariq** [comment]
@rabbah can you elaborate how to setup these environment variables (which and how) or provide some resources for these. Also, why does it not setup the environment variables by default when you deploy OpenWhisk? is there any specific reason? 
All I know is, CLI uses `~/.wskprops` for properties which I already put in the environment path.

**Comment by rabbah** [comment]
if you want to propose a PR please do :)
