### ISSUE TITLE
Docs: mac group_vars folder not exist, document need update

### ISSUE THREAD

**Issue by steven-zhangyuan** [apache/openwhisk#3020]
In ./ansible/README.md:
These values may be changed by modifying the group_vars for your environment. For example, mac users will find the limits in this file ./environments/mac/group_vars/all:
......

Such file is already removed from project and this README.md need update. Maybe delete this part.

**Comment by rabbah** [comment]
Thanks for finding this - do you intend to submit a pr to correct the doc? We welcome contributions.
