### ISSUE TITLE
Unexpected "action developer error " - The action did not produce a valid response and exited unexpectedly.

### ISSUE THREAD

**Issue by andrewnet** [apache/openwhisk#3099]
We executed a performance run over the weekend. When when analyzed the result, we found 3 out of 332465 activation (all for the same Java action) have status `action developer error` and error `The action did not produce a valid response and exited unexpectedly.`

```
{
    "namespace": "Entity_discovery_qa",
    "name": "action_create_asset_yp-qa",
    "version": "0.0.41",
    "subject": "discopro@us.ibm.com",
    "activationId": "f8d0df5533d5462490df5533d5f62491",
    "start": 1512959668050,
    "end": 1512959676101,
    "duration": 8051,
    "response": {
        "status": "action developer error",
        "statusCode": 0,
        "success": false,
        "result": {
            "error": "The action did not produce a valid response and exited unexpectedly."
        }
    },
    "logs": [],
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 300000
            }
        },
        {
            "key": "path",
            "value": "Entity_discovery_qa/action_create_asset_yp-qa"
        },
        {
            "key": "kind",
            "value": "java"
        }
    ],
    "publish": false
}
```

These activation should have been successful as all of these 332465 activation go through the same route. The activation does not contain any logs of our Java action, so we suspect that our code never had a chance to execute.

**Comment by pheuberger** [comment]
I'm interested in this too. We executed a few dozen POST request agains our APIGW with lambda functions behind it and had 3 actions fail with the same reason. I'd really like to know what exactly went wrong in these instances, but the error message is not very helpful. 
The IBM console says the actions failed after only 1ms execution time.

**Comment by pheuberger** [comment]
Has this been addressed in the meantime @rabbah? Can we get a statement?

**Comment by rabbah** [comment]
@pheuberger the initial post is about a java action running in the ibm cloud and that's something for IBM to investigate. 

In terms of the openwhisk system, it currently does not retry certain failure (at most once) which isn't ideal. It should be at least once (matching aws lambda for example) and that's covered by https://github.com/apache/openwhisk/issues/2883.

**Comment by rads18** [comment]
Hello,

Did this discussion lead anywhere?  I too am interested to learn how can we handle "action fails catastrophically" in other words did not execute the function at all.

**Comment by rabbah** [comment]
@rads18 see 2883 - the system should shift to at least once instead of at most once to start.

**Comment by rads18** [comment]
Thanks @rabbah for replying to this old thread, i recently faced this for a sequence where the action failed with "whisk internal error". This is not a condition i can handle inside the action as it was not executed and it wont goto the next in sequence as it failed.. any ideas?
