### ISSUE TITLE
remove API to lists all entities in a namespace?

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk#3153]
The API currently supports a `GET` on `/namespaces/_` which returns all the entities in a namespace. This is used in `wsk list` for example to show actions, triggers, rules, and packages.

The view supporting this API call is redundant with other views and takes up space in the database for the convenience of replacing 4 calls with 1. This view is also reduced in the controller which makes it harder to stream the response directly from the db to the client. Clients on the other can make 4 calls if needed, and this would provide a more consistent experience for using skip, limit per entity type (and count once that's added).

Thoughts?

**Comment by starpit** [comment]
i think this is a good idea. all of the Read APIs should use streaming, never touching the controller's  scala heap. plus, the list api can easily be implemented client-side, possibly with a more attractive user experience: the UI can begin rendering as soon as any one of the four sub-requests completes.

**Comment by csantanapr** [comment]
better yet if you have a hand full of triggers, you don't need to fetch all your 1000 actions to get the trigger list.

**Comment by krook** [comment]
Would this change anything from an end-user perspective when calling `wsk list`? That is, with this REST API change, would there be an associated change to the CLIs so that the command returns the same thing or would the user now have to list actions, triggers, rules, and packages separately?

**Comment by rabbah** [comment]
`wsk list` can preserve the behavior today, this is an implementation detail, not a user facing change otherwise.

**Comment by csantanapr** [comment]
>better yet if you have a hand full of triggers, you don't need to fetch all your 1000 actions to get the trigger list.
ignore this, we already have this on /triggers, is all efficiencies on dealing with views.
