### ISSUE TITLE
Changing Kafka port on the local Ubuntu 16.0 openwhisk installation

### ISSUE THREAD

**Issue by spattewar** [apache/openwhisk#3169]
Hello Experts,

Thanks for all your time in helping me set up local openwhisk installation on ubuntu 16.0. The local installation is working fine and i was able to create actions and test them. Now there is a requirement to run a Kafka service that is interacting with ignite. 

My work is to create an action that writes a topic to the Kafka which is then analysed by ignite. But now we are facing a problem that the outside kafka service is using the same port as the internal kafka of openwhisk.
 
Can i change the port of the kafka that openwhisk internally uses or can i use the same kafka service to write to the ignite. The first approach is preferable.

Looking forward to your help.
Appreciate your time as always.
Thanks and Regards

**Comment by markusthoemmes** [comment]
The port of the internal kafka bus is configurable at https://github.com/apache/incubator-openwhisk/blob/master/ansible/group_vars/all#L69. All of our configuration should be relative to that setting so changing that (+ redeploying) should give you the desired effect.

**Comment by spattewar** [comment]
Thank you Markus for providing time and response.

Does redeploying means reinstalling openwhisk or just restarting the
Dockers? Which steps should I perform?

Appreciate your help.

Thanks and regards

**Comment by markusthoemmes** [comment]
Well you'll need to redeploy all components in relation to kafka, that is: Kafka, Zookeeper, Controller and Invoker.

If you're using `redo` that'll be: `redo kafka controller invoker`

**Comment by spattewar** [comment]
Great. Thank you. I will try it now.

How about the other scenario of using the internal Kafka as any other Kafka
service.? Do you recommend it?

Thanks and regards

**Comment by rabbah** [comment]
You can do that.
