### ISSUE TITLE
Gradle tests updating the runtime dependencies

### ISSUE THREAD

**Issue by houshengbo** [apache/openwhisk#3178]
When we run the tests by the command: ./gradlew tests:test, gradle will verify and update the dependencies. We should not do this, since tests would not make any sense, if they are able to modify our deployment.

https://github.com/apache/incubator-openwhisk/blob/master/tests/build.gradle#L41:
```
test.dependsOn([
    ':actionRuntimes:nodejs6Action:distDocker',
    ':actionRuntimes:actionProxy:distDocker',
    ':actionRuntimes:pythonAction:distDocker',
    ':actionRuntimes:python2Action:distDocker',
    ':actionRuntimes:javaAction:distDocker',
    ':actionRuntimes:swift3.1.1Action:distDocker',
    ':sdk:docker:distDocker',
    ':tests:dat:blackbox:badaction:distDocker',
    ':tests:dat:blackbox:badproxy:distDocker'
])
```

**Comment by markusthoemmes** [comment]
I take it that no tests in the main repo are relying on the existence of those images anymore? Note that the tests do not modify the deployment but rather rely on those images being around (the ActionContainerTests for instance). Can you make sure, that all of those tests have been moved out to different repos?

**Comment by rabbah** [comment]
https://github.com/apache/incubator-openwhisk/tree/master/tests/src/test/scala/actionContainers We still have all the tests in this repo and we run them.

**Comment by rabbah** [comment]
(Iirc all of the tests and related skeleton have been cloned and owned by the runtime repos 😕)
