### ISSUE TITLE
nginx deployment fails if mount source is wiped

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk#32]
Observed this failure a few times and here's how to reproduce it.

```
sudo rm -rf /tmp/nginx
ant clean build deploy
ant teardown
sudo rm -rf /tmp/nginx # note that if vm reboots or on a vagrant reload, this directory is gone
ant deploy # would normally work without a rebuild modulo the nginx config
```

Now /tmp/nginx is owned by root instead of the user (e.g., vagrant); nginx deployment appears to work and the failure is detected much later because the API host will not respond. The nginx container during deployment comes up and responds to heartbeat before it detects a bad configuration (and dies).

The nginx deployment needs to assert the configuration directory exists and fail if it does not. This will prevent mounting a non-existent directory and making it root-owned. Should also consider using an alternate directory instead of /tmp.

Lastly, the nginx build needs to fail if it cannot copy the nginx conf to the target directory (which will now happen since that directory is owned by root and the user has to write permission).

**Comment by rabbah** [comment]
I'm inclined to replace the mount based approach with a docker cp instead. The current approach is flaky.

**Comment by sjfink** [comment]
Note that if we move to docker cp, not just the build but also the B/G swap code must change.

**Comment by daisy-ycguo** [comment]
I think this issue should be high priority to fix. Because `ant build` and `ant deploy` all failed because of "Permission denied" on the current code base.

**Comment by rabbah** [comment]
If you sudo rm the directory, you can restore desired behavior.

**Comment by daisy-ycguo** [comment]
@rabbah Thanks. I removed directory tmp/nginx and tmp/consul, and then I can build and deploy successfully. I guess it might because these two directories were created with the old version of OpenWhisk.

**Comment by csantanapr** [comment]
@rabbah close? this outdated i.e. ant days

**Comment by rabbah** [comment]
i dont think the underlying issue is resolved however - should be easy to replay with `redo edge` i think.
