### ISSUE TITLE
Controller seed nodes should not be required when local bookkeeping is used

### ISSUE THREAD

**Issue by dubee** [apache/openwhisk#3205]
`controllerSeedNodes` should not be a required property as long as `controllerLocalBookkeeping` is enabled. When `controllerLocalBookkeeping` is enabled, `controllerSeedNodes` is never referenced.

From LoadBalancerService.scala:

Make seed nodes a required property:
```
def requiredProperties =
    kafkaHosts ++
      Map(controllerLocalBookkeeping -> null, controllerSeedNodes -> null)
```

Does not reference seed nodes when local bookkeeping is used:
```
private val loadBalancerData = {
    if (config.controllerLocalBookkeeping) {
      new LocalLoadBalancerData()
    } else {

      /** Specify how seed nodes are generated */
      val seedNodesProvider = new StaticSeedNodesProvider(config.controllerSeedNodes, actorSystem.name)
      Cluster(actorSystem).joinSeedNodes(seedNodesProvider.getSeedNodes())
      new DistributedLoadBalancerData()
    }
  }
```

**Comment by dubeejw** [comment]
Perhaps the above can be alleviated with the use of PureConfig.

**Comment by dubeejw** [comment]
As a temporary work around, it is possible to pass an empty string for the seed node property.

**Comment by rabbah** [comment]
I don't know if the above is still valid. Closing as stale.
