### ISSUE TITLE
Source files for images in docs folder

### ISSUE THREAD

**Issue by shazron** [apache/openwhisk#3208]
Since this is an open source project, ideally the images to create the diagrams and logos should be open sourced as well. 

Related #3207 - I wanted to create a PR to modify the image, but I didn't have the source file. 

Images: https://github.com/apache/incubator-openwhisk/tree/master/docs/images

**Comment by shazron** [comment]
Since source files might be missing, what is an acceptable source format if we recreate? I'm biased to Adobe formats (surprise) but here's what I suggest:
1. Logos/icons (PSD, EPS)
2. Diagrams -- not sure. I'm avoiding some free "text to diagram" tools like Mermaid for perhaps something graphical like:
a. [Dia](http://dia-installer.de/) - standalone cross platform app
b. [LibreOffice Draw](https://www.libreoffice.org/discover/draw/) - standalone cross platform app
c. [OpenOffice Draw](https://www.openoffice.org/product/draw.html) - standalone cross platform app
d. [Diagramo](http://diagramo.com/) -- needs a PHP server to run in the browser (buggy, can't save on Mac)

**Comment by rabbah** [comment]
+1 (e)

**Comment by csantanapr** [comment]
@shazron 
Which open source tools could we use to edit PSD/EPS? 
I’m +1 with draw.io

**Comment by shazron** [comment]
The only one I can think of is GIMP or Photopea (only the former is open source, the latter is free).

If we want the real deal, not sure if there are any We can get Apache to formally request from Adobe: https://www.techsoup.org/restrictions#adobe so all committers can get a copy

**Comment by csantanapr** [comment]
Let's use GIMP then for Logo

**Comment by csantanapr** [comment]
Also Photopea can be use to edit GIMP format (XCF)
