### ISSUE TITLE
akka thread pool tuning

### ISSUE THREAD

**Issue by starpit** [apache/openwhisk#3226]
two of akka's thread pools could use some tuning.

the first is the default pool used by our fork join scheduler. the akka fork join scheduler has a default setting of `throughput=5`, which means each thread/worker will process at most 5 events before yielding -- and thus risking a context switch.

the second is the io pool, which uses (by default) a pinned scheduler (i.e. threads pinned to processors); this pool handles incoming packets. it has a default size of 1, and its own default throughput of 5.

in the following experiments, i peg the pool size to 8, with a throughput of 200, and vary the throughput setting of the fork join scheduler. NOTE: the xput= rows in this table build on PR #3225 as their baseline. thus the xput=5 row is identical to the performance of PR #3225, as xput=5 is the default setting.

```
           p25   p50   p75    p90    p99     max
master     20ms  23ms  28ms   40ms   270ms  1.7s
xput=5     18ms  21ms  26ms   35ms   85ms   1.4s    (baseline #3225)
xput=200   20ms  23ms  28ms   39ms   74ms   407ms
xput=1000  18ms  21ms  25ms   33ms   64ms   277ms    <===
xput=2000  19ms  22ms  26ms   36ms  103ms   751ms
```

test protocol: wrk -t8 -c800 -d60s --latency
endpoint: blocking invokes of echo action
deployment: environments/local, local couchdb, 44-way with 48GB memory; 12 invokers
load driver: 16-way located in the same rack

**Comment by starpit** [comment]
to tune the fork join scheduler, add this to core/controller/src/main/resources/application.conf

```
  actor {
     default-dispatcher {
        throughput=1000
     }
  }
```

**Comment by starpit** [comment]
to tune the io pool, add this to the same application.conf file:

```
akka {
  io {
     pinned-dispatcher {
        throughput=1000
        thread-pool-executor {
           core-pool-size = 8
        }
     }
     tcp {
        nr-of-selectors = 8
        batch-accept-limit = 1000
        direct-buffer-size = 1024 KiB
     }
  }
}

**Comment by bwmcadams** [comment]
I agree, in principle, that the tuning is a good thing. But I'm not so sure about the proposed defaults/baseline. The test machine for which these parameters were determined is described as "44-way with 48GB memory". These numbers definitely look good for that setup, but will they meet the needs of all users? 

Is there an assumption, with OpenWhisk, of what a "default" user machine should look like? There should likely, with the PR, be some documentation addition on user tuning as well.

**Comment by dubee** [comment]
@starpit ^^
