### ISSUE TITLE
Controller should not return a payload for created and deleted entities

### ISSUE THREAD

**Issue by dubee** [apache/openwhisk#3274]
When creating entities, the controller should respond with just a status code, 200 OK or 201 CREATED, omitting the created entity from the response.

Similarly, when deleting entities a status code, 200 OK or 202 ACCEPTED, should be returned without including the deleted entity in the response.

**Comment by nitikagarw** [comment]
Hi @dubee, @rabbah,
I am a beginner looking to contribute to OSS. Can I pick this issue?

**Comment by style95** [comment]
@nitikagarw 
Thank you for your help and welcome to the community :)

**Comment by rabbah** [comment]
Welcome to the community @nitikagarw - when you complete your first PR send me a message on Slack and I'll send you an openwhisk coffee/tea mug or hoodie.

**Comment by nitikagarw** [comment]
Hi @style95 @rabbah, Thank you for giving me the chance to contribute to OSS. 

I spent some time familiarizing myself with the code and have created a Draft PR to know if I'm moving in the right direction. 

I have two questions:

- As we have the same [function](https://github.com/apache/openwhisk/pull/4968/files#diff-ccbf57a3feb6b78f664e3ee8dc4d86cdR307) for PUT and POST, Do we need to make this change for both methods or only for the POST APIs?

- What are your views about changing the HTTP Status of DELETE API to 204 from 200?

**Comment by style95** [comment]
closing as done.
Thanks, @nitikagarw!
