### ISSUE TITLE
Integrate kube deployment?

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk#3346]
Our openwhisk-kube repo https://github.com/apache/incubator-openwhisk-deploy-kube currently is where our docs and deployment for kube are located.

But as kube is becoming increasingly the way our users want to deploy and use openwhisk, we should consider making it easier by integrating the kube deployment here instead. This will also better signal our commitment to kube which is something a lot of the other faas platforms already do. 

I’m opening this issue to start the discussion and I’ll follow this up with a note to the Apache dev list.

**Comment by csantanapr** [comment]
+1
I dont see hard blockers to be Travis/Jenkins integrated

**Comment by ddragosd** [comment]
👍  any thoughts on Apache Mesos ?

**Comment by dgrove-oss** [comment]
my 2 cents.  Once a deployment has stabilized (isn't being rapidly revved & has basic Travis CI testing), then it seems to me to make sense to pull it back into the core repo to make it easier to maintain.

**Comment by mrutkows** [comment]
FWIW, there should be some community driven criteria on what constitutes a deployment being "ready" for inclusion. That is, we should not be encouraging inclusion of deployments that could not be built on every PR with an acceptable level of BVT.  Basically, what is the standard where the dev. community is not perpetually claiming depl. X is broken...  In addition, we have to make sure anything in main repo. is ready for the apache release process being developed.  Clearly, Kube and Mesos are on that path; what is the consistent test/criteria we apply to any other that comes along?

**Comment by jthomas** [comment]
As a short term improvement, should we improve the docs to list all the deployment options and point to the external repos?

**Comment by Liu-HongYe** [comment]
How is it going?

**Comment by dgrove-oss** [comment]
Short term, we'd like to progress #3498 to at least document the deployment options that aren't included in the main repository.

I think it would be great if we could get https://github.com/apache/incubator-openwhisk-deploy-kube/issues/63 (deploy via a Helm chart) done before merging back to the main repo.  The current kubernetes deployment process is fairly well documented, but is still more manual that one would like.

**Comment by rabbah** [comment]
Consensus was to keep kube separate in its own repo.
