### ISSUE TITLE
WskBasicTests failed due to a caught exception during the log fetching process

### ISSUE THREAD

**Issue by eweiter** [apache/openwhisk#3370]
While running the test 
`Wsk Action REST should create, and invoke an action using a parameter file` from the WskBasicTests Suite, that test encountered an error due to an uncaught exception while fetching the logs. 

The output of the test showed the following:
```
system.basic.WskBasicTests > Wsk Action REST should create, and invoke an action using a parameter file STANDARD_OUT
    check failed for activation 8f51f83dc427469f91f83dc427269ff0: {"duration":11,"name":"paramFileAction","subject":"lime@us.ibm.com","activationId":"8f51f83dc427469f91f83dc427269ff0","publish":false,"annotations":[{"key":"path","value":"lime@us.ibm.com/paramFileAction"},{"key":"waitTime","value":35},{"key":"kind","value":"nodejs:6"},{"key":"limits","value":{"timeout":60000,"memory":256,"logs":10}},{"key":"initTime","value":11}],"version":"0.0.1","response":{"result":{"error":"Internal system error: system not ready, status: running"},"success":false,"status":"action developer error"},"end":1519758166952,"logs":["2018-02-27T19:02:04.031894666Z stderr: [wrapEndpoint] exception caught Cannot read property 'run' of undefined","2018-02-27T19:02:48.969Z       stderr: There was an issue while collecting your logs. Data might be missing."],"start":1519758166941,"namespace":"lime@us.ibm.com"}
    Exception occurred during test execution: org.scalatest.exceptions.TestFailedException: Some({"error":"Internal system error: system not ready, status: running"}) was not equal to Some({"payload":"test"})
```

Upon inspecting Kibana for the failure, I found: 
```
February 27th 2018, 14:02:49.917    [2018-02-27T19:02:48.981Z] [INFO] [#tid_33145265] [InvokerReactive] recorded activation

**February 27th 2018, 14:02:49.916    [2018-02-27T19:02:48.969Z] [WARN] [#tid_33145265] [ContainerProxy] reading logs failed: whisk.core.containerpool.logging.LogCollectingException: Failed to read logs**

February 27th 2018, 14:02:49.916    [2018-02-27T19:02:48.969Z] [INFO] [#tid_33145265] [InvokerReactive] recording the activation result to the data store
```

You can see in the stderr for the test failure `stderr: [wrapEndpoint] exception caught Cannot read property 'run' of undefined` .  I tried searching the code for where the above errors about "failed to read logs" were but I could not find any references to it. 

This issue may have two solutions that need to be implemented. 
1) Increase the logging around this failure, to be more explicit about why the reading of the logs failed
2) Find out where that uncaught exception was thrown and put error checking in place around it.

**Comment by markusthoemmes** [comment]
Thanks for investigating so deeply.

Note though: This is not "an uncaught exception during the log fetching process". The log fetching was fine, it just didn't finish properly (probaby due to missing sentinels).

The RCA of this issue will be somewhere in the action container which was not startet properly hence the uncaught exception *in the container* (not in the invoker).

**Comment by eweiter** [comment]
Updated title to no longer reflect an uncaught exception.  Rereading the error message I see now it says "Caught exception ..." and it threw a specific error.

**Comment by mdeuser** [comment]
@markusthoemmes - do you agree that there are 2 issues at play - (1) more logging failure details and (2) proper handling of `undefined` value ?

**Comment by markusthoemmes** [comment]
Yep. Hint for 1: It will be a matter of inserting a logline at `DockerContainer.scala:262` for whomever wanting to pick that up.
