### ISSUE TITLE
Couchbase support

### ISSUE THREAD

**Issue by devbv** [apache/openwhisk#3372]
Hi all, I found that I wrote spi module of artifact store supporting Couchbase in last year but not did PR.
It's based on pretty old revision so It may take a few time to rebase and test.
Anyway, would it be helpful if I wrap it up and PR? Give me a opinion.

**Comment by rabbah** [comment]
I can imagine how we can offer a few plugins for the artifact store. The concern as with any functionality is making sure it doesn’t rot. If there’s a way to automate the testing then we should include it. There’s on going work for Mongo as well and so we can have more than one.

**Comment by rabbah** [comment]
Contributions are welcomed.
