### ISSUE TITLE
The security of running arbitrary code in docker containers

### ISSUE THREAD

**Issue by Tor1mo** [apache/openwhisk#3373]
I couldn't really find any documentation on how the security regarding docker containers is addressed. As far as I was aware, the consensus was that the isolation provided by them ought not to be considered as secure. Does openwhisk take any measures to address that; or maybe there are specific reasons why this is not a concern in this context?

**Comment by rabbah** [comment]
Container security is handled from outside - access to resources and network isolation are of course necessary. There was a push to integrate AppArmor into the openwhisk code base (I’ll link for posterity) but the work wasn’t completed.
