### ISSUE TITLE
add reference log forwarder and monitoring dashboard

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk#3390]
The openwhisk deployment today doesn't provide a reference for standing up say an Elastic stack, or monitoring with Kibana. We can provide a reference but optional deployment to forward logs to Elastic and a sample Kibana dashboard.

**Comment by dgrove-oss** [comment]
#3378 is loosely related; proposing a refactor to make it easier to share code related to log augmentation for forwarding.
