### ISSUE TITLE
Consolidate action annotation constants

### ISSUE THREAD

**Issue by mdeuser** [apache/openwhisk#3401]
Currently, the defined action annotation names are not centrally defined.  Consolidate them as constants into a single location and change the existing code to use those constants.

Example annotations
- web-export
- final
- raw-http
- web-custom-options
- require-whisk-auth

**Comment by kiran002** [comment]
@mdeuser I would be interested in taking this up. 

My task would be to move the actions in [here](https://github.com/apache/incubator-openwhisk/blob/fb0bab64de6634725b409a63ffbb90fee295e8c1/common/scala/src/main/scala/org/apache/openwhisk/core/entity/WhiskAction.scala#L312-L317), to another object class and reference them in the core and in tests. Is this correct?

**Comment by rabbah** [comment]
Awesome @kiran002 - welcome to the community.

**Comment by mdeuser** [comment]
@kiran002 - thanks for picking this up :heart:  i defer to @rabbah, but in addition to what you have suggested, you may want to consider providing the list of these annotations via the openwhisk endpoint.  just like what is done with the set of system limits and runtime..

**Comment by kiran002** [comment]
@mdeuser can you please point me to where the system limits and runtime endpoints are defined?

**Comment by mdeuser** [comment]
@kiran002 - i'm not sure exactly were that code is.  it's the output from the `curl https://openwhiskhost`  this might be a good starting place https://github.com/apache/incubator-openwhisk/blob/d22ef30fe613d60d84a5310a6b89cdbe2c495995/core/controller/src/main/scala/org/apache/openwhisk/core/controller/Controller.scala#L190

**Comment by kiran002** [comment]
cool thanks will look into it! :)

**Comment by kiran002** [comment]
@rabbah 
Before i go all out and implement these changes, I wanted to get some feedback from you guys, So my idea is to have an annotations object
```
object Annotations {
  val FinalParamsAnnotationName = "final"
  val WebActionAnnotationName = "web-export"
  val WebCustomOptionsAnnotationName = "web-custom-options"
  val RawHttpAnnotationName = "raw-http"
  val RequireWhiskAuthAnnotation = "require-whisk-auth"
  val ProvideApiKeyAnnotationName = "provide-api-key"
}
```
and i intend to change all instances of 

```
 annotations = Map(WhiskAction.provideApiKeyAnnotationName -> JsBoolean(true)))
```
to
```
 annotations = Map(Annotations.ProvideApiKeyAnnotationName -> JsBoolean(true)))
```

**Comment by rabbah** [comment]
👍 sounds like a good plan to me.

**Comment by rabbah** [comment]
Don’t think you need to toJson method - not sure what your intent is there.

**Comment by kiran002** [comment]
toJson method was for ` providing the list of these annotations via the openwhisk endpoint`, do you think its necessary?

**Comment by rabbah** [comment]
Interesting thought. That hadn't occurred to me. Do you know how clients might use this?
