### ISSUE TITLE
Gradle Build failing 

### ISSUE THREAD

**Issue by aganesh-pk** [apache/openwhisk#3429]
I'm trying to setup openwhisk on ubuntu. 
Getting build failed error when building. Any idea?

vagrant@vagrant-ubuntu-trusty-64:~/openwhisk$ sudo ./gradlew distDocker

> Task :common:scala:tagImage
Mon Mar 12 20:04:41 UTC 2018: Executing 'docker tag scala whisk/scala:latest'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:scala:compileScala'.
> Failed to run Gradle Worker Daemon
   > Process 'Gradle Worker Daemon 1' finished with non-zero exit value 137

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 0s
19 actionable tasks: 19 executed

FAILURE: Build failed with an exception.

* What went wrong:
Process 'Gradle Worker Daemon 1' finished with non-zero exit value 137

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by csantanapr** [comment]
Try running the command directly like the gradle task is doing 

sudo docker tag scala whisk/scala:latest

Is docker setup correctly?
Try to see if there are errors doing : 
docker ps
docker images
docker info

Why are you using sudo?

**Comment by richenyadav001** [comment]
I was also stuck in same issue.
Thanks @csantanapr  for running command directly
There is a sudo permission issue.
[Manage Docker as a non-root user](https://docs.docker.com/install/linux/linux-postinstall/)

**Comment by rabbah** [comment]
Thanks @richenyadav001 for the tip.
