### ISSUE TITLE
Validate whether 'runtimes.manifest' is still needed by tests

### ISSUE THREAD

**Issue by jonpspri** [apache/openwhisk#3493]
The 'runtimes.manifest' variable in 'whisk.properties' and, therefore, 'whisk.properties.j2' may no longer be needed.  If it is still needed, it is needed by tests run for 'incubator-openwhisk', and such tests should be rewritten to read from an agreed configuration file directly, instead.

As that is resolved, several layers of indirection between runtimes specification and resolution could be resolved.

It should also be investigated whether the runtimes configuration for invoker (and other components) should be provided as a JSON string or as a file containing configuration.  The handling of the configuration in ansible is a major consideration for this conversation.  @csantanapr is a major user of YAML runtimes specification in creating/testing the turntimes for example and his requirements for flexibility in deployment must be addressed.

See PR #3412 for additional discussion.

**Comment by rabbah** [comment]
It is.
