### ISSUE TITLE
API functionality not working 

### ISSUE THREAD

**Issue by yadavvipinsonu** [apache/openwhisk#3557]
Hi  , 
We are trying to install and use openwhisk in corporate environment.
Cent-OS is the preferred operating system that we want to use.

Is there any documentation , webpages that have all the steps in detail for the installation process.
It seems api functions (api list ,create) are not working when we tried installation through below links

https://github.com/apache/incubator-openwhisk
https://github.com/apache/incubator-openwhisk-devtools
https://blog.krugazor.eu/2017/12/openwhisk-centos-installation-part-2/

**Comment by rabbah** [comment]
There isn't anything specific to centos. We welcome contributions on new installations/documentation.
