### ISSUE TITLE
Run full set of tests using Travis stages/jobs

### ISSUE THREAD

**Issue by csantanapr** [apache/openwhisk#3572]
Today we exclude a serie of test cases because running in a single travis job takes longer than the max timeout (~50 minutes)
Today we exclude tests like this
https://github.com/apache/incubator-openwhisk/blob/master/tests/build.gradle#L23-L31
```
task testLean(type: Test) {
    exclude '**/*Swift*'
    exclude '**/*Python*'
    exclude '**/*Java*'
    exclude '**/*ThrottleTests*'
    exclude '**/MaxActionDurationTests*'
    exclude '**/*ApiGwRestBasicTests*'
    exclude '**/*WskCli*'
}
```
We could create additional test suite to see if we can fit them in another job that runs in parallel.

Today we already run 2 jobs in parallel

```

```
cc @chetanmeh @mrutkows

**Comment by chetanmeh** [comment]
I did some analysis of the time taken in a typical travis build. Detailed break up can be seen [here][1]

For purpose of this break up a custom [branch][2] was created where the `build.sh` was broken into sub scripts 

1. scan - scalaFmt, scanCode
2. couch-setup
3. compile - common and core
4. distDocker
5. runDocker
6. runTests
7. Collect logs

This was done as travis report explicit time per script entry in `script` block. Based on reports from [gradle][3] following summary can be made

### Travis Time Breakup

| Phase | Time (mins)|
|-------|-------------|
| Base| 12|
| Docker work| 6|
| Code scan| 2|
| Test db only|11|
| Test require docker|12|

Further breakup
* Base ~12 mins
    * Install 62 sec
    * Couch 54 sec
    * Compile Core 145 sec (2.4 mins)
    * Compile Tests 386 sec (6.5 mins)
    * logs 50 sec
* Docker ~ 6 mins
    * Dist Docker 170 secs
    * Run all docker 180 secs
* Tests ~ 33 mins
    * Test just needing DB - 670 sec (11.15 min)
    * Test needing full docker setup (excluding previous) - 733 sec (12.2 min)

### Segregating Tests

In genral convention so far was to have tests under `system` package to depend on whole setup and tests outside just relying on database. However as per [reports][1] it can be seen that some tests in following package do depend on other parts

* whisk.core.controller.test
    * ControllerApiTests should ensure controller returns info
* whisk.core.database.test
    * CacheConcurrencyTests
* whisk.core.admin
    * WskAdminTests Wsk Admin CLI should verify guest account installed correctly

Probably we can move them to system package

Packages requiring complete setup

* apigw.healthtests
* services
* system.basic
* system.rest
* whisk.core.limits
* whisk.core.cli.test
* whisk.core.apigw.actions.test

[1]: https://docs.google.com/spreadsheets/d/e/2PACX-1vSujt396CMPJhvnsuDA1pHvITKrXFMzD5i1OqYwqXAxa4aif1gWakXib0rKnST351FhPqmo6VTgShWI/pubhtml#
[2]: https://github.com/apache/incubator-openwhisk/compare/master...chetanmeh:test-db-only
[3]: https://scans.gradle.com/s/o2fnhjckyaajw/performance/execution

**Comment by rabbah** [comment]
Great breakdown - thanks @chetanmeh!
I agree about moving the three suites mentioned - with the mocking of the database with an in memory store now possible, I'd like to eventually remove the couchdb dependence from the unit tests as well.

**Comment by chetanmeh** [comment]
### Test Segregation Methods

#### A - Package based filters

Currently we prepare a lean test set why providing a filter consisting of globs for tests to be excluded

```
    '**/*Swift*',
    '**/*Python*',
    '**/*Java*',
    '**/*ThrottleTests*',
    '**/MaxActionDurationTests*',
    '**/*ApiGwRestBasicTests*',
    '**/*WskCli*'
```

For splitting the test suite into multiple stages we would need to create include sets of various packages we need to include in given setup. One possible approach can be to have 2 sets

1. Tests requiring DB
2. Tests requiring full setup

It would need to be ensured that both set cover all the tests present

#### B - Use ScalaTest tags

ScalaTest supports [tagging the tests][1]. 

The tags can be specified on per test basis

```scala
object DbTest extends Tag("com.mycompany.tags.DbTest")

it must "subtract correctly" taggedAs(Slow, DbTest) in {
    val diff = 4 - 1
    assert(diff === 3)
  }
```

Or can be specified [on whole suite][5] by defining a custom annotation. 

```scala
@org.scalatest.TagAnnotation
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE})
public @interface RequiresDb {}

@tags.RequiresDb
class MyBusinessTest extends WordSpec with Matchers {
  "loads business objects from db" in { ... }
```

These tags would then need to be used with Gradle. However default test runner in Gradle does not supports tags. For that we need to use [gradle scalatest][3] plugin. This [blog entry][4] provides one example of how to configure it

So we need to decide which approach to take going forward

[1]: http://www.scalatest.org/user_guide/tagging_your_tests
[2]: http://www.michaelpollmeier.com/2015/08/26/tag-scalatest-
[3]: https://github.com/maiflai/gradle-scalatest
[4]: http://trickbooter.com/post/2016-11-17-gradle-scalatest/
[5]: http://doc.scalatest.org/3.0.0/index.html#org.scalatest.Tag

**Comment by markusthoemmes** [comment]
Great, thank you @chetanmeh.

One thing to keep in mind when moving tests around: The `system` package should only contain tests, that depend on the *OpenWhisk system*. That is, ideally they only talk through the OW API and do not know any of the innerts (like the database)

**Comment by csantanapr** [comment]
This a great analysis @chetanmeh 

We could also have the runtime unit tests in a seperate Travis job and this job doesn’t need deployed OW

**Comment by rabbah** [comment]
oooh and move all the repos back together? 😅🏃🏻‍♂️

**Comment by mcdan** [comment]
I'm also seeing some interesting stuff with running all the tests on our jenkins infrastructure. Seems like the "leanTests" alone use > 4gb of memory over their run and drive the machine into a memory starvation.

https://snapshot.raintank.io/dashboard/snapshot/uTSpjXnFAntDC2zG1Kh4xOXFE7pEKaUQ?orgId=2

**Comment by rabbah** [comment]
With ScalaTest tags is there a way to list all tests that would run for a given tag (ie a dry run)?

**Comment by chetanmeh** [comment]
@rabbah Did not found any such feature documented. So posted a query on scala-test dl https://groups.google.com/forum/#!topic/scalatest-users/3kxgke3tIr8
