### ISSUE TITLE
Unnecessary "becomes" pollutes global python install

### ISSUE THREAD

**Issue by mcdan** [apache/openwhisk#3608]
## Environment details:

* build system

## Steps to reproduce the issue:

1.   Try and use the ansible scripts in a build env that doesn't do things globally
2.   The ansible install for pip affects the global packages on the system

## Provide the expected results and outputs:

The prereqs steps install versions of specific python packages via sudo this isn't necessary.

## Provide the actual results and outputs:

The packages should be installed locally just to the user running the build. That way it pollutes the environment a bit less.

## Additional information you deem important:
* This doesn't break travis and makes it easier for people to use the build in a local jenkins.

**Comment by rabbah** [comment]
We've made many of these configurable already.
