### ISSUE TITLE
post.lua fails in wrk tests

### ISSUE THREAD

**Issue by tysonnorris** [apache/openwhisk#3667]
## Environment details:

* local deployment (trying to verify in travis by enabling log collection for perf tests)

## Steps to reproduce the issue:

1.   run wrk perf tests: `./performance/wrk_tests/throughput.sh "https://192.168.99.100:10001" "$(cat ansible/files/auth.guest)" ./performance/preparation/actions/async.js 100 5 10s`
2.   notice errors from wrk: `post.lua: post.lua:1: unexpected symbol`
3.   

(note: the error is output to stderr)

I think this is due to: https://github.com/apache/incubator-openwhisk/commit/3c12c2f3b8a36d3f9800251ec35aae687916f3f6#diff-96ee228ccd3e09e5e9519e18480b7719L1

locally, it works fine if I remove the extra linebreak

## Provide the expected results and outputs:

no errors

I will verify in an updated PR with log collection enabled, and create a separate PR for this fix, it is is seen there.

**Comment by tysonnorris** [comment]
This does not seem to happen with travis, but happens consistently locally (macos) and reverting this extra linebreak fixes it locally:
https://github.com/apache/incubator-openwhisk/commit/3c12c2f3b8a36d3f9800251ec35aae687916f3f6#diff-96ee228ccd3e09e5e9519e18480b7719L1

Is anyone able to confirm proper running of wrk tests on macos?

**Comment by rabbah** [comment]
Closing as stale.
