### ISSUE TITLE
Update NodeJS runtime reference

### ISSUE THREAD

**Issue by eweiter** [apache/openwhisk#3675]
The NodeJS runtime was recently updated to bring in the latest versions for NodeJS6 and NodeJS8.
NodeJS 6 went from `6.14.1` to `6.14.2`
NodeJS 8 went from `8.11.1` to `8.11.2`

We need to update the reference to this runtime so it picks up the latest NodeJS runtime version.

**Comment by rabbah** [comment]
Wrong repo and we have node 12 support now anyway.
