### ISSUE TITLE
Change current working dir to location of exec

### ISSUE THREAD

**Issue by duglin** [apache/openwhisk#3690]
I have a function that I deploy via a Docker container (ie. I do: `wsk action update mydemo exec.zip --native`). Inside of that zip I have some files that my function needs to access at runtime.  Those files appear at the root of the location of where the zip file is extracted/expanded. However, when the function's code (`exec`) is run, the current working dir is someplace else in the filesystem. In order for my app to locate its needed files I need to get the program's `args[0]` and strip off the `/exec` at the end to find where I should look for the files.  While obviously do-able, this isn't the greatest UX. It would be nicer if the current working dir was the root of where the zip file was expanded. Then the function author doesn't need to jump through hoops to find the data from their zip file.

**Comment by rabbah** [comment]
This belongs in the respective runtime and should already be done.
