### ISSUE TITLE
Issue occured when TASK [compile docker images using gradle]

### ISSUE THREAD

**Issue by wangaoone** [apache/openwhisk#3754]
## Environment details:

vagrant environment.

## Steps to reproduce the issue:

1. Task failed with
an exception. ----------- * Where: Script
'/vagrant/openwhisk/gradle/docker.gradle' line: 96  * What went wrong: Execution
failed for task ':core:invoker:distDocker'. > Mon Jun 11 03:16:56 UTC 2018:
Command 'docker --host 10.1.4.21:4243 build -t invoker
/vagrant/openwhisk/core/invoker' failed with exitCode 1  * Try: Run with
--stacktrace option to get the stack trace. Run with --info or --debug option to
get more log output.

2. Task failed with an exception. ----------- * Where: Script
'/vagrant/openwhisk/gradle/docker.gradle' line: 96  * What went wrong: Execution
failed for task ':core:invoker:tagImage'. > Mon Jun 11 03:16:56 UTC 2018:
Command 'docker --host 10.1.4.21:4243 tag invoker
10.1.4.21:5000/whisk/invoker:latest' failed with exitCode 1  * Try: Run with
--stacktrace option to get the stack trace. Run with --info or --debug option to
get more log output。

## Provide the expected results and outputs:
The process of compiling docker should be completed

## Provide the actual results and outputs:

```
fatal: [ansible]: FAILED! => {"changed": true, "cmd": "./gradlew distDocker -PdockerHost=10.1.4.21:4243 -PdockerRegistry=10.1.4.21:5000", "delta": "0:12:59.728541", "end": "2018-06-11 03:16:57.172308", "msg": "non-zero return code", "rc": 1, "start": "2018-06-11 03:03:57.443767", "stderr": "The command '/bin/sh -c wget --no-verbose https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/bin/kubectl' returned a non-zero code: 1\nThe command '/bin/sh -c wget --no-verbose https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/bin/kubectl' returned a non-zero code: 1\nThe command '/bin/sh -c wget --no-verbose https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/bin/kubectl' returned a non-zero code: 1\nError response from daemon: No such image: invoker:latest\nError response from daemon: No such image: invoker:latest\nError response from daemon: No such image: invoker:latest\n\nFAILURE: Build completed with 2 failures.\n\n1: Task failed with an exception.\n-----------\n* Where:\nScript '/vagrant/openwhisk/gradle/docker.gradle' line: 96\n\n* What went wrong:\nExecution failed for task ':core:invoker:distDocker'.\n> Mon Jun 11 03:16:56 UTC 2018: Command 'docker --host 10.1.4.21:4243 build -t invoker /vagrant/openwhisk/core/invoker' failed with exitCode 1\n\n* Try:\nRun with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by rabbah** [comment]
closing as stale.
