### ISSUE TITLE
routemgmt.yml playbook will fail silently if the wsk binary is missing

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk#3759]
If you manage to run the playbook (for example with mode=clean) with a missing `wsk` binary the playbook succeeds even though the script failed. This is because it swallows the error incorrectly.

line 39 suppresses the failure:
https://github.com/apache/incubator-openwhisk/blob/cd7196a8e16aef6e848add239f6dec83c208e5f7/ansible/roles/routemgmt/files/uninstallRouteMgmt.sh#L39-L41

**Comment by rabbah** [comment]
@mdeuser there's a problem with the dependencies in this playbook.

the routemgmt playbook runs last; when deploying this is ok since it will download `wsk` and install the package.

but if you teardown the system, this playbook cannot uninstall the package since the deployment is down at that point.

the playbook fails silently because a failed status code from `wsk` in the uninstall script is accepted.

**Comment by mdeuser** [comment]
you are correct.  the `clean` task depends on a live backend.  i like the idea of pulling it out of openwhisk.yml and explicitly calling it in the correct order.  i prefer to keep it out of the apigateway.yml playbook to keep these concerns separate.

**Comment by rabbah** [comment]
OK let me try this:

```
openwhisk 
download cli
routemgmt
```

to teardown

```
routemgmt
remove cli
openwhisk
```

**Comment by rabbah** [comment]
@mdeuser there is a postdeploy playbook - it could also go in there; that playbook installs the various packages (aka catalog).

**Comment by rabbah** [comment]
@mdeuser why not put it in the api gateway playbook? Logically it won't work without it.

**Comment by rabbah** [comment]
I did improve this some time ago.
