### ISSUE TITLE
Compute stable id for controller

### ISSUE THREAD

**Issue by chetanmeh** [apache/openwhisk#3858]
Currently controller uses passed name parameter for controllerId which in turn is used to create kafka topics. If the name is based on say ip then the topic names would not be stable.

To support stable id controller should use zookeeper based logic as being used in Invoker #2916

**Comment by chetanmeh** [comment]
@tysonnorris mentioned [here][1]

> invoker suffers the same (1 topic per ip, when id is based on ip)

One possible approach would be to support expiring the mappings via some external agent and then have id logic to pickup first unused from the sequence. Recently in Apache Jackrabbit Oak we faced [similar issue][2] and @mreutegg implemented a greedy logic to acquire clusterId.

As for expiry - For Mesos we can have a service which listens to task status event and if it finds an invoker getting terminated then it can remove the corresponding entry from the `/invokers/idAssignment/mapping` path in zookeeper. Thus later once new invoker comes up it can claim that id.

[1]: https://github.com/apache/incubator-openwhisk/pull/3507#issuecomment-403519143
[2]: https://issues.apache.org/jira/browse/OAK-7316

**Comment by chetanmeh** [comment]
Adding further ... below is a possible approach to use to get a stable id for a cluster consisting of "N" entities. Objective here is to have a sequential id with id getting reused in case the backing entity stops 

### A - Check id validity on startup

Assume ids are stored under path
```
/invokers/idAssignment/mapping
+ 1 - u1 //Some unique id
+ 2 - u2 //another unique id
```

At startup `IdAllocator` does following steps

1. List the entries under `/invokers/idAssignment/mapping`
2. For each entry get its unique id. The unique id can be
    - Mesos - [MESOS_TASK_ID][1] (also see [docs here][2])
    - k8s - [Pod id][3]
3. Check if the container for given id is still in running state. This logic can be part of an `IdStalenessChecker` SPI
    - Mesos - via [task api][4]
    - k8s - To be figured out
4. If not found in running state then make a reservation by setting your own id against the given entry or add a new entry

### B - Use TTL Ids

Use Curator [Persistent TTL Nodes][5] recipe to add a node with ttl. 

Benefit of "A" is that it would not add any load to zookeeper or etcd. While "B" is simpler to implement

[1]: https://mesosphere.github.io/marathon/docs/task-environment-vars.html#task-metadata
[3]: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables
[2]: http://mesos.apache.org/api/latest/java/org/apache/mesos/Protos.TaskID.html
[4]: http://mesos.apache.org/documentation/latest/endpoints/master/tasks/
[5]: https://curator.apache.org/curator-recipes/persistent-ttl-node.html

**Comment by chetanmeh** [comment]
@tysonnorris  @dgrove-oss Thoughts on above proposal?

**Comment by tysonnorris** [comment]
I'm not sure about checking the container states in various ways (I guess it wouldn't work with the pure-docker deployment also?). 

How about using akka clustering for id mapping resolution?
1. startup, join akka cluster
2. once cluster is stable, retrieve id mapping
3. any mapping whose cluster id is not active (in cluster members), can be replaced with a new member (who does not already appear in the current id mapping)
4. periodically: refresh the mapping; any mapping whose cluster id is not active, should emit a warning (there are now, or will be, abandoned topics); eventually(manually?) delete the stale mapping and stale topics(?);

**Comment by chetanmeh** [comment]
@markusthoemmes From what In understand even Invokers currently not have very stable ids. So there are two parts to problem

### Controller Stable Id

Here requirement is that current approach may lead to orphan topics in Kafka if controller restarts and chooses a new id for every run. So here we either go for stable id or have a way in Kafka to expire topics which do not see some activity after some time

### Invoker Stable Id

Currently Invokers make use of `--name` parameter to be provided a unique name which is then used to find a mapping id from zookeeper. The problem (at least for Mesos) is that there is no stable unique name parameter value to use. One can use the host ip but then it would vary if the next restart leads to  container being placed on different host.

Looking at [kube][1] setup it looks like it is using [StatefulSet][2] to keep stable id across restarts. So for Mesos we can also use similar [Persistent Volume][3] 

However I am not sure if using stateful feature of container runtime should be the way to go as it would cause issue in case that node gives a problem or goes offline. In such a case invoker would be started on a new node and that would cause the topic to become orphan leaving activations present in  it unprocessed.

Hence the search for newer approach

[1]: https://github.com/apache/incubator-openwhisk-deploy-kube/blob/489ce8e90abf3bc411f8dd7087d42916c8a004be/helm/openwhisk/templates/invoker.yaml#L99
[2]: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
[3]: https://mesosphere.github.io/marathon/docs/persistent-volumes.html

**Comment by chetanmeh** [comment]
> How about using akka clustering for id mapping resolution?

@tysonnorris Missed that we can also use that. Yes that should also provide a simpler solution. We anyway rely on akka networking in controller so possibly can use that for invokers also.

**Comment by chetanmeh** [comment]
> So for the Controller, that shouldn't be much of an issue if we just garbage collect stale topics after, say, 24 hours of inactivity. Inactivity means: No consumers connected for that time. There might even be a way to configure Kafka to do that.

Did not found any out of the box Kafka feature to do that. So we would need to have some tooling to do the purge. May be we add that support in `wskadmin-next`

> For the overflow case of course, this is different. We should strive for the overflow queue there though vs. fixing the ID mappings.

My concern was more for overflow case. As there would always be case where OW capacity may be limited and in case of burst of events the queue size may grow large. So yes probably overflow queue concept should be implemented

> Another angle to this is: Instead of trying to fix invoker id assignments (which are kinda important to be increments of 1) should we try to find an algorithm, that doesn't rely on numbered invokers at all?

Well thinking about this it appears what we are doing is similar to what Kafka would be doing internally via partitions support. If you have a single queue and multiple invokers form a consumer group then internally Kafka would parition the queue and allocate the partitions to individual invokers. So it would internally take care of sequential numbering of partitions.

So just for thought process lets say if we have a single Kafka queue and then following model can be implemented

1. The global topic use action name + namespace as partition key
2. Multiple invokers form a consumer group and subscribe to the above topic 
3. Each invoker then processed activations from the assigned partitions.

Such an approach would enable

1. Single stable topic
2. Simplify scaling by adding new invokers to share load and let Kafka rebalance the partitions to consumer group members
3. Partitioning by action + namespace would ensure stickiness to the invoker and would have same effect as current sharding load balancer strategy

**Comment by tysonnorris** [comment]
Revisiting this, from the starting point of:
- ignoring controller
- ignoring partitioning case

Can we provide a checkout system for ids?  e.g.:
- on start, acquire their id
- on stop, release their id

In a simple impl, we can leave it based on a int, but this becomes a bit arbitrary from invoker point of view - but is convenient that it works with existing load balancer.

For a more detailed example, use a counter in zk:
- invokera start, counter is 0
- invokera increments the counter (0->1)
- invokera id is 0
- invokerb start, counter is 1
- invokerb increments the counter (1->2)
- invokerb id is 1
...
The later one, we want to restart invokerb:
- invokerb stop
- invokerb decrements the counter (2 -> 1)
- invokerb start, counter is 1
- invokerb increments the counter
- invokerb id is 1

Now b has restarted, and is again id=1, but no name is used to associate this id.

The ramifications are:
* during restart, a stop must be processed before restarting 
* during restart, if multiple instances are restarting, the id previously used may end up on a different host after restart is complete
* during a hard crash, the counter must be manually adjusted

The last point is problematic, but may be solvable with a more complicated approach that checks cluster status (for kube/mesos) to determine cases where counter grows > number of instances, etc. 

Alternatively, if we can avoid invokers being tracked as int, we can more easily use some other id, so this may be a temporary solution.

**Comment by chetanmeh** [comment]
> The last point is problematic, but may be solvable with a more complicated approach that checks cluster status (for kube/mesos) to determine cases where counter grows > number of instances, etc.

@tysonnorris  Makes sense. Its what Option #A above refers to as `IdStalenessChecker` which enables having stable and valid ids

**Comment by dgrove-oss** [comment]
This has been quiet for a couple of months, @tysonnorris is there a specific problem with the current mechanism of managing ids via zookeeper with stable names for the invokers that you are trying to solve?

**Comment by tysonnorris** [comment]
The specific problem is that we on mesos are not using stateful applications, so hostnames, container names, etc all change with each start. I know the kube deployment currently relies on StatefulSets, possibly only for this reason, but mesos does not have similar support without additional complications.

**Comment by dgrove-oss** [comment]
ok, got it.  On Kubernetes we have both StatefulSet and DaemonSet to give us logical names. 

If you are missing that in Mesos, then maybe the minimally disruptive change is:
1. Build some id assignment microservice, most likely using zookeeper as you described above.  It would only be used on platforms like Mesos that lack built-in mechanisms for getting stable logical names.
2. Modify the invoker/controller start up path so that we add a new option to get the stable name from that id assignment service instead of assuming it is provided as a command line argument.  Or, in Kubernetes I might set it up so that an init_container contacted the id assignment service so the main invoker/controller code could be completely unchanged.  Does Mesos have something like init containers?

If we can do that, then we could contain the change so it could be easily ignored in systems that don't need it. I guess you also need a hook on shutdown to release the id as well (although I'd be worried about assuming a clean shutdown; invokers especially tend to crash in ugly fashions occasionally.  Can you add the hook externally as a container cleanup action in mesos somehow, so we know it will always be run??).

**Comment by chetanmeh** [comment]
@dgrove-oss As mentioned earlier using statefull approach has a slight issue for the case when such a host gets removed due to some error. In such a case the persistent info would be lost and that topic would become orphan. So if there are any activations in it they would not get processed.

So we may need to have a way to allow another node to claim such orphan topic.

**Comment by chetanmeh** [comment]
For now its the case of invoker ids which we have also discussed in previous comments on this issue

**Comment by dgrove-oss** [comment]
I think it could be restated as being  "how can we provide the capability of StatefulSet/DaemonSet on Mesos" so the rest of the system can assume stable names for things like invokers/controllers.

**Comment by tysonnorris** [comment]
@dgrove-oss can you elaborate on a) how is --uniqueName set and retained for StatefulSet/DaemonSet and b) what happens when a host vanishes in either case (is there any change the --uniqueName for next new host is not set to a value that was already in use?). I tried to decipher this in the deploy-kube repo, but my only guess is that it comes from `.Values.invoker.name`, and it isn't clear how that would get populated.

For mesos, we can do some juggling to track state on the host, but what Chetan points out is that since the state is tracked at the host, when a host goes down completely (as opposed to invoker jvm crash), the --uniqueName that should be used for it's replacement will also be lost. 

In general, this is super critical for invokers, but also important for controllers, where if a controller is revived and does not have precisely the right id (if it is replacing a previous controller instance), then the previous topic will be abandoned. 

This dependency on the cluster manager for state I think is an antipattern since there is otherwise absolutely no need to track state afaik. I definitely recognize there is some convenient ways to do it, but ultimately it would be great for OW to not be so sensitive to host swapping, and really the only way to get there is to remove the id assignment from external systems, and coordinate it internally, probably with assistance from more generic visibility of current cluster state, but not dependent on the cluster state directly. 

Or, if k8s is truly impervious to host crash+swap scenarios where uniqueName is carefully reused, I agree this is probably not worth pursuing 😄.

**Comment by dgrove-oss** [comment]
StatefulSets are truly immune.  Kubernetes creates/recreates the pods with stable pod hostnames that include the ordinal number (eg controller-0, controller-1, etc).  If controller-0 exits for any reason, a new controller-0 is created to replace it.  This ordinal number based name is also available to the pod spec in the helm chart/yaml as `metadata.name`. 

DaemonSets are ensured that as long as the actual worker node is functional, that kubernetes will create/recreate a pod on that node and will set `spec.nodeName` to the ip address of the worker node.  So when using DockerContainerFactory for the invokers, there is a slight gap:  if a worker node becomes permanently disabled, then any work already assigned the invoker on that node will be stranded in its kafka topic.  In practice, I don't think this gap is really worth putting much effort into fixing.  The node can be rebooted/reimaged in a matter of minutes, which is almost always good enough to allow an invoker to be started on it again, which picks up the work.  Furthermore, if the deployment is using the KubernetesContainerFactory for the invokers (OpenShift does), then there is no gap.  In this configuration, we use a StatefulSet and as discussed with the controllers above, when elements of the StatefulSet are lost, they will be recreated with the missing ordinal number. So we can expect to always regain the expected number of invokers, with dense uniqueNames from 0 to N-1.

**Comment by rabbah** [comment]
I believe this is already done.
