### ISSUE TITLE
Action invoke fails when coreshare value > 7 in group_vars/all

### ISSUE THREAD

**Issue by hsane2001** [apache/openwhisk#4014]
## Environment details:

Single and distributed Ubuntu 16.04 deployment
Docker version 18.03.1-ce, build 9ee9f40
CPU - Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
Server has 80 cores.

## Steps to reproduce the issue:

1.  Change  the value of "coreshare" in ansible/group_vars/all to "8"
2.  Build using gradlew distDocker
3.  Deploy openwhisk using ansible
4.  Create a python action (wsk action create prime prime.py) - FYI "which" action does not matter, the underlying issue is in the support of the infrastructure to the parameter "coreshare"
5. Invoke action as "wsk invoke action prime -b -v"

## Provide the expected results and outputs:

Expected result is that the action completes and returns "Hello" to the user.

## Provide the actual results and outputs:

The action is created but fails during invoke with an internal error.

wsk action -i invoke prime-py -b -p range 10000 -d
[commands.NewQualifiedName]:132:[Inf] Qualified pkg+entity (EntityName): prime-py
[commands.NewQualifiedName]:133:[Inf] Qualified namespace: _
[commands.NewQualifiedName]:134:[Inf] Qualified package:
[commands.NewQualifiedName]:135:[Inf] Qualified entity: prime-py
[li/commands.getParameters]:071:[Inf] Parsing parameters: []string{"{\"range\": 10000}"}
[mmands.getJSONFromStrings]:099:[Inf] Convert content to JSON: []string{"{\"range\": 10000}"}
[mmands.getJSONFromStrings]:109:[Inf] Created map 'map[range:10000]' from '{"range": 10000}'
[k.(*ActionService).Invoke]:294:[Inf] HTTP route: actions/prime-py?blocking=true&result=false
[k.(*Client).addAuthHeader]:299:[Inf] Adding basic auth header; using authkey
REQUEST:
[POST]  https://192.168.168.17/api/v1/namespaces/_/actions/prime-py?blocking=true&result=false
Req Headers
{
  "Authorization": [
    "Basic MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1A="
  ],
  "Content-Type": [
    "application/json"
  ],
  "User-Agent": [
    "OpenWhisk-CLI/1.0 (2018-09-05T22:00:18.848+0000) linux amd64"
  ]
}
Req Body
{"range":10000}

[go/whisk.PrintRequestInfo]:459:[Inf] Req Body (ASCII quoted string):
"{\"range\":10000}\n"
RESPONSE:Got response with code 500
Resp Headers
{
  "Access-Control-Allow-Headers": [
    "Authorization, Content-Type"
  ],
  "Access-Control-Allow-Origin": [
    "*"
  ],
  "Connection": [
    "keep-alive"
  ],
  "Content-Length": [
    "89"
  ],
  "Content-Type": [
    "application/json"
  ],
  "Date": [
    "Mon, 10 Sep 2018 21:18:40 GMT"
  ],
  "Server": [
    "nginx"
  ],
  "X-Request-Id": [
    "1891fb56a3e7c0f90c15bbd777700574",
    "1891fb56a3e7c0f90c15bbd777700574"
  ]
}
Response body size is 89 bytes
Response body received:
{"error":"There was an internal server error.","code":"1891fb56a3e7c0f90c15bbd777700574"}
[o/whisk.PrintResponseInfo]:500:[Inf] Response body received (ASCII quoted string):
"{\"error\":\"There was an internal server error.\",\"code\":\"1891fb56a3e7c0f90c15bbd777700574\"}"
[/whisk.parseErrorResponse]:515:[Inf] HTTP failure 500 + body
[/whisk.parseErrorResponse]:530:[Inf] HTTP failure 500; server error There was an internal server error. (code 1891fb56a3e7c0f90c15bbd777700574)
[k.(*ActionService).Invoke]:309:[Err] s.client.Do() error - HTTP req https://192.168.168.17/api/v1/namespaces/_/actions/prime-py?blocking=true&result=false; error 'There was an internal server error. (code 1891fb56a3e7c0f90c15bbd777700574)'
[nds.handleInvocationError]:1014:[Err] Client.Actions.Invoke(prime-py, &{%!t(*whisk.ErrorResponse=&{0xc420019680 0xc420336f40 0xc420336f60}) %!t(int=244) true false false true false false}) error: %!s(MISSING)
[-cli/commands.ExitOnError]:1187:[Inf] err object type: *whisk.WskError
[-cli/commands.ExitOnError]:1198:[Err] Got a *whisk.WskError error: &whisk.WskError{RootErr:(*errors.errorString)(0xc420337230), ExitCode:244, DisplayMsg:true, MsgDisplayed:false, DisplayUsage:true, DisplayPrefix:true, ApplicationError:false, TimedOut:false}
error: Unable to invoke action 'prime-py': There was an internal server error. (code 1891fb56a3e7c0f90c15bbd777700574)
Run 'wsk --help' for usage.

## Additional information you deem important:
Are the Openwhisk limits of coreshare been tested? Are they hardcoded anywhere to be less than 8?

**Comment by cbickel** [comment]
Hi,

how old is the version of Openwhisk you are using? I'm asking, because the paramter `coreshare` has been removed some weeks ago.
If you are using a new version of Openwhisk, this parameter should not be used at all and unrelated to the problem.
If you are using an older version I suggest to go to a newer version and configure the maximum amount of `invoker_user_memory` per invoker instead.

**Comment by hsane2001** [comment]
Its a couple of moths old I think. Here is what I got from the property in the wsk CLI:
whisk API version       v1
whisk namespace         _
whisk CLI version       2018-09-05T22:00:18.848+0000
whisk API build         2018-09-08T00:08:41Z
whisk API build number  latest

I dont however understand how "coreshare" can be replaced by "invoker_user_memory"?
coreshare defines the number of actions/containers you can invoke per core/thread. If this parameter is removed, then how is parallelism or scheduling being managed? i.e What is the limit of number of actions that can be simultaneously handled by a core?

**Comment by cbickel** [comment]
Hi,

this topic has been discussed on the dev list. https://lists.apache.org/thread.html/dfccf972bc1419fe48dbc23119441108c45f85d53625fd6f8fc04fcb@%3Cdev.openwhisk.apache.org%3E

To summarise the main argument:
The user defines, how many memory its action should consume, but the invoker-implementation limited the amount of containers based on the CPU share. This could lead to a massive over- or underload of the invoker (memory-wise).

**Comment by hsane2001** [comment]
Thanks - I will try it out.
