### ISSUE TITLE
Add golang runtime support to default deployments

### ISSUE THREAD

**Issue by csantanapr** [apache/openwhisk#4085]
Title: Add golang runtime support to default deployments

### 1. Add golang to core ansible/vagrant deploy
- Add golang entry into [ansible/files/runtimes.json](https://github.com/apache/incubator-openwhisk/blob/master/ansible/files/runtimes.json#L209)
```
"golang": [
    {
        "kind": "golang:1.11",
        "default": true,
        "deprecated": false,
        "attached": {
            "attachmentName": "codefile",
            "attachmentType": "text/plain"
        },
        "image": {
            "prefix": "openwhisk",
            "name": "actionloop-golang-v1.11",
            "tag": "latest"
        }
    }
]
```
- Update and add doc file into [docs/action_golang.md](https://github.com/apache/incubator-openwhisk/tree/master/docs)
- Update unicode tests https://github.com/apache/incubator-openwhisk/tree/master/tests/dat/actions/unicode.tests

Use Ruby PR as reference: https://github.com/apache/incubator-openwhisk/pull/3725

### 2. Add golang to CLI
- Add support for `--kind golang:x` and prefix `.go`
Use Ruby PR as reference: https://github.com/apache/incubator-openwhisk-cli/pull/352

### 3. Add golang to docker-compose deploy
- Add golang into runtime manifest
https://github.com/apache/incubator-openwhisk-devtools/blob/master/docker-compose/docker-whisk-controller.env#L64
Use Ruby PR as reference: https://github.com/apache/incubator-openwhisk-devtools/pull/150

### 4. Add golang to deploy-kube
- Add golang into runtime manifest
https://github.com/apache/incubator-openwhisk-deploy-kube/blob/master/helm/openwhisk/runtimes.json
Use Ruby PR as reference:https://github.com/apache/incubator-openwhisk-deploy-kube/pull/274 

### 5. Update wskdeploy
Issue opened here https://github.com/apache/incubator-openwhisk-wskdeploy/issues/1004

### 6 Update website
Issue opened here https://github.com/apache/incubator-openwhisk-website/issues/343

**Comment by rabbah** [comment]
Excellent.  Glad to see this!

**Comment by csantanapr** [comment]
I think folks voted in mailing list for `--king go:1.11` over `--kind golang:1.11`
So it needs to be
```
"go": [
    {
        "kind": "go:1.11",
        "default": true,
        "deprecated": false,
        "attached": {
            "attachmentName": "codefile",
            "attachmentType": "text/plain"
        },
        "image": {
            "prefix": "openwhisk",
            "name": "actionloop-golang-v1.11",
            "tag": "latest"
        }
    }
]
```

**Comment by csantanapr** [comment]
core repo PR merged: https://github.com/apache/incubator-openwhisk/pull/4093

**Comment by csantanapr** [comment]
deploy-kube repo merged: https://github.com/apache/incubator-openwhisk-deploy-kube/pull/327

**Comment by csantanapr** [comment]
@daisy-ycguo Do you know if we need changes for wskdeploy?

**Comment by csantanapr** [comment]
The devtools PR is merged: https://github.com/apache/incubator-openwhisk-devtools/pull/172

**Comment by csantanapr** [comment]
core cli PR is merged now: https://github.com/apache/incubator-openwhisk-cli/pull/375

**Comment by csantanapr** [comment]
I need to check if wskdeploy needs to updated with the runtime

**Comment by csantanapr** [comment]
@sciabarracom You want to handle these also

I added items 5 and 6 above

### 5. Update wskdeploy
Issue opened here https://github.com/apache/incubator-openwhisk-wskdeploy/issues/1004

### 6 Update website
Issue opened here https://github.com/apache/incubator-openwhisk-website/issues/343
