### ISSUE TITLE
[discussion] user can't know when entity was updated

### ISSUE THREAD

**Issue by upgle** [apache/openwhisk#4228]
The following CLI command will allow a user to get entity information, but not know when the entity was updated.

```
> wsk action get /seonghyun/hello
```

A document for entities contains a updated date, so we can provide it.
How about adding the updated date in the API response?

```
{
    "namespace": "seonghyun",
    "name": "hello",
    "version": "0.0.18",
    "updated": 1534995596948   <- let's add this line
    "exec": {
        "kind": "nodejs:6",
        "binary": false
    }
}
```

**Comment by rabbah** [comment]
@upgle I think you're suggesting serializing the updated value in the db out in the action/trigger/etc response, is that right?

**Comment by upgle** [comment]
@rabbah Yes, that's right. what do you think of serializing the updated value?

**Comment by rabbah** [comment]
👍 I’m ok with that.
