### ISSUE TITLE
Fail to run action with GPUs using nvidia-docker

### ISSUE THREAD

**Issue by Remumu** [apache/openwhisk#4242]
**Environment:**
Ubuntu 16.04, Local deployment, Using Titan Xp * 4 (driver version 410.79)
Installed openwhisk on docker following the instructions here: https://developer.ibm.com/kr/cloud/openwhisk/2017/07/09/apache-openwhisk-docker-inception/

At first, I tried to write the actions which are using tensorflow applications and realized that it is impossible to recognize GPUs with container made by offered docker image. So, I decided to use the nvidia-docker, which can use GPU on the docker container, and tried to use the image from nvidia, 
which is nvidia/cuda.
When I type the nvidia-smi command by just using docker and nvidia-docker, then it recognizes all the Gpus successfully. (nvidia-docker just give some runtime environment for the docker to use graphic card)

So, we tried to use it on the Openwhisk.
First we added a simple line, runtime:nvidia into the configuration file of the invoker
(at the /openwhisk/core/invoker/build/resources/main/application.conf,
 i added runtime:nvidia at the extra-args part  <---------------- is it right location ??)
 
Then, we tried to create and invoke action through Openwhisk with nvidia/cuda
by giving --docker nvidia/cuda, when we create action
but, as nvidia/cuda image didn't end with 
CMD ["/bin/bash", "-c", "cd actionProxy && python -u actionproxy.py"],
it can't respond to the Openwhisk system.

So we tried to build docker image by using openwhisk/dockerskeleton, but the OS it provides is Alpine
and it looks like there is no matching cuda version.

and also, when we tried to build docker image by using base image nvidia/cuda and created action,
it shows 
Activation: 'hello' (96fe93ba4fd34d1cbe93ba4fd33d1c5d)
[
    "2019-01-29T08:17:22.965829348Z stderr: /bin/bash: line 0: cd: actionProxy: No such file or directory"
]

which means it doesn't have actionproxy

What we want to ask is,

1. How can we get the actionProxy and actionProxy.py from the dockerskeleton so that we can use modified nvidia/cuda image

or 

2. How can we get the Dockerfile of dockerskeleton so that we can change the base images of it into 
another one

or

3. Is there any other good way to use GPU, Cuda and also tensorflow in the Openwhisk?

by the way, is it right to add runtime:nvidia at the configuration file?  like this
container-factory.container-args {
    network: bridge
    dns-servers: []
    dns-search: []
    dns-options: []
    extra-args: { runtime:nvidia }   
  }

**Comment by style95** [comment]
You may be interested in this: https://github.com/apache/incubator-openwhisk-runtime-docker/tree/master/core/actionProxy
