### ISSUE TITLE
How to configure the ssh access among different openwhisk nodes

### ISSUE THREAD

**Issue by houshengbo** [apache/openwhisk#4335]
Since we have got three VMs available for our jenkins pipeline build, we need to configure the ssh access among them in order to install invoker services on different VMs.

Jenkins is using the username "jenkins" to access the VMs, when the jenkins job is launched. I can only access the VMs with my apache id. How can we configure the ssh communication among the VMs for the username "jenkins"?

**Comment by houshengbo** [comment]
@rabbah I definitely need your help with this issue.

**Comment by neerajmangal** [comment]
@houshengbo, You can use the "credential" and "credential binding plugin" of Jenkins to store username and password or Keys in Jenkins. 

I have not seen your Job/pipeline so my observation can be wrong. 
 
- If you are able to create user on Target Machines, preffered method.  
   
    Create a Jenkins user or any other user on target machines and configure SSH Keys. Then store the SSH Keys or Username/Password in the credential plugin in Jenkins. 

- If you are not able to create a user on target machine and have access to Jenkins Machine's "Jenkins" user keys. **Not a good way**. 

  You can copy jenkins user's public keys to your authorized_keys and ssh to VMs from Jenkins by your username with Jenkins Keys.

**Comment by houshengbo** [comment]
@neerajmangal Thanks for the reply. I have three VMs for OpenWhisk builds. What I need is VM1 can access VM2 & VM3 by ssh, VM2 can access VM1 & VM3 by ssh, and VM3 can access VM1 & VM2 by ssh. However, the username "jenkins" used by Jenkins has been created for all these VMs, and I do not know the password for "jenkins" user. I can only login each of the VMs with my apache id, and I can grant "jenkins" user has the root access. 

I can configure the ssh access among these VMs for my apache id, e.g. when I login VM1 with my apache id, I can access VM2 by ssh inside VM1.

I am wondering if "credential" and "credential binding plugin" of Jenkins can resolve my issue for the existing "jenkins" user.

Thank you.

**Comment by houshengbo** [comment]
Hi folks, I have just discovered something new:
Since my apache id has the root access to all the VM1, I can force to use the user "jenkins". Here is what I accomplish:
Take openwhisk VM1 as an example, I can access it via ssh from my local terminal by running "ssh openwhisk-vm1-he-de.apache.org -l houshengbo".
Then, I run the command "sudo su - jenkins" to switch from my apache id to the user jenkins.
After that, I think I can generate the ssh keys on behalf on the user "jenkins", and configure the ssh access among all the VMs for the user "jenkins".

I will try the procedure locally to see if it works.

**Comment by shichawl** [comment]
Hi @houshengbo, you could whitelist your key in the "jenkins" users authorized key and then you may not have to sudo in and apply the other steps.
Also, make sure that you have your apache key added in your shell.

**Comment by houshengbo** [comment]
@shichawl I just tried that, and it still did not work for me in these VMs.
I login each of them VMs, switch to the user "jenkins", and use the command "ssh-keygen -t rsa" to generate the key pairs., so that the public and private keys are both saved under /home/jenkins/.ssh.

Next, I created a file called authorized_keys under /home/jenkins/.ssh for VM1, and add the public key of VM2 into it. I created a file called authorized_keys under /home/jenkins/.ssh for VM2, and add the public key of VM1 into it. 

Hoping ssh access for jenkins may work, I tried "ssh openwhisk-vm2-he-de.apache.org" in VM1 and "ssh openwhisk-vm1-he-de.apache.org" VM2. They both did not work by far.

Do I miss any steps? Or is it the apache's configuration of blocking users except apache ids?

**Comment by shichawl** [comment]
@houshengbo i guess you may have to create another file under /home/jenkins/.ssh call it "config" and add these values in it 
Host *
  StrictHostKeyChecking=no
  UserKnownHostsFile=/dev/null
  IdentityFile /home/.ssh/<id_rsa private file>

Also, did you add the private key in your shell via ssh-add -k <private key>?

**Comment by houshengbo** [comment]
@shichawl I created the config file with the content, and add the private key as well, but the ssh command still did not work.

The error is Permission denied (publickey)

I suspect that Apache has limited rules about how the user can access the VMs via ssh.

**Comment by shichawl** [comment]
Yep, one last check,  check the permissions for your files. Please  run the following:

chmod 700 ~/.ssh
chmod 600 ~/.ssh/authorized_keys

**Comment by houshengbo** [comment]
I succeeded!
There is a file called jenkins.pub under /etc/ssh/ssh_keys, which can be used to stored the authorized public keys. When I put the public key in it, the user jenkins can access this VM remotely.

Also, the configuration of sshd also tells me where to configure. This is the content of the file /etc/ssh/sshd_config:
ListenAddress 0.0.0.0

AcceptEnv LANG LC_*
AuthorizedKeysCommand /etc/ssh/bin/asf-ldap-sshkeys.sh
AuthorizedKeysCommandUser root
AuthorizedKeysFile /etc/ssh/ssh_keys/%u.pub
ChallengeResponseAuthentication no
PasswordAuthentication no
PrintMotd no
Protocol 2
Subsystem sftp /usr/lib/openssh/sftp-server
SyslogFacility AUTHPRIV
UsePAM yes
X11Forwarding no

We can see that the public keys should be saved under /etc/ssh/ssh_keys/.

**Comment by shichawl** [comment]
Perfect.

**Comment by houshengbo** [comment]
Hmm, apache vm automatically revert the content of  /etc/ssh/ssh_keys/jenkins.pub. The change I made did not last. have to figure out why.

**Comment by mrutkows** [comment]
WTG Vincent!

So glad we have you back even more!

**Comment by houshengbo** [comment]
I have created a user called openwhisk:
sudo useradd openwhisk
and grant the root access:
sudo usermod -aG sudo openwhisk

Then, I run the command "ssh-keygen -t rsa" to generate the key pairs.
I created the file openwhisk.pub under /etc/ssh/ssh_keys in VM1, and added the public keys of VM2 and VM3.
I created the file openwhisk.pub under /etc/ssh/ssh_keys in VM2, and added the public keys of VM1 and VM3.
I created the file openwhisk.pub under /etc/ssh/ssh_keys in VM3, and added the public keys of VM1 and VM2.

Among all these three VMs, the user openwhisk can be used to access any of them from the other two by ssh.

**Comment by houshengbo** [comment]
@rabbah Is it possible that openwhisk specifies the username used to access other nodes by ssh? If so, we can specify it to "openwhisk" during openwhisk depoyment, no matter what user logs into the VM.

The worst case is that in jenkinsfile, we access openwhisk1, openwhisk2 and openwhisk3 individually and install the services separately.

Let's wait for the response from apache infra team first.

**Comment by neerajmangal** [comment]
> Hmm, apache vm automatically reverts the content of /etc/ssh/ssh_keys/jenkins.pub. The change I made did not last. Have to figure out why.
> 
> I opened an issue for apache infra team to look at: https://issues.apache.org/jira/browse/INFRA-18003. I offered two ways to resolve this issue.
> @neerajmangal @shichawl @rabbah @mrutkows

I think you should have the pub file in /home/jenkins/.ssh, Infra team might be monitoring the directory /etc/ssh/ where you have placed the public keys. Also, I don't think you need three SSH keys to be generated on each machine as that will be difficult to maintain during deployment. 

Assuming you have permission to create a user on all of the VMs. 

- Create a user on all VMs and password -  owdeployer. For simplicity, you can have the same password. 
- Generate SSH keys - you can generate them anywhere. 
- Copy SSH Key to all VMs, this will automatically save the keys to /home/owdeployer/.ssh with proper permissions. 

```bash 
ssh-copy-id -i <path-to-public-key> owdeployer@<target-machine>
```  

- Check if you able to access VMs with private key remotely. 
- You can store Private Key in the Jenkins Credential and Credential Binding plugin and use it in job to deploy openwhisk components on all distributed VMs with user as owdeployer in ansible.cfg.

**Comment by houshengbo** [comment]
@neerajmangal I can definitely simplify the steps as you said, but the problem is that when jenkins launch the build jobs, the default user "jenkins" is used, not the user we created for openwhisk deployment. Currently, "jenkins" is a user not configurable for ssh access among these VMs(I tried, but the config got reverted every 30 mins as in me previous comments). That is why I ask whether openwhisk environment allows us to configure the user for ssh access to other machines, or we have an alternative way to bypass the ssh configuration.

**Comment by neerajmangal** [comment]
I believe we can use our own user to execute remote commands from Jenkins in the build section, it can be a bash script which will run the deployment steps (running ansible playbooks). 

One other way to do it to ssh to one of the remote VMs (master one) from Jenkins Job's build section and execute the commands from there. This way Jenkins dependencies will be removed.   

Also, let me know what is in your Jenkins Job, that way I can better help in that.  

I attempted a similar setup long time back, let me check if I can opensource it. It is having some specific stuff related to our environment, I will see if that can be removed, optimized and shared.

**Comment by style95** [comment]
@houshengbo Seems this can be closed?
