### ISSUE TITLE
remove web actions projections

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk#4352]
A webaction today allows you to do some projections of the result in the URL. For example
```
 curl /path/to/webaction.json/some/field
```

Will project a field called `.some.field` from the response of the webaction.

This has been proving annoying in my own experience developing web actions, where I'd like to use the path after the webaction as an actual resource path.

We removed projections on `.http` webactions and I'm proposing for discussion that we take it out for all extensions.

cc @csantanapr

**Comment by csantanapr** [comment]
SGTM take it out +1

**Comment by rabbah** [comment]
I prepared a draft patch here https://github.com/apache/incubator-openwhisk/compare/master...rabbah:noprojections?expand=1.

**Comment by jthomas** [comment]
👍 on this. I think this feature is super confusing for users and can't really see a valid use-case.

**Comment by rabbah** [comment]
Thanks @jthomas @csantanapr - my own experience is that it is also very difficult to use and I doubt there are any actual uses for this feature. The PR removes the feature - do we need a feature toggle?
