### ISSUE TITLE
How can I trace big computation action processes error in detail, like, a 10 minutes computation task?

### ISSUE THREAD

**Issue by Bobyuan1015** [apache/openwhisk#4406]
This is a big computation task, takes around 10 minutes on the local host.
And, I also run openwhisk locally.

The activation poll just shows," data missing", but what exact data is missing? Any solution for tracing this issue?

$ wsk -i action invoke word --result -v
REQUEST:
[POST]	https://10.239.93.78/api/v1/namespaces/guest/actions/word?blocking=true&result=true
Req Headers
{
  "Authorization": [
    "Basic MjNiYzQ2YjEtNzFmNi00ZWQ1LThjNTQtODE2YWE0ZjhjNTAyOjEyM3pPM3haQ0xyTU42djJCS0sxZFhZRnBYbFBrY2NPRnFtMTJDZEFzTWdSVTRWck5aOWx5R1ZDR3VNREdJd1A="
  ],
  "Content-Type": [
    "application/json"
  ],
  "User-Agent": [
    "OpenWhisk-CLI/1.0 (2019-03-20T20:17:38.064+0000) linux amd64"
  ]
}
Req Body
{}

RESPONSE:Got response with code 202
Resp Headers
{
  "Access-Control-Allow-Headers": [
    "Authorization, Origin, X-Requested-With, Content-Type, Accept, User-Agent"
  ],
  "Access-Control-Allow-Methods": [
    "GET, DELETE, POST, PUT, HEAD"
  ],
  "Access-Control-Allow-Origin": [
    "*"
  ],
  "Connection": [
    "keep-alive"
  ],
  "Content-Length": [
    "51"
  ],
  "Content-Type": [
    "application/json"
  ],
  "Date": [
    "Thu, 28 Mar 2019 07:37:56 GMT"
  ],
  "Server": [
    "openresty/1.13.6.2"
  ],
  "X-Openwhisk-Activation-Id": [
    "b73113029a8e4c49b113029a8e6c4937"
  ],
  "X-Request-Id": [
    "wkk0JwcwVna0aHKwFF7SSYwmJ9qmB0NA"
  ]
}
Response body size is 51 bytes
Response body received:
{"activationId":"b73113029a8e4c49b113029a8e6c4937"}
ok: invoked /guest/word, but the request has not yet finished, with id b73113029a8e4c49b113029a8e6c4937

$ wsk -i activation poll
Enter Ctrl-c to exit.
Polling for activation logs

Activation: 'word' (37090a36a94a46b0890a36a94a26b055)
[
    "2019-03-28T07:25:30.066Z       stderr: There was an issue while collecting your logs. Data might be missing."
]

Activation: 'word' (0bfdc7200a124232bdc7200a128232ce)
[
    "2019-03-28T07:20:44.416Z       stderr: There was an issue while collecting your logs. Data might be missing."
]

Activation: 'word' (cdaf0f32e7fc4efeaf0f32e7fc0efe9c)
[
    "2019-03-28T07:37:11.666Z       stderr: There was an issue while collecting your logs. Data might be missing."
]

Activation: 'word' (cdd2ec36f2c2422292ec36f2c2722230)
[
    "2019-03-28T07:39:47.417Z       stderr: There was an issue while collecting your logs. Data might be missing."
]

Activation: 'word' (b73113029a8e4c49b113029a8e6c4937)
[
    "2019-03-28T07:42:25.707Z       stderr: There was an issue while collecting your logs. Data might be missing."
]

**Comment by rabbah** [comment]
Closing as actionable - the action failed/threw an exception and aborted the container abruptly. Usually you can reproduce the errors locally and it will be easier.
