### ISSUE TITLE
Log lost in method 'KubernetesRestLogSourceStage.readLines'

### ISSUE THREAD

**Issue by ysjjovo** [apache/openwhisk#4409]
If filter 'isRelevantLogLine(lastTimestamp, timestamp)' in 'for iterator' of method 'readLines' cause lose logs.Dose anyone ever come across this problem?Dose anyone tell what is this for?

Sample function of 'nodejs6' below.It will lose about 10% logs.
```nodejs
function main(args){
    for(var i=0;i<10;i++){
        for(var j=0;j<10;j++){
            console.log(j);
        }
    }
    return args;
}
```

**Comment by ysjjovo** [comment]
Invoker upper sample 'nodejs' function,r'eadLines' method fetch logs from k8s looks like below
`2019-04-11T15:47:08.617316084Z 6
2019-04-11T15:47:08.61732014Z 7
2019-04-11T15:47:08.617325379Z 8
2019-04-11T15:47:08.61732974Z 9`
Some timestamp nanoseconds lost a zero in the end, therefore it's value less than last timestamp.
this line will be lost.
we could use code blew to verify this.
`import java.time.format.DateTimeFormatterBuilder
import java.time.{Instant, ZoneId}
object InstantTest {
  def main(args:Array[String]): Unit ={
    val K8STimestampFormat = new DateTimeFormatterBuilder()
      .parseCaseInsensitive()
      .appendPattern("u-MM-dd")
      .appendLiteral('T')
      .appendPattern("HH:mm:ss[.n]")
      .appendLiteral('Z')
      .toFormatter()
      .withZone(ZoneId.of("UTC"))

    val lastTimestamp=Instant.from(K8STimestampFormat.parse("2019-04-11T15:47:08.617316084Z"))
        val timestamp=Instant.from(K8STimestampFormat.parse("2019-04-11T15:47:08.61732014Z"))
    print(isRelevantLogLine(Option(lastTimestamp),timestamp))
  }
  def isRelevantLogLine(lastTimestamp: Option[Instant], newTimestamp: Instant): Boolean =
    lastTimestamp match {
      case Some(last) =>
        newTimestamp.isAfter(last)
      case None =>
        true
    }
}`

**Comment by dgrove-oss** [comment]
The same container can be re-used to execute multiple invocations of the same action.  The goal is to extract just the relevant log lines (those belonging to "this" activation).  The challenge is that loglines may not be demarcated with sentinel lines and that Kubernetes timestamps are fairly coarse grained.

The patch you provided in #4440 at first glance looks like it could result in extra loglines (logs from preceding activations) being redundantly recorded in the current activation's logs.

**Comment by ysjjovo** [comment]
You're right,Fetching K8S HTTP Logs with parameter sinceTime may get additional logs,sample debug log below show this.

```log
[2019-04-22T10:02:43.648Z] [DEBUG] *** Fetching K8S HTTP Logs w/ Path: /api/v1/namespaces/***/pods/wskinvoker-00-5-log-lost-test/log Query: timestamps=true&sinceTime=2019-04-22T09:55:02.$\color{red}{893115523Z}$

[2019-04-22T10:02:43.666Z] [DEBUG] * Read & decoded lines for K8S HTTP: List(2019-04-22T09:55:02.$\color{red}{885279349Z}$ stdout:AAAAA, 2019-04-22T09:55:02.893040214Z stdout: XXX_THE_END_OF_A_WHISK_ACTIVATION_XXX, 2019-04-22T09:55:02.$\color{red}{893115523Z}$stdout: XXX_THE_END_OF_A_WHISK_ACTIVATION_XXX)
```

In this situation,field lastTimeStamp will always be set to 2019-04-22T09:55:02.$\color{red}{893115523Z}$,then all invocation will get the same log.
So we should filter it manually,but docker json log field don't produce 9 digit nanosecond all the time,this will make this filter filt some normal logs for mistake.
