### ISSUE TITLE
How can I run tensorflow sample on openwhisk locally instead ibm bluemux?

### ISSUE THREAD

**Issue by Bobyuan1015** [apache/openwhisk#4417]
I need a sample on local openwhisk. The sample should not be a hello-world program. At least, the computation time of running this sample on my local openwhisk is over 500ms, or less than 3 minutes.

Many thanks for any sample, any suggestion, any guidance.

**Comment by rabbah** [comment]
You'll want to create a docker action - or try http://jamesthom.as/blog/2018/08/13/serverless-machine-learning-with-tensorflow-dot-js/.
