### ISSUE TITLE
How can I get latency measure for cold start? I know the warm-start measure, which would be tested by owperf.

### ISSUE THREAD

**Issue by Bobyuan1015** [apache/openwhisk#4439]
How can I get latency measure for the cold start way process? 

I'v known the warm-start measure, which would be tested by owperf, shown below:

All clients finished warmup. Start measurement.
MASTER-0:	Stop measurement. Start post-processing after 60000 msec
MASTER-0:	    bi,	          as,	            ae,	            ts,	         ta,	oea,	oer,	d,	ad,	   ai,	           ora,	           rtt,     	 ortt
WORKER-1:	1554966125355,	1554966133062,	1554966133116,	1554966125391,	7671,	7707,	7711,	50,	54,	undefined,	undefined,	undefined,	undefined

**Comment by rabbah** [comment]
the activation record for an action has an annotation called `initTime` which is there only for cold-start.

Closing as stale/inactionable.
