### ISSUE TITLE
How does Wrk test openwhisk performance during cold-start, especially latency

### ISSUE THREAD

**Issue by Bobyuan1015** [apache/openwhisk#4449]
I'd like to test latency performance during cold-start action on openwhisk, and known 'latency.sh'
Is there any guide to run this sh, and does it can satisfy my goal or not ?

set -e

currentDir="$(cd "$(dirname "$0")"; pwd)"

# Host to use. Needs to include the protocol.
host=$1
# Credentials to use for the test. USER:PASS format.
credentials=$2
# Path to action src
action_src=$3
# How long to run the test
duration=${4:-30s}

$currentDir/throughput.sh $host $credentials  $action_src 1 1 1 $duration

**Comment by rabbah** [comment]
Closing as stale/inactionable.
