### ISSUE TITLE
Recover / Re-create action /whisk.system/github/webhook failed

### ISSUE THREAD

**Issue by noodle88** [apache/openwhisk#4467]
Hi all,
I just run API and removed whisk.system/github/webhook action :  /whisk.system/github/webhook 
Now, I created action again but its just create as a normal function with code.
Then I cannot add webhook again

How to recover / re-create it?
API (PUT): api/v1/namespaces/whisk.system/actions/github/webhook
Body:
`
{
    "namespace": "whisk.system/github",
    "name": "webhook",
    "version": "0.0.46",
    "exec": {
        "kind": "nodejs:6",
        "code":""
        "binary": false
    },
    "annotations": [
        {
            "key": "description",
            "value": "Creates a webhook on GitHub to be notified on selected changes"
        },
        {
            "key": "feed",
            "value": true
        },
        {
            "key": "sampleInput",
            "value": {
                "accessToken": "123ABCXYZ",
                "events": "push,delete,pull-request",
                "repository": "myRepository or myOrganization/myRepository",
                "username": "myUserName"
            }
        },
        {
            "key": "exec",
            "value": "nodejs:6"
        },
        {
            "key": "parameters",
            "value": [
                {
                    "bindTime": true,
                    "description": "Your GitHub username",
                    "name": "username",
                    "required": true
                },
                {
                    "bindTime": true,
                    "description": "The name of a GitHub repository",
                    "name": "repository",
                    "required": true
                },
                {
                    "bindTime": true,
                    "description": "A webhook or personal token",
                    "doclink": "https://github.com/settings/tokens/new",
                    "name": "accessToken",
                    "required": true
                },
                {
                    "description": "A comma-separated list",
                    "doclink": "https://developer.github.com/webhooks/#events",
                    "name": "events",
                    "required": true
                }
            ]
        }
    ],
    "limits": {
        "timeout": 60000,
        "memory": 256,
        "logs": 10,
        "concurrency": 1
    },
    "publish": false
}
`
## Environment details:
* local deploymen: ubuntu
## Steps to reproduce the issue:
1.   DELETE action webhook (DELETE) : /whisk.system/github/webhook
2.  CREATE action webhook (PUT) : /whisk.system/github/webhook 
3.  CREATE binding package to GitHub and Triger:
3.1 Bingding git: 
 `wsk -i -d package bind /whisk.system/github git_binding_name \
 --param username git_username \
 --param repository myGitRepo \
 --param accessToken git_token`
Response:    ok: created binding git_binding_name

  3.2 Create trigger to add webhook: 
   `wsk -i trigger create my_git_triger --feed git_binding_name/webhook --param events push -d`
Error:` {
    "response": {
        "result": {
            "error": "Missing main/no code to execute."
        },
        "status": "action developer error",
        "success": false
    }
}`
As I know, whisk.sytem/github/webhook now as a normal function , not as the first time 

## Provide the expected results and outputs:
Expected: github/webhook added

Please help me.
Thanks

**Comment by jiangpengcheng** [comment]
normally you can use `ansible postdeploy.yml` to recreate all actions in [openwhisk-catalog](https://github.com/apache/incubator-openwhisk-catalog)

and for your issue, the body you put doesn't contain any code, so the action cannot be invoked, you should recreate the action with some source code file like:
```
wsk action create github/webhook openwhisk-catalog/packages/github/webhook.js
```
see [action-nodejs.md](https://github.com/apache/incubator-openwhisk/blob/master/docs/actions-nodejs.md)
