### ISSUE TITLE
Provide Whisk SDK for Python

### ISSUE THREAD

**Issue by ioana-blue** [apache/openwhisk#450]
I think it would be really nice to have a small SDK for Python that allows a python coder to access whisk rest api from their python action very easily. For example, the SDK should support invoking actions, firing triggers, getting logs, etc. I believe there is such an SDK for javascript.

**Comment by rabbah** [comment]
Repurpose the `wsk cli`?

**Comment by ioana-blue** [comment]
One thing that would be useful part of the SDK is a way to retrieve auth credentials such that it's easier for a python action to invoke a different action.
