### ISSUE TITLE
Update cache-invalidator build.gradle file to resolve bluemix-openwhiskl-cli build issue. 

### ISSUE THREAD

**Issue by steven0711dong** [apache/openwhisk#4574]
Currently plugin import uses an absoluate path. `apply from: "${project.rootProject.projectDir.absolutePath}/gradle/docker.gradle"`, which causes PG build issues for bluemix-openwhisk-cli. 

Will need to change it to apply from: ‘../../../gradle/docker.gradle’

**Comment by rabbah** [comment]
Sorry I don’t understand the issue. It looks like the way you’re building causes the root to be different. Is the change to a relative path unique to this file? I didn’t check if we are using relative or absolute elsewhere.

**Comment by steven0711dong** [comment]
@rabbah Sorry, I'm supposed to change it to `‘../../../gradle/docker.gradle’`, not `‘../../../gradle/docker.gradle’`. I think bluemix-openwhisk-cli build uses a different path so this import cannot be an absolute path, so I want to change it to relative path. I believe relative paths are used in most build.gradle file.
