### ISSUE TITLE
NoSuchMethodError:com/google/gson/reflect/TypeToken.getParameterized

### ISSUE THREAD

**Issue by zhaoyangmushiyi** [apache/openwhisk#4601]
I can successfully run in my local environment, but when I run main method in Functions by java environment I get the error:
"error": "An error has occured while invoking the action (see logs for details): java.lang.NoSuchMethodError: com/google/gson/reflect/TypeToken.getParameterized(Ljava/lang/reflect/Type;[Ljava/lang/reflect/Type;)Lcom/google/gson/reflect/TypeToken; (loaded from file:/javaAction/build/libs/javaAction-all.jar by sun.misc.Launcher$AppClassLoader@a469db90) called from class com.cloudant.client.api.Database (loaded from file:/tmp/useraction2986047301306946649.jar by org.apache.openwhisk.runtime.java.action.JarLoader@c126b7e8)."

I use maven and already added gson dependency.

**Comment by nikolavukovic** [comment]
Hello,
have you solved this issue or maybe found a workaround? I am having the exact same problem when using Cloudant 2.19.0. I need to make a query which fetches JSONs from CouchDB. The query api uses getParameterized method which is not present in GSON lib versions < 2.8.6. It seems that the java runtime uses 2.8.5, even when 2.8.6 is added as a maven dependency.
