### ISSUE TITLE
key 'kind' does not exist

### ISSUE THREAD

**Issue by jiangpengcheng** [apache/openwhisk#4615]
There will be a `key 'kind' does not exist` error while a `generateFallbackActivation` is used as the `generateFallbackActivation` won't add the `kind` annotation to `WhiskActivation`:

```scala
  private def generateFallbackActivation(msg: ActivationMessage, response: ActivationResponse): WhiskActivation = {
    val now = Instant.now
    val causedBy = if (msg.causedBySequence) {
      Some(Parameters(WhiskActivation.causedByAnnotation, JsString(Exec.SEQUENCE)))
    } else None

    WhiskActivation(
      activationId = msg.activationId,
      namespace = msg.user.namespace.name.toPath,
      subject = msg.user.subject,
      cause = msg.cause,
      name = msg.action.name,
      version = msg.action.version.getOrElse(SemVer()),
      start = now,
      end = now,
      duration = Some(0),
      response = response,
      annotations = {
        Parameters(WhiskActivation.pathAnnotation, JsString(msg.action.asString)) ++ causedBy
      })
  }
```

but while send UserEvent, the `ActivationMessage.from` require the `kind` annotation:

```scala
  /** Constructs an "Activation" event from a WhiskActivation */
  def from(a: WhiskActivation): Try[Activation] = {
    for {
      // There are no sensible defaults for these fields, so they are required. They should always be there but there is
      // no static analysis to proof that so we're defensive here.
      fqn <- a.annotations.getAs[String](WhiskActivation.pathAnnotation)
      kind <- a.annotations.getAs[String](WhiskActivation.kindAnnotation)
    } yield {
      Activation(
        fqn,
        a.response.statusCode,
        a.duration.getOrElse(0),
        a.annotations.getAs[Long](WhiskActivation.waitTimeAnnotation).getOrElse(0),
        a.annotations.getAs[Long](WhiskActivation.initTimeAnnotation).getOrElse(0),
        kind,
        a.annotations.getAs[Boolean](WhiskActivation.conductorAnnotation).getOrElse(false),
        a.annotations
          .getAs[ActionLimits](WhiskActivation.limitsAnnotation)
          .map(_.memory.megabytes)
          .getOrElse(0),
        a.annotations.getAs[String](WhiskActivation.causedByAnnotation).toOption)
    }
  }
```

since the `kind` data is not easy to get when generate fallback activation, is it ok to make it optional?

**Comment by sven-lange-last** [comment]
@jiangpengcheng your proposal makes sense. I agree with what you wrote on the dev mailing list: 

> When get action from DB is failed or namespace is blacklisted while invoking an activation, the `InvokerReactive` will generate a fallback result for it, in these cases, it's not possible to get the `kind` info.

Maybe extend `generateFallbackActivation()` such that we can pass additional desired annotations, add `unknown` to the list of pre-defined kinds and call `generateFallbackActivation()` with `Parameters(WhiskActivation.kindAnnotation, JsString(Exec.UNKNOWN))`.

https://github.com/apache/openwhisk/blob/d4d7ceb627573670f70993d4e31dcf2a6737c3f8/common/scala/src/main/scala/org/apache/openwhisk/core/entity/Exec.scala#L239-L243

**Comment by jiangpengcheng** [comment]
@sven-lange-last thanks for the suggestions!

**Comment by jiangpengcheng** [comment]
closed as merged

**Comment by jiangpengcheng** [comment]
gg
