### ISSUE TITLE
better error message for unsupported kind

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk#4616]
Using a runtime that is not supported produces this API response.

```
kind 'nodejs:12' not in Set(python:3.6, php:7.1, dotnet:2.2, go:1.11, swift:4.1, nodejs:10, ballerina:0.990, ruby:2.5, nodejs:, nodejs:6, php:7.2, python:3, python, python:2, python:3.7, swift, php:7.3, swift:3.1.1)
```

we should format the error message better than that.

**Comment by ali-raza-tariq** [comment]
How about, 
```
the specified runtime 'nodes:12' is not yet supported by the platform. Set(python:3.6, php:7.1, dotnet:2.2, go:1.11, swift:4.1, nodejs:10, ballerina:0.990, ruby:2.5, nodejs:, nodejs:6, php:7.2, python:3, python, python:2, python:3.7, swift, php:7.3, swift:3.1.1) shows all the valid candidates.
```
does that work?

**Comment by rabbah** [comment]
the specified runtime 'nodejs:12' is not supported by this platform. Valid values are: python:3.6, php:7.1, dotnet:2.2, go:1.11, swift:4.1, nodejs:10, ballerina:0.990, ruby:2.5, nodejs:, nodejs:6, php:7.2, python:3, python, python:2, python:3.7, swift, php:7.3, swift:3.1.1.

**Comment by rabbah** [comment]
Could also put quotes around each kind.

**Comment by ali-raza-tariq** [comment]
sounds good!

**Comment by ali-raza-tariq** [comment]
For better structure (as discussed), errorMessage for unsupported kind has been moved to `ErrorResponse.scala`.

**Comment by nitikagarw** [comment]
Hi @rabbah, 
Does this issue require more work? I see the above PR was merged which addresses the discussion here. 
Thanks, 
Nitika Agarwal

**Comment by rabbah** [comment]
This is fixed. Thanks @nitikagarw for the nudge.
