### ISSUE TITLE
ubuntu_setup/all.sh fails on ElementaryOS

### ISSUE THREAD

**Issue by anandskumar** [apache/openwhisk#4621]
## Environment details:

* local deployment, vagrant, native ubuntu, Mac OS, Bluemix, ...   
Local Deployment on ElemtaryOS 5.0 Juno (based on Ubuntu 18-04 Bionic)

* version of docker, vagrant, ubuntu, ...
Ubuntu 18-04

## Steps to reproduce the issue:

1. cd tools/ubuntu  
2.   ./all.sh

## Provide the expected results and outputs:

```
```

## Provide the actual results and outputs:

```
Reading package lists... Done                                                                     
E: The repository 'https://download.docker.com/linux/ubuntu juno Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

## Additional information you deem important:
* The script uses 'lsb_release -cs' to get the Ubuntu version codename. But elementary reports its own codename - 'juno' instead of 'bionic'

* changes you did or observed in the environment
I hardcoded the codename wherever needed. But you can also use /etc/os_release which has the Ubuntu release it is based on.

**Comment by rabbah** [comment]
@anandskumar we welcome contributions - if you'd like to address this please reopen/and submit a PR.
