### ISSUE TITLE
Correct the contribution coding standards description or CI check behavior plz 

### ISSUE THREAD

**Issue by BillZong** [apache/openwhisk#4649]
The CI use `scalafmt` format checking, while the description says we should use `scalariform`.

That would mislead contributors and make the PR failed whenever we use `scalariform` to format our code.

Every time I have to format the code use `scalariform`, and explicitly save the file to make `scalafmt` auto format happen.
= =

The document description is [here](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md#coding-standards)

**Comment by rabbah** [comment]
The docs should say scalafmt. Sorry about that.

**Comment by rabbah** [comment]
The jetbrains Link should be https://plugins.jetbrains.com/plugin/8236-scalafmt/ which actually requires no install in the latest version (it’s bundled in).

**Comment by BillZong** [comment]
Yeap, the plugin is used by default. And "auto format when saving" setting is saving my time.

Correct the document and close this issue plz. XD
