### ISSUE TITLE
action can be deleted with wsk trigger delete

### ISSUE THREAD

**Issue by AkimitsuTosha** [apache/openwhisk#4673]
## Environment details:

* local deployment

## Steps to reproduce the issue:

1.   `wsk action create hello_action hello.js`
2.   `wsk trigger delete hello_action`

## Provide the expected results and outputs:

I expect the following behavior
```
 $ wsk trigger delete hello_action
 error: Unable to delete action 'hello_action': Resource by this name exists but is not in this collection. (code xxx)\
```

## Provide the actual results and outputs:

The action can be deleted with `wsk trigger delete`.
here is the demo commands:
```
$ wsk action create hello_action hello.js 
ok: created action hello_action

 # can delete the action with wsk trigger delete
 $ wsk trigger delete hello_action
 ok: deleted trigger hello_action

$ wsk trigger create hello_trigger
ok: created trigger hello_trigger

 # triggers cannot be deleted with wsk action delete
 $ wsk action delete hello_trigger
 error: Unable to delete action 'hello_trigger': Resource by this name exists but is not in this collection. (code xxx)\
```

## Additional information you deem important:

triggers cannot be deleted with `wsk action delete`

**Comment by rabbah** [comment]
It’s worth nothing that for pre-existing actions the behavior will continue as reported until the assets are updated to include the entityType.
