### ISSUE TITLE
Openwhisk users & namespaces wskadmin utility - clarification

### ISSUE THREAD

**Issue by ali-raza-tariq** [apache/openwhisk#4687]
Hi guys,  i have been testing with OpenWhisk (docker-compose) environment so far and want to try out `wskadmin` Utility. Surprisingly, i could not find any detailed resources that could provide significant background except the install instructions and some use-instructions for `wskadmin`. I would really appreciate if someone could clarify a few things in this regard. 

First, what is the difference between a user & namespace when using wskadmin. Normally, a namespace is a logical entity that can be subjected to various limits and rule, and can have multiple users but in another issue (https://github.com/apache/openwhisk-deploy-kube/issues/61), i found someone answered creating the namespace the same way you create user! using `wskadmin` (which makes it confusing). If this is true then how can we add multiple users in the same namespace?- won't that be just like creating new namespaces? Also the -ns (namespace) flag is no longer working (whenever i try to use it, it shows `[wskadmin] Error: Unknown option 'n'`). Has it been deprecated or changed?

Second, are the namespaces created using `wskadmin` utility in any way different than the OpenWhisk namespace? The reason i ask this is, when i created multiple users/namespaces using `wskadmin`, i am unable to see them in `wsk -i namespace list`. 

Third, when you deploy OpenWhisk (docker-compose), you have a serverless environment with guest namespace. I want to create different namespaces with different limits (i am assuming `wskadmin` can help me do this!), then run invocations in those namespaces and analyze the invocation behaviors. I don't know, even after i create different users, how to switch between users & namespaces for testing. Or does users need to join/login (how?) my OpenWhisk deployment separately (different terminal)? 

Can someone provide resources that can help me in this regard? thanks!

**Comment by rabbah** [comment]
A user (subject) may have belong to more than one namespace. Two subjects that share namespace have equal rights to it.

When you create a subject or namespace with wskadmin you are create an identity in the database for them. 

Each namespace has a unique key. When you use wsk property set —auth you configure it for that namespace. 

The wsk namespace list operation lists all namespaces authorized by the key. Since it’s bijective you will see only one key. 

Historically a key had access to all namespaces for a subject but this is no longer the case.

**Comment by rabbah** [comment]
When you create a subject or namespace with wskadmin the tool prints out the auth key for it. You can also retrieve it with wskadmin user get. You have to use this AUTH key with REST api calls or wsk cli (—auth).

**Comment by ali-raza-tariq** [comment]
thanks for explaining @rabbah, one more thing - how do you create a namespace? like I mentioned  above another issue is creating namespace the same way you create user (then can they be two different entities). Also, I would assume when you create a new user, it will only belong to the guest namespace unless you manually add it to respective namespaces using `-ns` flag (which no longer seems to be working - has it been deprecated?).

**Comment by rabbah** [comment]
When you create a new user they are assigned their own namespace. 

If the flag isn’t working there could be a regression in the docs. This functionality is tested.

**Comment by rabbah** [comment]
```
> wskadmin user create guest1
9e0693f9-ea91-4a94-92ce-7d2f25397dda:...

> wskadmin user create guest2
6276cb16-ccc9-4076-88cd-74465ad03b51:...

> wskadmin user create guest2 -ns sharedspace
f391012d-b6e5-45fe-9080-74aab31a6535:...

> wskadmin user create guest1 -ns sharedspace
b386fb16-7838-425c-9d8a-d8c5ffd32e14:...

> wskadmin user list sharedspace --all
b386fb16-7838-425c-9d8a-d8c5ffd32e14:...	guest1
f391012d-b6e5-45fe-9080-74aab31a6535:...	guest2
```

I don't see a problem with `-ns`.

**Comment by ali-raza-tariq** [comment]
interesting! I couldn't get the `wskadmin` utility to work initially because the `whisk.properties` environment is not setup by default and I didn't know how to!, so I did gradle build for `wskadmin-next`. I have been using that executable which still doesn't seem to work with `-ns` flag. Just set those environment variable up and tested with existing `/bin/wskadmin`, it works fine.

**Comment by chetanmeh** [comment]
> I have been using that executable which still doesn't seem to work with -ns flag

@ali-raza-tariq This was a bug in documented example as `wskadmin-next` argument support bit different formats. More details and updated document now provided in #4692
