### ISSUE TITLE
Kafka Ver. 0.11.0.1 uses OracleJDK

### ISSUE THREAD

**Issue by JiniousChoi** [apache/openwhisk#4717]
The default Kafka version 0.11.0.1 utilizes JAVA(TM) internally, it seems.
So, I got wondering if you have any issue with upgrading the version of Kafka, say, to 3.4.x or to 3.5.x. Because both of those docker images use OpenJDK I think no one would need to worry about the license issue.

So, my question is, in a nutshell, do I need to change the version of Kafka on my own if I want to keep it free, using Openwhisk as a whole?

```bash
$ docker exec -i kafka0 java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by dgrove-oss** [comment]
I think upgrading to a more recent Kafka release (eg. 2.2.x) would be a worthwhile project.  I don't know how much or little effort this would take.  Someone would need to take a careful look at the release notes since 0.11.x and see what changes were made in the clients and in the configuration details of the docker image.

**Comment by JiniousChoi** [comment]
@dgrove-oss 
I am in a position where I need to upgrade it to a recent release due to the license issue. Since it seems that it's me who wants this change the most why don't I have a chance to take a look at it and proceed with the upgrading process?

**Comment by dgrove-oss** [comment]
Sounds good; thanks @JiniousChoi!

**Comment by style95** [comment]
@JiniousChoi 
If you look into it, it would be greatly appreciatable.

I think a few Kafka libraries are being used in some places such as `KafkaMessagingProvider` and `MessageFeed`. 
(Since I didn't look into it deeply, there can be more components which dependent on Kafka.)

We need to figure out such components are compatible with the latest Kafka.
I think we may need to upgrade those libraries as well.

**Comment by JiniousChoi** [comment]
Sounds good! Then I'll look into the release notes for Kafka soon

**Comment by JiniousChoi** [comment]
Also, I have a question. I read some hints that the team would use Vagrant for the development of Openwhisk at this [README.md](https://github.com/apache/openwhisk/blob/master/tools/vagrant/README.md#create-a-vagrant-vm). It is still valid? If so, would you use it for integration tests as well? Some recommendations would be appreciated.

**Comment by style95** [comment]
In the upstream Travis build, we are deploying OpenWhisk natively.

**Comment by JiniousChoi** [comment]
@dgrove-oss Then how about the local test? Do you use Vagrant to keep the environment the same, controlled across all the developers? Or do you just let them develop on whatever host machine they have?

**Comment by rabbah** [comment]
Likely there are many camps on this. Some like kube some native ansible and some compose to give an idea. My suggestion: use the standalone controller it’ll be easier and faster for you. We maintain the vagrant box so infrequently. I’ve been increasingly switching from ansible to standalone and like it. https://github.com/apache/openwhisk/blob/master/core/standalone/README.md

**Comment by dgrove-oss** [comment]
I think Vagrant is the least used environment.  Perhaps it is time to remove it from the documentation.

**Comment by rabbah** [comment]
less is more :)

**Comment by JiniousChoi** [comment]
That's what I was asking! Thanks a lot :)

**Comment by JiniousChoi** [comment]
And, I'd love to read through a guiding document for Openwhisk developers if there is any.
Neither [CONTRIBUTING.md](CONTRIBUTING.md) nor [Recommended-Reading-for-OpenWhisk-Developers wiki](https://github.com/apache/openwhisk/wiki/Recommended-Reading-for-OpenWhisk-Developers) seems comprehensive, judging by not including the local environment as you guys recommend.

**Comment by style95** [comment]
> I think Vagrant is the least used environment. Perhaps it is time to remove it from the documentation.

+1 on this.

And I think it would be also great to change our QuickStart guide to the one based on standalone deployment.
https://github.com/apache/openwhisk#quick-start

**Comment by JiniousChoi** [comment]
@rabbah 
Can I use external Kafka, not the embedded one, when using standalone Openwhisk?

**Comment by chetanmeh** [comment]
> What happens if I run java -jar openwhisk-standalone.jar without '--kafka' switch?

Then OpenWhisk runs in [lean mode][1] (#4216) without Kafka. With `--kafka` it uses [embedded kafka][2]. See #4628 for details on what all was done for this mode. Note that it uses Kafka 2.1.1. So basic stuff works as expected with this Kafka version.

To make standalone connect to existing running Kafka would need some work as current approach was implemented with embedded mode and has to adapt the listeners to workaround the Docker networking. May be try launching Standalone without `--kafka` switch and instead set following system properties

```
-Dwhisk-config.kafka.hosts=localhost:9093 -Dwhisk.spi.MessagingProvider=org.apache.openwhisk.connector.kafka.KafkaMessagingProvider
-Dwhisk.spi.LoadBalancerProvider=org.apache.openwhisk.standalone.KafkaAwareLeanBalancer
```

Change the port as per your setup. I have not tried it so cannot comment if it works as expected!

[1]: https://medium.com/openwhisk/lean-openwhisk-open-source-faas-for-edge-computing-fb823c6bbb9b
[2]: https://github.com/embeddedkafka/embedded-kafka

**Comment by JiniousChoi** [comment]
@chetanmeh 
Thanks for your detailed tips!
I'll look into the #4628 and the system.properties hack.
I'll share the result.

**Comment by JiniousChoi** [comment]
[testSystemBasic.zip](https://github.com/apache/openwhisk/files/4162847/testSystemBasic.zip)

I ran the SystemBasic test against my working system on Vagrant(Ubuntu16.04) with the following command:

> ./gradlew :tests:testSystemBasic -Dwhisk.auth="23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP" -Dwhisk.server=https://localhost -Dopenwhisk.home=\`pwd\`

And I have 2 failed tests.

Is it me doing something wrong? I'd like to know a proper test environment where I can see them all passed, 100%.

Do I need to see all-green in my test result before a PR? Please guide me on the minimum requirement for PR.

**Comment by rabbah** [comment]
There are some tests that are known to [fail sporadically](https://github.com/apache/openwhisk/issues?q=is%3Aopen+is%3Aissue+label%3Aheisenbug). Unless you suspect your change is the reason for the failing tests, I would open the PR and let Travis determine status more thoroughly.

**Comment by JiniousChoi** [comment]
#4802
