### ISSUE TITLE
ERROR: https://alpine.global.ssl.fastly.net/alpine/v3.8/main: could not connect to server (check repositories file) WARNING: Ignoring APKINDEX.3e85023f.tar.gz: No such file or directory

### ISSUE THREAD

**Issue by wangxw001** [apache/openwhisk#4732]
> Task :common:scala:distDocker
Tue Nov 19 23:05:06 CST 2019: Command 'docker build -t scala /home/wxw/openwhisk/common/scala' failed with exitCode 2, 1 retries left, retrying...
Tue Nov 19 23:05:06 CST 2019: Executing 'docker build -t scala /home/wxw/openwhisk/common/scala'

Step 1/11 : FROM adoptopenjdk/openjdk8:x86_64-alpine-jdk8u172-b11
 ---> 78db6b96e4c0
Step 2/11 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 2472807fccb1
Step 3/11 : ENV LANGUAGE en_US:en
 ---> Using cache
 ---> cce2b579ab0e
Step 4/11 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> caa6a54cb096
Step 5/11 : RUN sed -i 's/http\:\/\/dl-cdn.alpinelinux.org/https\:\/\/alpine.global.ssl.fastly.net/g' /etc/apk/repositories
 ---> Using cache
 ---> f8dacd425927
Step 6/11 : RUN apk add --update sed curl bash && apk update && apk upgrade
 ---> Running in 47a27d03f535
fetch https://alpine.global.ssl.fastly.net/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
ERROR: https://alpine.global.ssl.fastly.net/alpine/v3.8/main: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.3e85023f.tar.gz: No such file or directory
fetch https://alpine.global.ssl.fastly.net/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
ERROR: https://alpine.global.ssl.fastly.net/alpine/v3.8/community: could not connect to server (check repositories file)
WARNING: Ignoring APKINDEX.1bff76d9.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  bash (missing):
    required by: world[bash]
  sed (missing):
    required by: world[sed]
The command '/bin/sh -c apk add --update sed curl bash && apk update && apk upgrade' returned a non-zero code: 2

**Comment by style95** [comment]
Hi, @wangxw001 Could you elaborate on the issue more?

**Comment by wangxw001** [comment]
@style95 I am installing OpenWhisk, and when I  input order "sudo ./gradlew distDocker", there is an error at step 6/11. The error is "could not connect to server".
In my opinion, I can open the url"https://alpine.global.ssl.fastly.net/alpine/v3.8/main/x86_64/APKINDEX.tar.gz" and then download it. But in the terminal, we can featch it.

**Comment by wangxw001** [comment]
@style95 I am installing OpenWhisk, and when I input order "sudo ./gradlew distDocker", there is an error at step 6/11. The error is "could not connect to server".
In my opinion, I can open the url"https://alpine.global.ssl.fastly.net/alpine/v3.8/main/x86_64/APKINDEX.tar.gz" and then download it. But in the terminal, we can not featch it and then well failed

**Comment by wangxw001** [comment]
@style95 I am installing OpenWhisk, and when I input order "sudo ./gradlew distDocker", there is an error at step 6/11. The error is "could not connect to server".
In my opinion, I can open the url"https://alpine.global.ssl.fastly.net/alpine/v3.8/main/x86_64/APKINDEX.tar.gz" and then download it. But in the terminal, we can not fetch it and then well failed

**Comment by style95** [comment]
So when you execute each command manually, cannot you access the url inside of the container?
If you can access the url in your host machine but not in your container, I suspect there are some proxy issues or DNS server issues.

Are you running it behind of a proxy or firewall?

**Comment by rabbah** [comment]
@wangxw001 how/did you resolve this issue?
