### ISSUE TITLE
the command "wsk action invoke /whisk.system/utils/echo -p message hello --result" error

### ISSUE THREAD

**Issue by wangxw001** [apache/openwhisk#4757]
When I finished installing openwhsik, I execute the command to verify that openwhisk has failed.
The command is "wsk action invoke /whisk.system/utils/echo -p message hello --result", and the out is "Unable to invoke action 'utils/echo': Post http://172.17.0.1/api/v1/namespaces/whisk.system/actions/utils/echo?blocking=true&result=true: EOF
Run 'wsk --help' for usage.
"
So , I wonder what went wrong?

**Comment by jiangpengcheng** [comment]
it's hard to locate your error from above information, would you please paste your controller's log and invoker's log here?

**Comment by CodingYuanLiu** [comment]
Try "wsk -i action invoke ..."?

**Comment by rabbah** [comment]
Closing as stale/hopefully resolved. Also for rapid help try the community on slack.

**Comment by 0613BTS** [comment]
> When I finished installing openwhsik, I execute the command to verify that openwhisk has failed.
> The command is "wsk action invoke /whisk.system/utils/echo -p message hello --result", and the out is "Unable to invoke action 'utils/echo': Post http://172.17.0.1/api/v1/namespaces/whisk.system/actions/utils/echo?blocking=true&result=true: EOF
> Run 'wsk --help' for usage.
> "
> So , I wonder what went wrong?

I meet the same problem. Have you solved this? What can I do?

**Comment by rabbah** [comment]
@0613BTS I commented on the issue you opened https://github.com/apache/openwhisk/issues/5100#issuecomment-817131960.
