### ISSUE TITLE
Define procedures for a new proposal

### ISSUE THREAD

**Issue by style95** [apache/openwhisk#4776]
As @rabbah mentioned [here](https://cwiki.apache.org/confluence/display/OPENWHISK/2019-12-04+OW+Tech+Interchange+Meeting+Notes), we have many proposals in [OpenWhisk Wiki](https://cwiki.apache.org/confluence/display/OPENWHISK/Proposals).

But we lack the official procedures for them.
While it is ok for small changes, lifecycle management is necessary for large changes.

We need procedures to discuss proposals, evaluate them, make a consensus for the direction, and finally include or drop some of them, etc.

Many renowned projects have their own procedures:

* K8S(KEP): https://github.com/kubernetes/enhancements/tree/master/keps
* Kafka(KIP): https://cwiki.apache.org/confluence/display/KAFKA/Kafka+Improvement+Proposals 

It's clear for users to figure out which proposals are active and will be included in and when.

I will look into their approaches and define our own.

**Comment by rabbah** [comment]
Thanks Dominic for leading this.

**Comment by style95** [comment]
I am looking into KEP first.

# General about KEP

* They run a separate repo for KEP: https://github.com/kubernetes/enhancements
* PM SIG(Product Management Special Interest Group) is in charge of the repo.
  * [SIG List](https://github.com/kubernetes/community/blob/master/sig-list.md)
  * SIG is generally module-based, there are chairs for each SIG.
* There is [a simple guideline](https://github.com/kubernetes/enhancements#is-my-thing-an-enhancement) to differentiate enhancements with the others.
* Generally, enhancements require multiple releases to implement them and it is to track the status of them.
* A enhancement is filed in the repo once there is a consensus at least in one SIG.
* Enhancements are tracked by Github issues. And before creating an issue he is supposed to
  * Share the enhancement via mailing lists, community meetings, or issues in other repos.
  * (optionally) Implement a prototype
  * Identify people who agree to work with (This is because it requires approx. 9mo ~ 1 year to implement.)
  * Be ready to become a project manager for the enhancement.
* There are 3 stages, alpha, beta, stable.
* It is to keep a high standard of integrity and consistency throughout all systems, tests, documentation, and so on.
* They are using labels
  * `sig/foo`: To denote which module is related. (ex: /sig api)
  * `kind/feature`: To denote the issue should be tracked as an enhancement. (/kind feature)
  * `tracked/yes`: To denote the issue is actively tracked in the current milestone.
  * `tracked/no`: To denote the issue is not tracked in the current milestone.
  * `stage/{alpha,beta,stable}`: The stage of the enhancement.

They defined KEP using [KEP-1](https://github.com/kubernetes/enhancements/blob/master/keps/0001-kubernetes-enhancement-proposal-process.md). It includes the details about KEP.
There are also [a template](https://github.com/kubernetes/enhancements/blob/master/keps/YYYYMMDD-kep-template.md) for KEP.

From now on, I will look into KEP-1 and the template for the details.

**Comment by bdelacretaz** [comment]
Considering that the OpenWhisk community is much smaller than Kubernetes I think a very lightweight process might be sufficient.

https://github.com/apache/cordova-discuss is one example of such a lightweight process: basically just a set of proposal documents in a single place, with state annotations like "incoming", "in progress", "completed", "abandoned" or something like that. Those annotations can be Markdown front matter or just a page which lists the proposals like in that example.

Just my 2 cents - I'm not actively involved in OpenWhisk development, but hopefully this helps.

**Comment by style95** [comment]
@bdelacretaz Thak you for comments.
I opened a PR based on KEP, KIP, and Cordova-discuss.

**Comment by rabbah** [comment]
Thanks @style95 the process is now in place.
