### ISSUE TITLE
Feature Request: Allow different Docker Repos and Credentials to pull Docker Images

### ISSUE THREAD

**Issue by ThomasUllrich666** [apache/openwhisk#4787]
Hello I want to use OpenWhisk for a big app in our Company. 
Therefore I need a way to pull the image from our internal Docker Artifactory Repository.

Can you please implement a way that solves this problem?

**Comment by style95** [comment]
@ThomasUllrich666 Do you want to use a consolidated docker registry for all images or multiple registries for each runtime(blackbox) container?

**Comment by ThomasUllrich666** [comment]
If I can choose I would like to have a way to implement multiple registry for different container. 
I think that the best way will be that openwhis change the ~/.docker/config.json in a proper way. Then the user is able to add as many repos as he want.

**Comment by style95** [comment]
ok this is good to have.

In our downstream repo, we added a volume mapping for `~/.docker/` on all invokers.
I logged in to our private registry and give access to all custom docker images for the docker user.
Then users can create actions with custom docker images from a private registry.
Invokers are also able to pull images from a private registry as long as they have access to the registry and the images.
I haven't tried with multiple registries but I think it would work ideally if you login to all registries.

I would open a pull request for this soon.

**Comment by dgrove-oss** [comment]
A related user comment here: https://github.com/apache/openwhisk-deploy-kube/issues/528#issuecomment-567107376

**Comment by acabarbaye** [comment]
Just for verification, does it mean that this statement in the documentation is no longer true ? https://github.com/apache/openwhisk/blob/master/docs/actions-docker.md#usage
> <IMAGE> must be an image name for a public Docker image on Docker Hub.
If so, could the documentation be updated in order to understand how to use/configure a private registry?
Moreover, would it work for images located in a AWS ECS instance?

**Comment by style95** [comment]
@acabarbaye Yes it seems the document should be updated accordingly.

An operator can log-in to a private registry and do volume mapping like this:

```
invoker_docker_volumes:
  - ~/.docker:/root/.docker
```

With regard to images in ECS, I think it would work as long as they are accessible in a same way with the others.
