### ISSUE TITLE
gen untrusted server certificate for host

### ISSUE THREAD

**Issue by luzhang92** [apache/openwhisk#4789]
When I run  ansible-playbook -i environments/local setup.yml

I got the error about:

fatal: [localhost -> localhost]: FAILED! => {"changed": true, "cmd": "\"/home/zl/project/Noah/openwhisk/ansible/files/genssl.sh\" \"*.localhost\" \"server\" \"/home/zl/project/Noah/openwhisk/ansible/roles/nginx/files\"", "delta": "0:00:00.005662", "end": "2020-01-06 15:08:22.220630", "msg": "non-zero return code", "rc": 126, "start": "2020-01-06 15:08:22.214968", "stderr": "/bin/sh: 1: /home/zl/project/Noah/openwhisk/ansible/files/genssl.sh: Permission denied", "stderr_lines": ["/bin/sh: 1: /home/zl/project/Noah/openwhisk/ansible/files/genssl.sh: Permission denied"], "stdout": "", "stdout_lines": []}

[FAILED]
> "/home/zl/project/Noah/openwhisk/ansible/files/genssl.sh" "*.localhost" "server" "/home/zl/project/Noah/openwhisk/ansible/roles/nginx/files"
non-zero return code
/bin/sh: 1: /home/zl/project/Noah/openwhisk/ansible/files/genssl.sh:
Permission denied

How can I fix them

**Comment by rabbah** [comment]
Closing as stale.
