### ISSUE TITLE
Proper promise rejection errors

### ISSUE THREAD

**Issue by HunderlineK** [apache/openwhisk#4809]
Environment: Node

Currently, if the result of a cloud function run is a promise rejection, we get a generic error which can mean multiple different causes. Error messages should be as specific as possible to help debugging.

## Environment details:
IBM Cloud

## Provide the expected results and outputs:
If a promise is rejected, the error type will be specified as such.

## Provide the actual results and outputs:
A generic unexpected error has happened message which is too ambiguous.

**Comment by rabbah** [comment]
hi @HunderlineK - can you provide an example of the `node` function you used?

**Comment by HunderlineK** [comment]
Hi @rabbah. I've tried to find the invocations that had this issue, but in all cases it is possible that the error might have been because we ran out of memory and I tried to produce simple cases where OOM could definitely be excluded as a cause and could not see this issue.

I'm closing the ticket unless I find a solid example, thanks.
