### ISSUE TITLE
> Task :core:standalone:distDocker FAILED

### ISSUE THREAD

**Issue by estimate123** [apache/openwhisk#4821]
liu@ubuntu:~/openwhisk$ ./gradlew distDocker
Sending build context to Docker daemon  9.216kB

Step 1/11 : FROM adoptopenjdk/openjdk8:x86_64-alpine-jdk8u172-b11
 ---> 78db6b96e4c0
Step 2/11 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> f7918d2a4f86
Step 3/11 : ENV LANGUAGE en_US:en
 ---> Using cache
 ---> 9e115e2072dd
Step 4/11 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> f8091fca9d49
Step 5/11 : RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
 ---> Using cache
 ---> 7f0c3f62eb6d
Step 6/11 : RUN apk add --update sed curl bash && apk update && apk upgrade
 ---> Using cache
 ---> 565085b83d5b
Step 7/11 : RUN mkdir /logs
 ---> Using cache
 ---> 66e2792850f3
Step 8/11 : COPY transformEnvironment.sh /
 ---> Using cache
 ---> 3147ecaa660a
Step 9/11 : RUN chmod +x transformEnvironment.sh
 ---> Using cache
 ---> 00f55f6aa0a2
Step 10/11 : COPY copyJMXFiles.sh /
 ---> Using cache
 ---> 20595667c7f7
Step 11/11 : RUN chmod +x copyJMXFiles.sh
 ---> Using cache
 ---> a46f55232d00
Successfully built a46f55232d00
Successfully tagged scala:latest

> Task :common:scala:distDocker
Mon Feb 10 20:57:18 PST 2020: Executing 'docker build -t scala /home/liu/openwhisk/common/scala'
Building 'scala' took 0.491 seconds

> Task :common:scala:tagImage
Mon Feb 10 20:57:18 PST 2020: Executing 'docker tag scala whisk/scala:latest'

> Task :core:controller:distDocker
Mon Feb 10 20:57:23 PST 2020: Executing 'docker build -t controller /home/liu/openwhisk/core/controller'

Sending build context to Docker daemon  103.5MB

Step 1/13 : FROM scala
 ---> a46f55232d00
Step 2/13 : ENV UID=1001     NOT_ROOT_USER=owuser
 ---> Using cache
 ---> 8e073a7e377f
Step 3/13 : ENV SWAGGER_UI_DOWNLOAD_SHA256=3d7ef5ddc59e10f132fe99771498f0f1ba7a2cbfb9585f9863d4191a574c96e7     SWAGGER_UI_VERSION=3.6.0
 ---> Using cache
 ---> b0de48adc833
Step 4/13 : ENV DOCKER_VERSION=18.06.3-ce
 ---> Using cache
 ---> 9b2a12cfd637
Step 5/13 : RUN apk add --update openssl
 ---> Using cache
 ---> b1058042d9dc
Step 6/13 : RUN curl -sSL -o docker-${DOCKER_VERSION}.tgz https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz &&     tar --strip-components 1 -xvzf docker-${DOCKER_VERSION}.tgz -C /usr/bin docker/docker &&     tar --strip-components 1 -xvzf docker-${DOCKER_VERSION}.tgz -C /usr/bin docker/docker-runc &&     rm -f docker-${DOCKER_VERSION}.tgz &&     chmod +x /usr/bin/docker &&     chmod +x /usr/bin/docker-runc
 ---> Using cache
 ---> 650c844ffdf6
Step 7/13 : RUN curl -sSL -o swagger-ui-v${SWAGGER_UI_VERSION}.tar.gz --no-verbose https://github.com/swagger-api/swagger-ui/archive/v${SWAGGER_UI_VERSION}.tar.gz &&     echo "${SWAGGER_UI_DOWNLOAD_SHA256}  swagger-ui-v${SWAGGER_UI_VERSION}.tar.gz" | sha256sum -c - &&     mkdir swagger-ui &&     tar zxf swagger-ui-v${SWAGGER_UI_VERSION}.tar.gz -C /swagger-ui --strip-components=2 swagger-ui-${SWAGGER_UI_VERSION}/dist &&     rm swagger-ui-v${SWAGGER_UI_VERSION}.tar.gz &&     sed -i s#http://petstore.swagger.io/v2/swagger.json#/api/v1/api-docs#g /swagger-ui/index.html
 ---> Using cache
 ---> afd45013c956
Step 8/13 : ADD build/distributions/controller.tar /
 ---> Using cache
 ---> 3b581febbed2
Step 9/13 : COPY init.sh /
 ---> Using cache
 ---> efae4578be1d
Step 10/13 : RUN chmod +x init.sh
 ---> Using cache
 ---> cd2de71a8c2e
Step 11/13 : RUN adduser -D -u ${UID} -h /home/${NOT_ROOT_USER} -s /bin/bash ${NOT_ROOT_USER}
 ---> Using cache
 ---> a45946570e18
Step 12/13 : EXPOSE 8080
 ---> Using cache
 ---> 1b275dea3b7b
Step 13/13 : CMD ["./init.sh", "0"]
 ---> Using cache
 ---> 8c7346d94f33
Successfully built 8c7346d94f33
Successfully tagged controller:latest

> Task :core:controller:distDocker
Building 'controller' took 2.601 seconds

> Task :core:controller:tagImage
Mon Feb 10 20:57:26 PST 2020: Executing 'docker tag controller whisk/controller:latest'
Sending build context to Docker daemon  102.2MB

Step 1/11 : FROM scala
 ---> a46f55232d00
Step 2/11 : ENV UID=1001     NOT_ROOT_USER=owuser
 ---> Using cache
 ---> 8e073a7e377f
Step 3/11 : ENV DOCKER_VERSION=18.06.3-ce
 ---> Using cache
 ---> 2af00bb6eb8e
Step 4/11 : RUN apk add --update openssl
 ---> Using cache
 ---> 50a4024e5477
Step 5/11 : RUN curl -sSL -o docker-${DOCKER_VERSION}.tgz https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz &&     tar --strip-components 1 -xvzf docker-${DOCKER_VERSION}.tgz -C /usr/bin docker/docker &&     tar --strip-components 1 -xvzf docker-${DOCKER_VERSION}.tgz -C /usr/bin docker/docker-runc &&     rm -f docker-${DOCKER_VERSION}.tgz &&     chmod +x /usr/bin/docker &&     chmod +x /usr/bin/docker-runc
 ---> Using cache
 ---> ecddac2d9130
Step 6/11 : ADD build/distributions/invoker.tar ./
 ---> Using cache
 ---> d06f7ad822b7
Step 7/11 : COPY init.sh /
 ---> Using cache
 ---> 3721f4ee896c
Step 8/11 : RUN chmod +x init.sh
 ---> Using cache
 ---> 55ea6503c5e4
Step 9/11 : RUN adduser -D -u ${UID} -h /home/${NOT_ROOT_USER} -s /bin/bash ${NOT_ROOT_USER}
 ---> Using cache
 ---> c50f6b410a4f
Step 10/11 : EXPOSE 8080
 ---> Using cache
 ---> b01e96bcbd49
Step 11/11 : CMD ["./init.sh", "0"]
 ---> Using cache
 ---> e753d0ab0aab
Successfully built e753d0ab0aab
Successfully tagged invoker:latest

> Task :core:invoker:distDocker
Mon Feb 10 20:57:26 PST 2020: Executing 'docker build -t invoker /home/liu/openwhisk/core/invoker'
Building 'invoker' took 2.027 seconds

> Task :core:invoker:tagImage
Mon Feb 10 20:57:28 PST 2020: Executing 'docker tag invoker whisk/invoker:latest'

> Task :core:standalone:distDocker
Mon Feb 10 20:57:41 PST 2020: Executing 'docker build --build-arg OPENWHISK_JAR=build/libs/openwhisk-standalone-1.0.0-SNAPSHOT.jar -t standalone /home/liu/openwhisk/core/standalone'

Sending build context to Docker daemon  181.2MB

Step 1/11 : FROM scala
 ---> a46f55232d00
Step 2/11 : ARG OPENWHISK_JAR
 ---> Using cache
 ---> 522f5f05c387
Step 3/11 : ENV DOCKER_VERSION=18.06.3-ce
 ---> Using cache
 ---> ab550b73be05
Step 4/11 : ENV WSK_VERSION=1.0.0
 ---> Using cache
 ---> 7e61af06da75
Step 5/11 : ADD init /
 ---> Using cache
 ---> 6b9199f19186
Step 6/11 : ADD stop waitready /bin/
 ---> Using cache
 ---> 9a9d51adc63f
Step 7/11 : RUN chmod +x /bin/stop /bin/waitready ;  curl -sL   https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz   | tar xzvf -  -C /usr/bin --strip 1 docker/docker ;  curl -sL   https://github.com/apache/openwhisk-cli/releases/download/${WSK_VERSION}/OpenWhisk_CLI-${WSK_VERSION}-linux-amd64.tgz   | tar xzvf - -C /usr/bin wsk
 ---> Running in f161d971fd4a
docker/docker
wsk

> Task :core:standalone:distDocker
Mon Feb 10 21:11:41 PST 2020: Command 'docker build --build-arg OPENWHISK_JAR=build/libs/openwhisk-standalone-1.0.0-SNAPSHOT.jar -t standalone /home/liu/openwhisk/core/standalone' was killed after 840 seconds, 2 retries left, retrying...
Mon Feb 10 21:11:41 PST 2020: Executing 'docker build --build-arg OPENWHISK_JAR=build/libs/openwhisk-standalone-1.0.0-SNAPSHOT.jar -t standalone /home/liu/openwhisk/core/standalone'

Sending build context to Docker daemon  181.2MB

Step 1/11 : FROM scala
 ---> a46f55232d00
Step 2/11 : ARG OPENWHISK_JAR
 ---> Using cache
 ---> 522f5f05c387
Step 3/11 : ENV DOCKER_VERSION=18.06.3-ce
 ---> Using cache
 ---> ab550b73be05
Step 4/11 : ENV WSK_VERSION=1.0.0
 ---> Using cache
 ---> 7e61af06da75
Step 5/11 : ADD init /
 ---> Using cache
 ---> 6b9199f19186
Step 6/11 : ADD stop waitready /bin/
 ---> Using cache
 ---> 9a9d51adc63f
Step 7/11 : RUN chmod +x /bin/stop /bin/waitready ;  curl -sL   https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz   | tar xzvf -  -C /usr/bin --strip 1 docker/docker ;  curl -sL   https://github.com/apache/openwhisk-cli/releases/download/${WSK_VERSION}/OpenWhisk_CLI-${WSK_VERSION}-linux-amd64.tgz   | tar xzvf - -C /usr/bin wsk
 ---> Running in 361d2dc462c9
docker/docker
wsk

> Task :core:standalone:distDocker
Mon Feb 10 21:25:41 PST 2020: Command 'docker build --build-arg OPENWHISK_JAR=build/libs/openwhisk-standalone-1.0.0-SNAPSHOT.jar -t standalone /home/liu/openwhisk/core/standalone' was killed after 840 seconds, 1 retries left, retrying...
Mon Feb 10 21:25:41 PST 2020: Executing 'docker build --build-arg OPENWHISK_JAR=build/libs/openwhisk-standalone-1.0.0-SNAPSHOT.jar -t standalone /home/liu/openwhisk/core/standalone'

Sending build context to Docker daemon  181.2MB

Step 1/11 : FROM scala
 ---> a46f55232d00
Step 2/11 : ARG OPENWHISK_JAR
 ---> Using cache
 ---> 522f5f05c387
Step 3/11 : ENV DOCKER_VERSION=18.06.3-ce
 ---> Using cache
 ---> ab550b73be05
Step 4/11 : ENV WSK_VERSION=1.0.0
 ---> Using cache
 ---> 7e61af06da75
Step 5/11 : ADD init /
 ---> Using cache
 ---> 6b9199f19186
Step 6/11 : ADD stop waitready /bin/
 ---> Using cache
 ---> 9a9d51adc63f
Step 7/11 : RUN chmod +x /bin/stop /bin/waitready ;  curl -sL   https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz   | tar xzvf -  -C /usr/bin --strip 1 docker/docker ;  curl -sL   https://github.com/apache/openwhisk-cli/releases/download/${WSK_VERSION}/OpenWhisk_CLI-${WSK_VERSION}-linux-amd64.tgz   | tar xzvf - -C /usr/bin wsk
 ---> Running in 5fb0f29d145d
docker/docker

> Task :core:standalone:distDocker FAILED
Mon Feb 10 21:39:42 PST 2020: Command 'docker build --build-arg OPENWHISK_JAR=build/libs/openwhisk-standalone-1.0.0-SNAPSHOT.jar -t standalone /home/liu/openwhisk/core/standalone' was killed after 840 seconds, no more retries left, aborting...

> Task :core:standalone:tagImage
Mon Feb 10 21:39:42 PST 2020: Executing 'docker tag standalone whisk/standalone:latest'

FAILURE: Build failed with an exception.

* Where:
Script '/home/liu/openwhisk/gradle/docker.gradle' line: 155

* What went wrong:
Execution failed for task ':core:standalone:distDocker'.
> Mon Feb 10 21:39:42 PST 2020: Command 'docker build --build-arg OPENWHISK_JAR=build/libs/openwhisk-standalone-1.0.0-SNAPSHOT.jar -t standalone /home/liu/openwhisk/core/standalone' was killed after 840 seconds

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42m 30s
32 actionable tasks: 13 executed, 19 up-to-date

1.My problem is Task :core:standalone:distDocker FAILED, could someone tell me how to fix it?

**Comment by estimate123** [comment]
I try to setup my ubuntu for the openwhisk, it always stuck here when I run the comman ./gradlew distDocker

**Comment by zhanghuanhao** [comment]
same，ubuntu18.04

**Comment by zhanghuanhao** [comment]
try ` --info` to get more information

**Comment by sciabarra** [comment]
Just tried and built successfully so definitely it looks like a dependency problem. The standalone embeds a javascript application (the playground) so npm is required.
