### ISSUE TITLE
remove dependencies on nodejs:6 runtime kind

### ISSUE THREAD

**Issue by dgrove-oss** [apache/openwhisk#4829]
NodeJS 6 is long past EOL.  We've long since deprecated the nodejs:6 runtime kind.

We need to remove all dependencies throughout the entire system on the nodejs:6 runtime kind, then remove it from the runtime manifest.

Some known lingering uses:
+ https://github.com/apache/openwhisk-package-kafka/issues/367
+ https://github.com/apache/openwhisk-package-cloudant/issues/222
+ https://github.com/apache/openwhisk-wskdeploy/pull/1089

**Comment by emishas** [comment]
@dgrove-oss 
there is a dependancy in openwhisk-composer
https://github.com/apache/openwhisk-composer/blob/1e1297eb9e8119854b35ebb0b0630f7f8aee39c6/travis/runtimes.json#L14

**Comment by dgrove-oss** [comment]
Thanks @emishas -- will take a look

**Comment by dgrove-oss** [comment]
submitted https://github.com/apache/openwhisk-composer/pull/72 for composer; waiting to see what travis thinks :)

**Comment by emishas** [comment]
@dgrove-oss there are also dependancies inside packages, i.e.:

Alarms package was updated
https://github.com/apache/openwhisk-package-alarms/commit/a2e108e3537b6015f4e437ed43a9450eef90fa2e

but Kafka not:
https://github.com/apache/openwhisk-package-kafka/search?q=nodejs&unscoped_q=nodejs

Haven't checked the rest.

**Comment by rabbah** [comment]
We've dropped node 6 now.
