### ISSUE TITLE
Race Condition with Activation Completion Ack Back to Controller and Activation Write to Couchdb?

### ISSUE THREAD

**Issue by bdoyle0182** [apache/openwhisk#4842]
I might just be misunderstanding the code base here, but my understanding is that in ContainerProxy; the ack that is sent back to the controller on `completed*` that is used by the Controller to mark the activation as successful is done concurrently with the activation write to couchdb. Specifically the `sendActiveAck` and `storeActivation` functions respectively. Does this cause a race condition where the the `sendActiveAck` that produces the message to `completed*` could complete and then the invoker dies before the activation is written to couchdb and thus the activation is never persisted? I assume this is either intentional or I have some misunderstanding. 

Our system listens on the `completed*` topics to know when the activations are finished, but it would be a problem for us if something could theoretically be put on the `completed*` topic and then potentially never get persisted because an invoker goes down or is restarted in that small window. It seems like the new approach with ActivationPersisterService #4632 would solve the problem at least for our use case because we could listen on the new `activations` topic for a notification on when an activation is completed or the `completed-others*` (I'm not sure which one applies) because whatever that topic is now directly feeds the writes to the primary persistence storage so it would be guaranteed to eventually make it there.

Also a note on the ActivationPersisterService, a very big fan of anything that lets us control / configure / limit load on couchdb :)

**Comment by rabbah** [comment]
This is by design - it's possible for an activation record to be "lost" in that it may not be recorded in the activation store but its results are externally observable (either via request/response, a continuation or a sequence). This is an area where the semantics and implementation could be improved.

The design partly stems from the at most once activation model, and only recording the activation metadata once after completion. The active ack is the fast pass and is sent ahead of log collection. The activation metadata waits for the logs to be drained (which can delay the write back noticeably).

**Comment by rabbah** [comment]
I was remiss not to say welcome Brendan - looks like this is your first issue for apache/openwhisk. 

BTW did you also look at the elastic store PR #3977 which routes activations to ELK instead of Couch?

**Comment by bdoyle0182** [comment]
> This is by design - it's possible for an activation record to be "lost" in that it may not be recorded in the activation store but its results are externally observable (either via request/response, a continuation or a sequence). This is an area where the semantics and implementation could be improved.
> 
> The design partly stems from the at most once activation model, and only recording the activation metadata once after completion. The active ack is the fast pass and is sent ahead of log collection. The activation metadata waits for the logs to be drained (which can delay the write back noticeably).

Thanks for the answer, I figured this was probably the case. Our use case for openwhisk is entirely non-blocking activations so we rely on getting the result from the activation store. Well we hit the quark controller http endpoint for the activation with the activationId which gets it from couchdb (assuming it's not cached). When you say request/response, do you mean it's results are guaranteed externally observable for blocking activations? In the event that the activation record is lost and all of the controllers are restarted, there's never a way to get information on that activation again right?

Also yes, I did see the elasticsearch pull request for activations. We are actually interested in moving activations off couchdb, but not necessarily to elasticsearch. It's great to know that swapping out activation stores is now going to be supported though. What is your opinion on us implementing an object store (i.e. s3) `ActivationStore` for activations? The other db we would be considering moving activations to is mongo. Curious on your thoughts
