### ISSUE TITLE
Cannot find module Error

### ISSUE THREAD

**Issue by beraybentesen** [apache/openwhisk#4866]
After successfully deploying with zip file receiving this when I invoke action :

 "error": "Error: Cannot find module '/nodejsAction/nrx2Fj84'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:508:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at eval (eval at <anonymous> (/nodejsAction/runner.js:55:49), <anonymous>:1:1)\n    at /nodejsAction/runner.js:55:49\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
}

**Comment by rabbah** [comment]
hi @beraybentesen - this isn't very helpful/actionable. Usually this error means your function isn't package properly (your zip file is empty or missing index.js, package.json or similar). You'll need to share more details so someone can help you.

**Comment by beraybentesen** [comment]
@rabbah You're right. I fixed with the correct configuration. And quick question, is there a way to update action without uploading zip again ? Let's say you just need to update the code itself instead of dependencies etc.

**Comment by rabbah** [comment]
currently there is only one zip file which contains the code and dependencies.
