### ISSUE TITLE
add documentation for typescript function runtime and update runtimes

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk#4872]
The typescript runtime was recently added to openwhisk but we do not yet have docs for the runtime and it is missing from runtimes.json.

We need a doc like https://github.com/apache/incubator-openwhisk/blob/master/docs/actions-nodejs.md for typescript functions.

Adding the runtime to the runtime manifest can be done per https://github.com/apache/openwhisk/blob/master/docs/actions-new.md#the-runtimes-manifest.

**Comment by Rurouni-Jiaxin** [comment]
@rabbah Please assign this to me. Much obliged 🙏

**Comment by Rurouni-Jiaxin** [comment]
@rabbah The typescript runtime seems deprecated, I cannot find the typescript counterpart as https://github.com/apache/openwhisk-runtime-nodejs

**Comment by IamPreethi-S** [comment]
Hey, would like to know if this issue is resolved?.
If not, I would like to take it up and contribute.
Thanks:)

**Comment by Rurouni-Jiaxin** [comment]
> Hey, would like to know if this issue is resolved?. If not, I would like to take it up and contribute. Thanks:)

Hi, I have a PR https://github.com/apache/openwhisk-runtime-nodejs/pull/227 that is still waiting for review. It's for JavaScript though. If a documentation were needed for TypeScript, I am not sure where to add that. As far as I know, there seems to be only one single Node runtime:  https://github.com/apache/openwhisk-runtime-nodejs

**Comment by rabbah** [comment]
Typescript (ts) functions get compiled and run as node functions - there is some support to ship ts code as the action code and the action will compile it before it runs it (at init time). This will create a longer cold start. It's a nice feature for getting started but for production, the code should get compiled ahead of time rather than at runtime. As such we should close this issue as wont fix.
