### ISSUE TITLE
There was an SSL error when I deployed the environment

### ISSUE THREAD

**Issue by wangxw001** [apache/openwhisk#4886]
I execution instruction "ansible-playbook -i environments/local openwhisk.yml"
And  when to execute the task ——“TASK [cli : Download release archive to build directory ...] ”，
there is an SSLError ——“ An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SSLError: ('The read operation timed out',)”

the details are as follows.

TASK [cli : Download release archive to build directory ...] ***********************************************************************************************************
Friday 17 April 2020  13:43:15 +0800 (0:00:00.261)       0:04:01.627 ********** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SSLError: ('The read operation timed out',)
fatal: [172.17.0.1]: FAILED! => {"changed": false, "msg": "failed to create temporary content file: ('The read operation timed out',)"}

failed to create temporary content file: ('The read operation timed
out',)

PLAY RECAP *************************************************************************************************************************************************************
172.17.0.1                 : ok=11   changed=2    unreachable=0    failed=1   
controller0                : ok=26   changed=3    unreachable=0    failed=0   
invoker0                   : ok=29   changed=7    unreachable=0    failed=0   
kafka0                     : ok=10   changed=4    unreachable=0    failed=0   

Friday 17 April 2020  13:48:47 +0800 (0:05:31.380)       0:09:33.008 **********

**Comment by rabbah** [comment]
The logs show
  > The read operation timed out

This might indicate the `nginx` container failed to start up or crashed. Check `docker ps` output to see which containers are up. How did you deploy your stack?
