### ISSUE TITLE
Monitoring OpenWhisk metrics tool

### ISSUE THREAD

**Issue by pankaj-dahiya** [apache/openwhisk#4889]
Is these any paid/open-source tool available to monitor openwhisk ?

https://github.com/apache/openwhisk/blob/master/docs/metrics.md

This points out towards a repo which is 3 year year old, not at all working (obviously) and no one is maintaining that repo!

Also, when we make a change into "group_vars/all" how will it be communicated to the running cluster? (I am running openwhisk locally via docker-compose)
Edited : Why can't we add our statsd server in environment file (docker-whisk-controller.env) and if it is possible to add via environment variable, why this option is not mentioned in any of the docs!

**Comment by rabbah** [comment]
Sorry @pankaj-dahiya didn't see this earlier - Depends on what you want to monitor. We use Datadog in our production cluster.
