### ISSUE TITLE
Standalone Server API Gateway creates unconfigurable and open Redis instance

### ISSUE THREAD

**Issue by aFuerst** [apache/openwhisk#4904]
## Environment details:

* standalone deployment, native ubuntu
* Docker version 18.09.2, build 6247962
* Description:    Ubuntu 16.04.5 LTS

## Steps to reproduce the issue:

1.   Build standalone server `./gradlew :core:standalone:build`
2.   Run with API gateway `java -jar ./bin/openwhisk-standalone.jar --api-gw --api-gw-port 4569`
3.   Notice a Redis docker instance is created

## Provide the expected results and outputs:
Custom configuration overriding [`standalone.conf` redis settings](https://github.com/apache/openwhisk/blob/master/core/standalone/src/main/resources/standalone.conf#L92) allows mounting custom `redis.conf` to the container, changing the docker host port, or just a setting password on Redis

## Provide the actual results and outputs:
[API GW uses default Redis port and provides no way to override it or redis any config](https://github.com/apache/openwhisk/blob/master/core/standalone/src/main/scala/org/apache/openwhisk/standalone/ApiGwLauncher.scala#L57)

## Additional information you deem important:
* This open Redis is a security vulnerability

**Comment by chetanmeh** [comment]
Standalone mode is recommended only for local development and not production uses. Does the redis bounds to all interfaces in your case or it is only bound to localhost

**Comment by aFuerst** [comment]
I am using it for local development but it's running on an internet-facing server. 

Per the redis docker info the server launched has no security and is accessible from non-localhost sources. https://hub.docker.com/_/redis/

**Comment by rabbah** [comment]
Setting a password on the redis server would be a good enhancement. @aFuerst would you be interested in contributing a pull request?

**Comment by aFuerst** [comment]
@rabbah I would if I had the time, which wouldn't be for several more months at least

**Comment by rabbah** [comment]
Thanks @aFuerst - I am interested in doing this so one of us will get to it.
