### ISSUE TITLE
Could action timeout limit be unlimited or configurable?

### ISSUE THREAD

**Issue by acabarbaye** [apache/openwhisk#4907]
Documentation states that the maximum time limit for an action is 5 minutes (300000ms) https://github.com/apache/openwhisk/blob/master/docs/reference.md#per-action-timeout-ms-default-60s
Could this value be unlimited or configurable as some actions (e.g. extensive calculations, network bound actions) may take much longer than 5 minutes?

**Comment by style95** [comment]
@acabarbaye It is a cluster-wide configuration.
You can change this value.
https://github.com/apache/openwhisk/blob/master/common/scala/src/main/resources/application.conf#L393

**Comment by acabarbaye** [comment]
@style95 : Thanks for the link. I got misled by the documentation. I thought only default values could be modified. Maybe a link to the application.conf should be added to that page as well.

**Comment by Jyuqi** [comment]
@style95 : I change this value to 10 mins, and my action works perfectly. But when I change this to 60 mins or more, the action never returns even after timeout. What should I do if I need the action to run several hours?

**Comment by Jyuqi** [comment]
@style95 : I've tried to change this value to 20 mins. From log I see my action suddenly stops after 5 mins limit and returns error after 20 minutes. But when I change this to 60 mins or more, the action never returns even after timeout. What should I do if I need the action to run several hours?

**Comment by Jyuqi** [comment]
![Screen Shot 2020-07-01 at 13 14 31](https://user-images.githubusercontent.com/48507550/86273296-04530d00-bb9e-11ea-95e9-af77857cae68.png)

**Comment by Jyuqi** [comment]
@style95 : I've tried to change this value to 500 mins. Now my action can run within 500 mins. I set the timeout to 10 mins, 20 mins, 60 mins and 500 mins.  From activation log I see 10 mins works fine. For 20 mins, my action suddenly stops after 3 mins limit and returns error after 20 minutes. For 60 mins, the action stops after 15 mins returns after 124 mins. For 500 mins, my action didn't return after 20h. What should I do if I need the action to run several hours? 
![Screen Shot 2020-07-01 at 13 14 31](https://user-images.githubusercontent.com/48507550/86273380-2c427080-bb9e-11ea-9261-3089a48361e8.png)

**Comment by rabbah** [comment]
Have you checked the logs in the action or the invoker? This is impossible for us to diagnose with the information provided. It could be your action is running out of memory or just crashing, among other reasons.

**Comment by rabbah** [comment]
Closing as inactionable.

**Comment by ZinuoCai** [comment]
I see that here is also a time-limit configuration. What is the difference between them? I deploy OpenWhisk with K8s.

https://github.com/apache/openwhisk/blob/625fc5b7593360bc01e74147c02ce5f1461b5cd3/core/invoker/src/main/resources/application.conf#L68

**Comment by ZinuoCai** [comment]
I also want to extend the running time of a function. I deploy my OpenWHisk with K8s. I change the application.conf in the scala directory and rebuild the controller image. I set it below.

    time-limit {
        min = 100 ms
        max = 25 m
        std = 20 m
    }

However, it does not work properly. The default running is still 1 minute. Anything else should I modify?

**Comment by style95** [comment]
I think you want to change this.
https://github.com/apache/openwhisk-deploy-kube/blob/master/helm/openwhisk/values.yaml#L78

Regarding kubernetes timeouts, they are applied when you run a pod or get logs from a pod.
https://github.com/apache/openwhisk/blob/master/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala#L177

**Comment by rabbah** [comment]
There are the timeouts that you set on individual actions (e.g., `wsk action update --timeout`) which can range from the deployment's `min-max` values. These apply per action.
