### ISSUE TITLE
Why does staggered execution of functions cause cold starts?

### ISSUE THREAD

**Issue by wangxw001** [apache/openwhisk#4925]
I deployed OpenWhisk on a single host. When I call both functions continuously at the same time,  cold start occurs. So why does staggered execution of functions cause cold starts?
![image](https://user-images.githubusercontent.com/48479042/85093833-dc6bbd00-b21f-11ea-99cb-68a7824bc35c.png)

**Comment by style95** [comment]
It depends on your local configuration.
How many memory did you configure for an invoker and in which interval did you invoke each action?

**Comment by rabbah** [comment]
The current heuristics are such that as you saturate some worker nodes, you get new worker nodes, which leads to some cold starts. To answer this question with more detail, you'd need to share your configuration and test setup.
