### ISSUE TITLE
Executing openwhisk action using remote docker container (docker hub)

### ISSUE THREAD

**Issue by Nivekiba** [apache/openwhisk#4926]
## Environment details:

* local deployment, native ubuntu, Mac OS, Kubernetes, ...
* version of docker, ubuntu, ...

## Steps to reproduce the issue:

1.   create an openwhisk action using `--docker <user_name>/python3action:boto3` where boto3 is the tag containing the `boto3` python library
2.   try to execute the action

## Provide the expected results and outputs:

``` a JSON result or an action developer error
```

## Provide the actual results and outputs:

![image](https://user-images.githubusercontent.com/20845649/85586258-0dddf180-b641-11ea-888b-2fe97a5110f1.png)

## Additional information you deem important:
* issue happens only occasionally or and i don't know what are the circumstances

**Comment by rabbah** [comment]
I tried to docker pull your image `nivekiba/python3action:boto3` and failed. OpenWhisk will also try to pull this docker image. If it's not on docker hub, it would explain the reason for the failure. To use an image that is only available locally tag it as `whisk/...` instead. You can check the reason for the failure by inspecting the invoker logs using the `x-request-id` in the API response or the activation id for your failed activation.

**Comment by Nivekiba** [comment]
so it is a docker hub problem ? because sometimes i can pull that image et sometimes not

**Comment by Nivekiba** [comment]
Ok thanks to have noticed me that the pull... after verification, that docker image doesn't even exist on my repository.
