### ISSUE TITLE
Openwhisk show no packages were installed on both guest as well as whisk system.

### ISSUE THREAD

**Issue by sathish95** [apache/openwhisk#4931]
can anyone please tell me how to install whisk package like alarm, slack, kafka etc in windows machine. I started openwhisk using below command java -jar openwhisk-standalone.jar --all --data-dir D:\whisk -v.

everything started correctly and working fine, but could not find any whisk packages. could any one let me know how to install those packages in windows machine locally.

**Comment by rabbah** [comment]
It would be convenient to add an option to standalone openwhisk ton install the action catalogs. To install the packages, you can follow the instructions from [the samples catalog](https://github.com/apache/openwhisk-catalog).

```
git clone https://github.com/apache/openwhisk-catalog.git
cd openwhisk-catalog
./packages/installCatalogUsingWskdeploy.sh 789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP http://localhost:3233
```

If you want to run the alarms or kafka service provider, there is more setup required as those have to startup microservices (in additional containers) to run the feed providers. These are also not part of the standalone bring up process at this point.

Contributions are welcomed.

**Comment by sathish95** [comment]
Thanks for your response. Openwhisk Kubernetes deploy servered my requirements.
