### ISSUE TITLE
Failed to pass "ensure controller files directory exists"

### ISSUE THREAD

**Issue by samanta-amit** [apache/openwhisk#4945]
Getting error for "ansible-playbook prereq.yml"

TASK [ensure controller files directory exists] ********************************
Monday 17 August 2020  20:51:20 +0000 (0:00:00.076)       0:00:09.423 ********* 
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'controller.protocol == 'https'' failed. The error was: An unhandled exception occurred while templating '{u'protocol': u\"{{ controller_protocol | default('https') }}\", u'extraEnv': u'{{ controller_extraEnv | default({}) }}', u'dir': {u'become': u'{{ controller_dir_become | default(false) }}'}, u'ssl': {u'keystore': {u'password': u'openwhisk', u'name': u'{{ __controller_ssl_keyPrefix }}openwhisk-keystore.p12'}, u'cert': u'{{ __controller_ssl_keyPrefix }}openwhisk-server-cert.pem', u'cn': u'openwhisk-controllers', u'key': u'{{ __controller_ssl_keyPrefix }}openwhisk-server-key.pem', u'keyPrefix': u'{{ __controller_ssl_keyPrefix }}', u'clientAuth': u\"{{ controller_client_auth | default('true') }}\", u'storeFlavor': u'PKCS12'}, u'heap': u\"{{ controller_heap | default('2g') }}\", u'managedFraction': u'{{ controller_managed_fraction | default(1.0 - (controller_blackbox_fraction | default(__controller_blackbox_fraction))) }}', u'entitlement': {u'spi': u\"{{ controller_entitlement_spi | default('') }}\"}, u'instances': u\"{{ groups['controllers'] | length }}\", u'loglevel': u\"{{ controller_loglevel | default(whisk_loglevel) | default('INFO') }}\", u'timeoutFactor': u'{{ controller_timeout_factor | default(2) }}', u'blackboxFraction': u'{{ controller_blackbox_fraction | default(__controller_blackbox_fraction) }}', u'confdir': u'{{ config_root_dir }}/controller', u'authentication': {u'spi': u\"{{ controller_authentication_spi | default('') }}\"}, u'arguments': u\"{{ controller_arguments | default('') }}\", u'timeoutAddon': u\"{{ controller_timeout_addon | default('1 m') }}\", u'basePort': 10001, u'akka': {u'cluster': {u'bindPort': 2551, u'basePort': 8000, u'host': u\"{{ groups['controllers'] | map('extract', hostvars, 'ansible_host') | list }}\", u'seedNodes': u\"{{ groups['controllers'] | map('extract', hostvars, 'ansible_host') | list }}\"}, u'provider': u'cluster'}, u'loadbalancer': {u'spi': u\"{{ controller_loadbalancer_spi | default('') }}\"}}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'ini'. Error was a <class 'ConfigParser.NoSectionError'>, original message: No section: u'controller'\n\nThe error appears to have been in '/home/amit/openwhisk/ansible/setup.yml': line 89, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  # Generate Controller certificates\n  - name: ensure controller files directory exists\n    ^ here\n"}

The conditional check 'controller.protocol == 'https'' failed. The error
was: An unhandled exception occurred while templating '{u'protocol': u"{{
controller_protocol | default('https') }}", u'extraEnv': u'{{
controller_extraEnv | default({}) }}', u'dir': {u'become': u'{{
controller_dir_become | default(false) }}'}, u'ssl': {u'keystore': {u'password':
u'openwhisk', u'name': u'{{ __controller_ssl_keyPrefix }}openwhisk-
keystore.p12'}, u'cert': u'{{ __controller_ssl_keyPrefix }}openwhisk-server-
cert.pem', u'cn': u'openwhisk-controllers', u'key': u'{{
__controller_ssl_keyPrefix }}openwhisk-server-key.pem', u'keyPrefix': u'{{
__controller_ssl_keyPrefix }}', u'clientAuth': u"{{ controller_client_auth |
default('true') }}", u'storeFlavor': u'PKCS12'}, u'heap': u"{{ controller_heap |
default('2g') }}", u'managedFraction': u'{{ controller_managed_fraction |
default(1.0 - (controller_blackbox_fraction |
default(__controller_blackbox_fraction))) }}', u'entitlement': {u'spi': u"{{
controller_entitlement_spi | default('') }}"}, u'instances': u"{{
groups['controllers'] | length }}", u'loglevel': u"{{ controller_loglevel |
default(whisk_loglevel) | default('INFO') }}", u'timeoutFactor': u'{{
controller_timeout_factor | default(2) }}', u'blackboxFraction': u'{{
controller_blackbox_fraction | default(__controller_blackbox_fraction) }}',
u'confdir': u'{{ config_root_dir }}/controller', u'authentication': {u'spi':
u"{{ controller_authentication_spi | default('') }}"}, u'arguments': u"{{
controller_arguments | default('') }}", u'timeoutAddon': u"{{
controller_timeout_addon | default('1 m') }}", u'basePort': 10001, u'akka':
{u'cluster': {u'bindPort': 2551, u'basePort': 8000, u'host': u"{{
groups['controllers'] | map('extract', hostvars, 'ansible_host') | list }}",
u'seedNodes': u"{{ groups['controllers'] | map('extract', hostvars,
'ansible_host') | list }}"}, u'provider': u'cluster'}, u'loadbalancer': {u'spi':
u"{{ controller_loadbalancer_spi | default('') }}"}}'. Error was a <class
'ansible.errors.AnsibleError'>, original message: An unhandled exception
occurred while running the lookup plugin 'ini'. Error was a <class
'ConfigParser.NoSectionError'>, original message: No section: u'controller'  The
error appears to have been in '/home/amit/openwhisk/ansible/setup.yml': line 89,
column 5, but may be elsewhere in the file depending on the exact syntax
problem.  The offending line appears to be:    # Generate Controller
certificates   - name: ensure controller files directory exists     ^ here 

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=1

**Comment by style95** [comment]
@samanta-amit 
Could you share the details about the issue and how to reproduce it?

**Comment by samanta-amit** [comment]
I was trying to build OpenWhisk on Ubuntu 18.04. So after installing docker and all the prerequisites following "/all.sh" script.
Then, I configured the CouchDB database parameters, then I ran "ansible-playbook setup.yml

But, I am getting aforementioned error that it failed to "ensure controller files directory exists". 

![Screenshot from 2020-08-18 17-05-50](https://user-images.githubusercontent.com/17064188/90543705-9a0a2200-e175-11ea-9c60-a34211a6b484.png)
![Screenshot from 2020-08-18 17-06-02](https://user-images.githubusercontent.com/17064188/90543714-9d051280-e175-11ea-84d2-f6695d081bae.png)

**Comment by samanta-amit** [comment]
I was trying to build OpenWhisk on Ubuntu 18.04. So after installing docker and all the prerequisites following "/all.sh" script.
Then, I configured the CouchDB database parameters, then I ran "ansible-playbook setup.yml

But, I am getting aforementioned error that it failed to "ensure controller files directory exists".

![Screenshot from 2020-08-18 17-05-50](https://user-images.githubusercontent.com/17064188/90543771-b27a3c80-e175-11ea-98db-3a8fb93619bf.jpg)
![Screenshot from 2020-08-18 17-06-02](https://user-images.githubusercontent.com/17064188/90543780-b5752d00-e175-11ea-961f-8ad94fd085bf.jpg)

**Comment by style95** [comment]
Could you share your python and ansible version as well?

**Comment by samanta-amit** [comment]
ansible 2.5.2 and Python 2.7.17

**Comment by style95** [comment]
Thank you for sharing.

Hm.. that ansible task is just to ensure the directory for the controller certificates.
Since it does nothing but check the existence and create it if not exist, I feel there would be no issue in most cases.

Also it is seemingly the ansible task issue but it also says about the missing section for `controller` and the offending line.
![image](https://user-images.githubusercontent.com/3447251/90705442-e49eb200-e2cd-11ea-9160-d8a22160c392.png)
If you didn't touch any configuration, there will be the section.

I observed a similar issue when I used a different version of Ansible or Python, so I asked them.

Could you check once if `controller` section and `controller.protocol` configuration exist in `ansible/group_vars/all`?

**Comment by rabbah** [comment]
@style95 i couldn't reproduce this simply by changing the controller protocol :/
my ansible version is 2.7.7

**Comment by samanta-amit** [comment]
Yes, the controller section exists. Without it also, I can build the OpenWhisk. But, I am facing another problem related to invoking a "hello" message following the command "wsk action invoke /whisk.system/utils/echo -p message hello --result".

error: Unable to invoke action 'utils/echo': Post https://172.17.0.1/api/v1/namespaces/whisk.system/actions/utils/echo?blocking=true&result=true: dial tcp 172.17.0.1:443: getsockopt: connection refused.

Do you have any idea about this error?

**Comment by style95** [comment]
@rabbah 
When I faced the similar issue, I used older ansible than 2.5.2.
And that was because the ansible syntax had changed.


@samanta-amit 
So the above controller directory issue is resolved?

Regarding the connection refused, need to check a couple of things.

1. Haven't you faced any error or issue during all ansible tasks?
2. Are Nginx and Controller containers running?
3. Could you access the controller directly with the controller IP/port?

**Comment by samanta-amit** [comment]
Thanks for replying. I am really sorry for pestering you will all the questions. 

No, the controller directory issue is there. But, with that issue also, I can build Openwhisk. 

About the connection issue, I checked the things you asked.

1. I did not face any error during all the listed ansible tasks, only one aforementioned error.
2. Both Nginx and Container are running.
3. I do not know,  how to check it? Would you please elaborate on this a little?

**Comment by samanta-amit** [comment]
In addition to that, I tried to enable the Docker API following the instructions in
https://www.ivankrizsan.se/2016/05/18/enabling-docker-remote-api-on-ubuntu-16-04/

**Comment by samanta-amit** [comment]
Sorry, I did not meant to close this issue. I put this wrongly. Please ignore it.

**Comment by style95** [comment]
Then I suspect your controller is not running well because of the above issue.
If you don't need to secure the connection between nginx and controller, I suggest changing controller protocol to `http` as @rabbah mentioned above.

You can add this line to `environments/local/group_vars/all` or your environment configuration.
```
controller_protocol: http
```

Regarding the direct access to a controller, you can check the controller port using `docker ps`.

```
$ docker ps
CONTAINER ID        IMAGE                                                      COMMAND                  CREATED             STATUS              PORTS                                                                                                 NAMES
4b01049c888d        whisk/controller:latest   "/bin/sh -c 'exec /i…"   44 hours ago        Up 44 hours         0.0.0.0:15000->15000/tcp, 0.0.0.0:16000->16000/tcp, 0.0.0.0:8000->2551/tcp, 0.0.0.0:10001->8080/tcp   controller0
```

You can access to `http://localhost:10001/ping` and the controller would return just `pong`.

```
$ curl http://localhost:10001/ping
pong
```

You can also check whether your controller is running well or not via logs.
The default location of the logs is `/tmp/wsklogs/controller0/`.

Even you can configure your wsk cli to directly connect to the controller as well.

```
$ wsk property set --apihost http://localhost:10001
```

In this case, the cli will directly communicate with a controller. So the Nginx would do nothing here.

BTW, did you just clone the openwhisk repo and use it or change anything?
You anyway would need to solve the controller directory issue so I want to make sure the codes are intact.

**Comment by rabbah** [comment]
For the avoidance of doubt - did you try the "quickstart" which runs a standalone openwhisk stack as a Java process?  It is simpler to install and get running which may be less prone to the errors you're encountering.

```
cd openwhisk
./gradlew core:standalone:bootRun
```

See https://github.com/apache/openwhisk#quick-start.

**Comment by samanta-amit** [comment]
@rabbah I tried to do that, but the building is stuck at "96% EXECUTING". Will try to do it from scratch again and get back to you.

@style95 I tried to add this "controller_protocol: http", but still the error is there. May be, I will try to build it again and come back to you.

**Comment by rabbah** [comment]
That's expected - the Java process remains the foreground. If you run the `wsk` init command at the start you can start using openwhisk.

**Comment by samanta-amit** [comment]
@rabbah I configured wsk by the following command.

wsk property set \
  --apihost 'http://localhost:3233' \
  --auth '23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP'

Then, I rebuild OpenWhisk again. But, still, it stuck at "96% EXECUTING". Do I need to do anything else?

**Comment by samanta-amit** [comment]
@rabbah This is the executing state, it is going on for more than 1.30 hour. It seems like in a loop and checking the things again and again. Is there anything wrong in it or is this the correct way?

![Screenshot from 2020-08-20 21-33-40](https://user-images.githubusercontent.com/17064188/90850618-6bd04200-e32f-11ea-90f7-df7b6a380fe9.jpg)

**Comment by rabbah** [comment]
It's not stuck. Maybe "building is misleading". What you're seeing are the server logs. Run a wsk command from another terminal like `wsk action list` and you'll see logs scroll buy.

**Comment by samanta-amit** [comment]
Thanks. After doing "wsk action list", I am getting this error. 

error: Unable to obtain the list of actions for namespace 'default': Get http://localhost:3232/api/v1/namespaces/_/actions?limit=30&skip=0: dial tcp 127.0.0.1:3232: getsockopt: connection refused
