### ISSUE TITLE
No Invokers Available

### ISSUE THREAD

**Issue by ShubhamGupta9582** [apache/openwhisk#4948]
Hi guys,
I am invoking 50-60 actions per minute that is working fine for some times (around 1-2 hr) but after some times most of the actions start to fail. If i check log with activation id it shows **The server is currently unavailable (because it is overloaded or down for maintenance)**. and when i check controller logs it shows **no Invokers available**.

and now if i execute **wsk -i api list** it gives **error: Unable to obtain the API list: Request accepted, but processing not completed yet** and even if i invoke any action using gateway api it gives same error the request accepted but processing not completed yet.

I am using openwhisk-devtools. So, the limits are already high.
I have already increased **CONFIG_whisk_containerPool_userMemory to 40GB** in docker-whisk-controller.env file.

Currently I have only one invoker but i tried to increase invoker using **INVOKER_INSTANCES** property in docker-whisk-controller.env file but that didn't work. because in make file it is simply doing docker-compose up and there is only one invoker service in docker-compose.yml thats why the invokers had not increased.

**Comment by rabbah** [comment]
Usually this message means you tripped the internal circuit breaker which detect an overload situtation. The limits for the deployment should be checked (they're low by default). If those are already high, inspect the logs and check for error messages in the controller.
