### ISSUE TITLE
Is there any way to increase request size limit while running in standalone?

### ISSUE THREAD

**Issue by Shariar076** [apache/openwhisk#4965]
## Environment details:

* local deployment, commit: ef33823a1d22179133999f7cd628202cd0498a5a
* ubuntu-18.04.1

## Steps to reproduce the issue:

1.   virtualenv -p python3 virtualenv
2.   source virtualenv/bin/activate
3.   pip install pyjokes
4.  zip -r jokes.zip virtualenv __main__.py
5.  wsk action create jokes --kind python:3 --main joke jokes.zip

## Provide the expected results and outputs:

```
ok: created action helloPython
```

## Provide the actual results and outputs:
Client-end:
```
error: Unable to create action 'jokes': The connection failed, or timed out. (HTTP status code 500)
```
Server-end:
```
'Request too large: Request of size 91630348 was longer than the maximum of 52428800'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler
```

## Additional information you deem important:
*  The zipped python package is sized 66MB with only one python package `pyjokes`.
*  Is there a way to increase/bypass the request-limit? As you see, the packages including a `virtualenv` can be quite larger than the 50MB limit.

**Comment by style95** [comment]
I think you many find this useful.

* Akka HTTP: https://github.com/apache/openwhisk/blob/master/common/scala/src/main/resources/application.conf#L21

**Comment by Shariar076** [comment]
Thanks @style95 . It works now
