### ISSUE TITLE
where is the config file

### ISSUE THREAD

**Issue by ZYH1120** [apache/openwhisk#4980]
I want to change the config file of the openwhisk so that I can adjust the number of invoker container or the memory size of them.So how can I find the config file of openwhisk.

.

**Comment by rabbah** [comment]
If you're ansible deployment to VMs then you edit this file https://github.com/apache/openwhisk/blob/master/ansible/environments/local/hosts.j2.ini to add more invoker hosts.

**Comment by ZinuoCai** [comment]
@rabbah Can I change the config file if I deploy it with K8s? By the way, I also wonder what the difference between K8s and ansible deployment?

**Comment by rabbah** [comment]
Ansible is intended for a baremetal/VM deployment. For Kube, there are helm charts https://github.com/apache/openwhisk-deploy-kube which don't tend to rely or share some of the configurations with Ansible.

**Comment by GitHubDiom** [comment]
Hi, there

I have deployed openwhisk in Kind(k8s in docker).

How do I change the default code size (48 MB in default)?

In the beginning, I  run the following command for building virtual env.
```shell 
docker run --rm -v "$PWD:/tmp" openwhisk/python3action /bin/bash -c "cd tmp; virtualenv --system-site-packages virtualenv; source virtualenv/bin/activate; pip install -r requirements.txt"
```

And I found that `openwhisk/python3action` is too slow and usually failed when building the env.

Then I change the command:

``` shell
docker run --rm -v "$PWD:/tmp" ibmfunctions/action-python-v3.7:1.8.0 /bin/bash -c "cd tmp; virtualenv --system-site-packages virtualenv; source virtualenv/bin/activate; pip install -r reqs.txt"
```
where the reqs.txt just include `opencv-python` dependency

After I zip the `virtualenv` and `__main__.py` then I get `func.zip`, which is 63 M.

How to I change the default code size to create the action?

Thank you
