### ISSUE TITLE
How to change project ip and project port

### ISSUE THREAD

**Issue by crazyzcc619** [apache/openwhisk#4994]
## Environment details:

* local deployment, native ubuntu, Mac OS, Kubernetes, ...
* version of docker, ubuntu, ...

## Steps to reproduce the issue:

1.   
2.   
3.   

## Provide the expected results and outputs:

```
output comes here
```

## Provide the actual results and outputs:

```
output comes here
```

## Additional information you deem important:
* issue happens only occasionally or under certain circumstances   
* changes you did or observed in the environment

**Comment by crazyzcc619** [comment]
Is there a great god to help

**Comment by crazyzcc619** [comment]
Is there a great god to help

**Comment by rabbah** [comment]
How are you deploying openwhisk?

**Comment by crazyzcc619** [comment]
./gradlew core:standalone:bootRun

**Comment by ZinuoCai** [comment]
I do not understand why you want to change the IP address. But you can change the port referrint to [here](https://github.com/apache/openwhisk/tree/master/core/standalone).

You should first build the project with `./gradlew :core:standalone:build`. And then, you can assign a port to the application with `java -jar openwhisk-standalone.jar -p [YOUR_PORT]`. Good luck!

**Comment by rabbah** [comment]
Thanks @ZinuoCai for the added context. C
