### ISSUE TITLE
idle_container configuration in openwhisk

### ISSUE THREAD

**Issue by parichehrvn** [apache/openwhisk#5009]
Currently, the _Invoker_ component configuration in the _application.conf_ has the following configuration for _container proxy_ :

  container-proxy {
    timeouts {
      # The "unusedTimeout" in the ContainerProxy,
      #aka 'How long should a container sit idle until we kill it?'
      idle-container = 10 minutes
      pause-grace = 50 milliseconds
  }
how and where can I change the idle-container value?

**Comment by rabbah** [comment]
change this value ` idle-container = 10 minutes`.

**Comment by parichehrvn** [comment]
> Change this value ` idle-container = 10 minutes`. You can do it by editing the application.conf or passing an environment variable to override the value.

Is in possible to change the environment variable without reinstalling through the helm or rebuild by gradle and then upgrade with helm?

**Comment by joey0320** [comment]
@parichehrvn can you explain what is the difference btw idle-container & pause-grace???

**Comment by parichehrvn** [comment]
@joey0320 When a container runs out, it stays running for up to 50 milliseconds. In other words, it is hot for up to 50 milliseconds. This time is determined by pause-grace.
If no request is made to execute the function on the container within these 50 milliseconds, the container will be suspended for 10 minutes. In these 10 minutes, the container is warm and if requested, it will have a warm start. This time is determined by idle-container.
The pause container is a container which holds the network namespace for the pod.

**Comment by rabbah** [comment]
> Is it possible to change the environment variable without reinstalling through the helm or rebuild by gradle and then upgrade with helm?

@parichehrvn you do not need to rebuild but do need to redeploy.

**Comment by jiangpengcheng** [comment]
close as resolved/no update
