### ISSUE TITLE
How can a function use the external storage?

### ISSUE THREAD

**Issue by ZinuoCai** [apache/openwhisk#5035]
I wonder whether I can store some data in the CouchDB and use it when invoking the function, like the machine learning tasks?

**Comment by rabbah** [comment]
CouchDB used by OpenWhisk is part of the internal system and not available to the actions. Of course in a custom deployment, you could do that, if you wanted to. You can use any db you want as a service or if you deploy it into your system.

If you're considering using a hosted/vendor provided version of OpenWhisk, there are options which offer integrated storage (e.g., Nimbella, or provision an instance on IBM's Cloud Functions).
