### ISSUE TITLE
Illegal query: Invalid input ' ', expected '+', '=', query-char, 'EOI', '&' or pct-encoded 

### ISSUE THREAD

**Issue by jonee** [apache/openwhisk#5043]
## Environment details:

* IBM Cloud Functions
* Golang or Docker / Native runtime
* Also reproducible for nodejs

## Steps to reproduce the issue:

1.   Create the action with the code below (ibmcloud fn action update helloGo main.go --kind go:1.15 --web true)
2.   Retrieve the web action and invoke with a post
ibmcloud fn action get helloGo --url <- returns your url

curl -X POST -d '{"name":"sfdsfs4 "}' https://us-south.functions.appdomain.cloud/api/v1/xxx/helloGo.json

## Provide the expected results and outputs:

```
Expects the program to not error out and work as intended
```

## Provide the actual results and outputs:

```
{"code":"6683a4187e392c69625e2dbafba217ee","error":"Illegal query: Invalid input ' ', expected '+', '=', query-char, 'EOI', '&' or pct-encoded (line 1, column 17): {\"name\":\"sfdsfs4 \"}\n                ^"}

```

## Additional information you deem important:
* issue happens 100% of the time and should be easy to reproduce 
* It errors out when a post parameter has a space character. If a parameter has the +, it becomes a space. 
* Also, for native / docker it does not reuse variables outside of the main function (as compared to Golang runtime). This is usually used to reuse db connection (separate bug report)

Code for golang runtime
save as main.go
ibmcloud fn action update helloGo main.go --kind go:1.15 --web true
ibmcloud fn action get helloGo --url # returns your url
curl -X POST -d '{"name":"sfdsfs4 "}' https://us-south.functions.appdomain.cloud/api/v1/xxx/helloGo.json
ibmcloud wsk activation logs --last # returns the logs

```
package main

import (
    "log"
    "os"
    "time"
)
var t0 time.Time

func Main(params map[string]interface{}) map[string]interface{} {
    log.Println("params")
    log.Println(params)

    log.Println("os.Args")
    log.Println(os.Args)

    if t0.IsZero() {
		t0 = time.Now()
		log.Println("new t0")
	} else {
		log.Println("re used t0")
    }

    res := make(map[string]interface{})
    res["body"] = "Hello!"
    return res
}
```

Code for native / docker runtime
save as main.go
GOOS=linux GOARCH=amd64 go build -o exec
zip exec.zip exec
ibmcloud wsk action update helloGo --native exec.zip
ibmcloud fn action get helloGo --url <- returns your url
curl -X POST -d '{"name":"sfdsfs4 "}' https://us-south.functions.appdomain.cloud/api/v1/<xxx>/helloGo.json
ibmcloud wsk activation logs --last # returns the logs

```
package main

import (
    "fmt"
    "log"
    "os"
    "time"
    "encoding/json"
)
var t0 time.Time

func main() {
    log.Println("os.Args")
    log.Println(os.Args)

    if t0.IsZero() {
		t0 = time.Now()
		log.Println("new t0")
	} else {
		log.Println("re used t0")
    }

    msg := map[string]string{"body": ("Hello!")}
    res, _ := json.Marshal(msg)
    fmt.Println(string(res))
}
```

**Comment by jonee** [comment]
I can reproduce this for nodejs as well. 

Code for nodejs
save as test.js
ibmcloud fn action update helloNode test.js --kind nodejs:10 --web true
ibmcloud fn action get helloNode --url # returns your url
curl -X POST -d '{"name":"sfdsfs4 "}' https://us-south.functions.appdomain.cloud/api/v1/xxx/helloNode

// test.js
'use strict';

async function main(params) {
  console.log(params);


  return {
    body: {payload: `Hello world`},
    statusCode: 200,
    headers:{ 'Content-Type': 'application/json'}
  };

}

exports.main = main;

**Comment by rabbah** [comment]
I reproduced this against the playground as well [code here](https://apigcp.nimbella.io/api/v1/web/playground/default/showCode/user463062/z).
```
curl -X POST -d '{"name":"sfdsfs4 "}' https://apigcp.nimbella.io/api/v1/web/playground/user463062/z
```

There is a hidden character ` ` after the `4` which is the culprit.

**Comment by rabbah** [comment]
```
> curl -X POST -H'content-type: application/json' -d '{"name":"sfdsfs4 "}' https://apigcp.nimbella.io/api/v1/web/playground/user463062/z
Hello!
```
vs.
```
> curl -X POST  -d '{"name":"sfdsfs4 "}' https://apigcp.nimbella.io/api/v1/web/playground/user463062/z
{"code":"b8ff36573cb0182382b699c5cf588d6f","error":"Illegal query: Invalid input ' ', expected '+', '=', query-char, 'EOI', '&' or pct-encoded (line 1, column 17): {\"name\":\"sfdsfs4 \"}\n                ^"}
```

The latter uses `Content-Type: application/x-www-form-urlencoded`.

**Comment by jonee** [comment]
Ok thanks a lot!

it seems I only need to add -H 'content-type: application/json'
