### ISSUE TITLE
Upgrade to Akka 2.6.11

### ISSUE THREAD

**Issue by vrann** [apache/openwhisk#5060]
For any new features which uses Akka actors it would makes sense to start using Behavior-based construction of actors with the [Akka Typed](https://doc.akka.io/docs/akka/current/typed/from-classic.html). This is the way to construct actors encouraged by Akka for any new functionality. In order to use Akka Typed, it should be supported by the Akka version used in OpenWhisk. At the same time no changes needed to the Akka Classic actors. Upgrading to the newest Akka version would allow to use all latest features of the Akka, while keeping it compatible with almost everything of the Akka 2.5.x that is been used in OpenWhisk so far.

In our case we are implementing a new type of invocation system which heavily uses Akka actors.

This is an enhancement.

 Based on [Migration Guide 2.5.x to 2.6.x](https://doc.akka.io/docs/akka/current/project/migration-guide-2.5.x-2.6.x.html) the few areas has to be touched in the Open Whisk:
- to get rid of implicit custom ActorMaterializer and letting Akka to substitute with the system-wide one
- to upgrade to Akka Http 10.2.3. Having that ConnectionContext.https was deprecated, there is no good replacement for it without upgrading from Akka Http 10.1.x
- also, having AkkaSSLConfig was deprecated, few changes needed to the way the Https has been set up when host name verification is disabled
- RestartSink.withBackoff accepts RestartSettings as a parameter in akka 2.6.x
- akka.actor.FSM.setTimer => akka.actor.FSM.startTimerAtFixedRate
- akka.actor.Scheduler.schedule => akka.actor.Scheduler.scheduleAtFixedRate

**Comment by bdoyle0182** [comment]
Also FSM is deprecated in 2.6. All of the fsm's would need to be silenced. After 2.6 fsm's would need to be transitioned to typed which is a major refactor

**Comment by vrann** [comment]
@bdoyle0182 I haven't noticed deprecation on `akka.actor.FSM` at least not in  [2.6.12 version](https://github.com/akka/akka/blob/v2.6.12/akka-actor/src/main/scala/akka/actor/FSM.scala). It didn't even require to be silenced for compilation/tests. Are you saying this is something need to be done when transitioned from 2.6.x to the next major version?

The only thing about FSM deprecation I found in [2.5.x to 2.6.x migration guide](PersistentFSM) is that PersistentFSM got deprecated. But it doesn't look like it's used in OpenWhisk. Or am I missing something?

Thanks!

**Comment by ddragosd** [comment]
@vrann thanks for making this contribution in https://github.com/apache/openwhisk/pull/5065 .
