### ISSUE TITLE
[Question] How to make docker container standby

### ISSUE THREAD

**Issue by antengj** [apache/openwhisk#5073]
Hi guys.
Thanks for your nice product.
I found when the openwhisk start, there only one nodejs container standby.
How to make other run env container standby  as default and can make more then one standby like a pool?
Otherwise, there's lot's of time spend to pull images and start container.
Thanks.

**Comment by ningyougang** [comment]
Hm.. you mean prewarm container?

if that, when openwhisk starts, system will start several prewarm container according to the `runtimes.json`,
you can modify the runtimes.json to adjust the prewarm container.

**Comment by antengj** [comment]
> Hm.. you mean prewarm container?
> 
> if that, when openwhisk starts, system will start several prewarm container according to the `runtimes.json`,
> you can modify the runtimes.json to adjust the prewarm container.

Yes, that what I wanted. Thank you so much.
Is there any documents about this ? I want to know where is this file, how to set this file, and how to start openwhisk with this file.
Thanks.

**Comment by ningyougang** [comment]
Seems it is simple, seems no document for it.

Just modify the `openwhisk/ansible/files/runtimes.json` and redeploy the invoker component, in `ContainerPool.scala`, it will read the runtimes.json and create the prewarm containers(e.g. nodejs, java. python etc).

You can deploy the openwhisk use ansible.

BTW, currently, didn't support `adjust the prewarm containers in flying`, must adjust the prewarm containers via deploy with the new runtimes.json.
In future, we may support it.

**Comment by antengj** [comment]
> Seems no document for it.
> 
> Just modify the `openwhisk/ansible/files/runtimes.json` and redeploy the invoker component, in `ContainerPool.scala`, it will read the runtimes.json and create the prewarm containers(e.g. nodejs, java. python etc).
> 
> You can deploy the openwhisk using ansible.
> 
> BTW, currently, didn't support `adjust the prewarm containers in flying`, must adjust the prewarm containers via deploy with the new runtimes.json.
> In future, we may support it.

It worked.
Thank you so much!
