### ISSUE TITLE
a little problem with understanding the code in `ContainerPool`

### ISSUE THREAD

**Issue by ZinuoCai** [apache/openwhisk#5079]
Hello, I wonder what `actor` it refers to in the line below. It really confuses me a lot.
 
https://github.com/apache/openwhisk/blob/f9e469e50aac5a345a010e2bf1f71596f1b101fc/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala#L199

**Comment by rabbah** [comment]
It's bounded here:

https://github.com/apache/openwhisk/blob/f9e469e50aac5a345a010e2bf1f71596f1b101fc/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerPool.scala#L167-L168

this is the actor which represents the proxy to the actual container for running an action.

**Comment by ZinuoCai** [comment]
Thank you very much! It is such a complicated project.
