### ISSUE TITLE
CircleCI error uploading to Box

### ISSUE THREAD

**Issue by jbampton** [apache/openwhisk#5083]
## Steps to reproduce the issue:

After I fixed the last Python error in #5082 there is now a new error.

Right at the bottom of the build log seen here -> https://travis-ci.com/github/apache/openwhisk/jobs/490246490

Shown in the image below.

<img width="314" alt="Screen Shot 2021-03-12 at 11 08 17 pm" src="https://user-images.githubusercontent.com/418747/110953330-f55e6480-8392-11eb-93cf-ce5d08a3eb07.png">

refs #5082

**Comment by jiangpengcheng** [comment]
above error means there are some failed test cases, in your case, there are 2, both of which are known issues cause of unstable testcases

so close this

**Comment by rabbah** [comment]
@dgrove-oss should we remove the box upload? It’s proven difficult to maintain.
