### ISSUE TITLE
Unit Tests failing due to testcontainers

### ISSUE THREAD

**Issue by vrann** [apache/openwhisk#5120]
## Environment details:

* Travis

## Steps to reproduce the issue:

1.   Create PR with no code change (i.e. documentation update) and wait for tests to get executed  

## Provide the expected results and outputs:
Unit tests passed successfully 

## Provide the actual results and outputs:

Unit Tests are failing with the following issue

```
org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=docker.elastic.co/elasticsearch/elasticsearch:6.7.2)
Caused by:
com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: alpine:3.5"}
```

Here is an example of the failing job: https://travis-ci.com/github/apache/openwhisk/jobs/500605165

## Additional information you deem important:
* contacted Travis support team and here is what they responded:
"It appears that the error Is because of a testcontainers bug. Is by any chance your library or code dependent on that? This issue was addressed in testcontainer since the release of version 1.15.0"

**Comment by ddragosd** [comment]
fixed on #5121.

Thanks @vrann !
