### ISSUE TITLE
Allow web actions to respond with non-standard status codes

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk#5146]
## Environment details:

* local deployment (standalone openwhisk)

## Steps to reproduce the issue:

1.  create a web action using this function:
```
> cat t.js
const main = () => ({
  "body": {
    "message": "hello"
  },
  "statusCode": 442
})
```

2. invoke the web action
```
> wsk action update t t.js --web true
> curl -X POST `wsk action get t --url`
{
  "code": "b86c3c15bed0763357caa327bd2f25e4",
  "error": "Response is not valid 'message/http'."
}
```

Expecting the API to work (return the `message`) but it does not.
Change the `statusCode` to 400 and the API works as expected.

The relevant logic is here https://github.com/apache/openwhisk/blob/59b67fe96f44e573f3348afed966a1cdaf80ddf2/core/controller/src/main/scala/org/apache/openwhisk/core/controller/WebActions.scala#L251-L261

This is an error in the controller for status code 442 but it is swallowed. Amending the `Try` logic to show the exceptions produces:
```
exception in resultAsHttp: java.lang.RuntimeException: 
Non-standard status codes cannot be created by implicit conversion. 
Use `StatusCodes.custom` instead.
```

For reference, this is the cited message:
https://github.com/akka/akka-http/blob/5f8fb8c29285dcef16d74704394a7f6acf4f544e/akka-http-core/src/main/scala/akka/http/scaladsl/model/StatusCode.scala#L87

**Comment by jaishirole** [comment]
@rabbah This seems is fixed by https://github.com/apache/openwhisk/pull/5149. If yes, this issue stands closed and no 'help wanted' here?

**Comment by rabbah** [comment]
Thanks @jaishirole indeed the PR includes the proposed patch.
