### ISSUE TITLE
Authentication and user interface

### ISSUE THREAD

**Issue by elifsz** [apache/openwhisk#5156]
Is it possible to see the actions that I deployed with wsk from the console with the user interface, how will I do this?

and although I have authenticated myself and entered username: guest, password: auth key according to the information given, my login is not accepted. Where can I get the correct information?
![wsk-web](https://user-images.githubusercontent.com/44908865/132502247-5dcb09b4-afec-4494-8687-2c3877ec415d.PNG)
![property](https://user-images.githubusercontent.com/44908865/132502258-b5e93e50-dfb6-44bc-be17-2efae9b7a7fd.PNG)

**Comment by jrhunger** [comment]
I'm sure you have moved onto something else, but if you look at that whisk auth you see in the middle a colon (:) character.  The part before that is the username and the part after it is the password.
