### ISSUE TITLE
support OpenWhisk in Apache APISIX

### ISSUE THREAD

**Issue by moonming** [apache/openwhisk#5173]
hello, I am from Apache APISIX and we want to support OpenWhisk in [Apache APISIX](https://github.com/apache/apisix), here is the proposal: https://github.com/apache/apisix/issues/5485. 
Hope to get your feedback and help, thank you

**Comment by rabbah** [comment]
Thanks for the heads up and sorry for the delayed response. I've commented on the issue and will have a look at the PR.
