### ISSUE TITLE
Problem with slack digest messages

### ISSUE THREAD

**Issue by sebbASF** [apache/openwhisk#5175]
The slack digest messages on the dev@ list don't have any message-ids.
I don't know what is being used to generate them, but they ought to have unique message-ids.

Sample message:

https://lists.apache.org/api/source.lua?id=896q75ofyp6jjstom0ts2w8t41nr8my0

Here is a message with an id:

https://lists.apache.org/api/source.lua?id=4myw89oov7nn9ymo15pdnljy16qvdofd

Search for 'Message-Id', you should find:
Message-ID:
 <BYAPR02MB57667C72432D3B2EEBB14F68AF919@BYAPR02MB5766.namprd02.prod.outlook.com>

Message-IDs are important, because they are used for message threading etc.

**Comment by rabbah** [comment]
Is there documentation on how to generate message-ids (I'm not familiar
with them so will have to look into it)? I can look into whether it's easy
to add to the slack/email digest generator (it is automated cron using an
smtplib to send the email).


-r

**Comment by sebbASF** [comment]
Most email libraries include a means to generate the ids [1]

What language is being used?

[1] https://en.wikipedia.org/wiki/Message-ID

**Comment by rabbah** [comment]
Python. Found this on SO
https://stackoverflow.com/questions/22939035/how-to-get-message-id-of-email-sent-from-smtplib.

**Comment by sebbASF** [comment]
Yes, for Python this is the usual way to do it:
https://docs.python.org/3/library/email.utils.html#email.utils.make_msgid

**Comment by rabbah** [comment]
Moved to https://github.com/rabbah/slack-email-digest/issues/2. Will handle there.
