### ISSUE TITLE
Reach MySQL in Docker Container

### ISSUE THREAD

**Issue by Sladerix** [apache/openwhisk#5177]
Hi everyone... i've a problem.
I'm learning OpenWhisk and i installed it using the Kubernetes included with Docker Desktop.

I've a MySQL database running in a Docker container.

How can i reach it from an action of OpenWhisk? can i simply use the container name as address?

Thanks in advance :D

**Comment by rabbah** [comment]
Hopefully you figured this out - yes you can use the ip address but better to use the kubedns service name instead in case the ip changes, your function would not require an update.
