### ISSUE TITLE
How to add blog for Apache openwhisk and Apache APISIX 

### ISSUE THREAD

**Issue by moonming** [apache/openwhisk#5183]
hello, @rabbah thanks for your help about https://github.com/apache/apisix/pull/5518, Apache APISIX support Apache Openwhisk now:)
Are there channels such as blog or medium that can publish articles that is how to use Openwhisk and APISIX? Thanks a lot

**Comment by juzhiyuan** [comment]
Just leave a message in Slack and wait for more replies 😄 It seems that Apache OpenWhisk submit posts on Medium only, I cannot find the entry, too.

**Comment by rabbah** [comment]
We publish blogs here https://medium.com/@openwhisk - if you have a medium account I can add you so you can submit an article.

**Comment by juzhiyuan** [comment]
@rabbah Oh sure, we have a Medium link here: https://medium.com/@apacheapisix

And its account is `juzhiyuan@apache.org` :)

**Comment by rabbah** [comment]
@apacheapisix added as a writer - you can submit an article and i'll review and publish it.
do you want to schedule it for a particular day?

**Comment by juzhiyuan** [comment]
Sure, will let you know 😄

**Comment by juzhiyuan** [comment]
cc @yzeng25

**Comment by yzeng25** [comment]
> @apacheapisix added as a writer - you can submit an article and i'll review and publish it. do you want to schedule it for a particular day?

Hi @rabbah , after @apacheapisix is added as a writer, I logged in to @apacheapisix on Medium, and could not find notification about this event. I am a bit confused about the next steps of submitting an article here.

Usually, when publishing an article, I can click "Write" to write the contents and click "publish" to publish it on Medium.

Do we need to follow a different procedure when submitting an article?

**Comment by rabbah** [comment]
You have to assign the article to the `openwhisk` publication. I took a couple of screenshots from Medium.

<img width="271" alt="Screen Shot 2021-12-09 at 8 44 34 AM" src="https://user-images.githubusercontent.com/4959922/145407626-21dc0de6-d819-4ef2-bdcd-c084404c0ebd.png">
<img width="306" alt="Screen Shot 2021-12-09 at 8 44 40 AM" src="https://user-images.githubusercontent.com/4959922/145407573-633844de-a4ef-4c71-a4e2-4b7ab7401014.png">

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/145408559-bd4a4fba-0266-4bab-b5b8-c4953e4bb28c.png)

![image](https://user-images.githubusercontent.com/2106987/145408578-d7187fb6-5125-456a-b53e-35fc153164cd.png)

![image](https://user-images.githubusercontent.com/2106987/145408868-ed680919-95fd-4df8-a80f-fc2f7eaedb1c.png)

Hi @rabbah, it seems that there have no other publications 😅 Maybe the account is incorrect?

**Comment by yzeng25** [comment]
Here is what I get for the actual output.

![image](https://user-images.githubusercontent.com/36651058/145408752-4c706d69-d9e1-46cc-b109-80e4e2e304f7.png)

![image](https://user-images.githubusercontent.com/36651058/145408848-316bc0c4-955d-47d6-bfd7-880da7fad168.png)

Seems like it is missing for some reason.

**Comment by rabbah** [comment]
🤦‍♂️ 🤦‍♂️ 🤦‍♂️  i added but didn't save! try again.

**Comment by yzeng25** [comment]
Cool, it works now!

![image](https://user-images.githubusercontent.com/36651058/145413908-01de8deb-cba2-4977-a752-6c871866def6.png)

**Comment by juzhiyuan** [comment]
Thanks!!

**Comment by yzeng25** [comment]
Hi @rabbah ,

The blog is submitted on Medium just now, please take a look when you are available, Thanks :)

**Comment by rabbah** [comment]
On it. Thanks.

**Comment by rabbah** [comment]
When do you want me to publish it? It looks good. I didn't try the tutorial due to lack of time but like the hotswap capabilities and will be looking at this more in depth when i get a chance.

**Comment by rabbah** [comment]
I made only a small edit by the way.

**Comment by juzhiyuan** [comment]
cc @yzeng25

**Comment by yzeng25** [comment]
> When do you want me to publish it? It looks good. I didn't try the tutorial due to lack of time but like the hotswap capabilities and will be looking at this more in depth when i get a chance.

Thanks @rabbah ! You can publish it anytime.

**Comment by yzeng25** [comment]
The article is published now :) Shall we close this issue? cc @moonming 
https://medium.com/openwhisk/coming-soon-apache-apisix-integrate-with-apache-openwhisk-aca14188a267

**Comment by juzhiyuan** [comment]
Good to close 🥰
