### ISSUE TITLE
Cached locally after first invocation with --docker... where??

### ISSUE THREAD

**Issue by jebruen** [apache/openwhisk#5201]
Can someone please explain the following? 

"Custom runtime images will be pulled from Docker Hub into the local platform registry upon the first invocation. This can lead to longer cold-start times on the first invocation with a new or updated image. Once images have been pulled down, they are cached locally."

When I update and invoke an action with a publicly available image on dockerhub using the --docker flag, I would expect that image to be shown when I do a "docker image ls," but I don't see it. Where are these images cached locally? 

And I would assume that future invocations using that same image defined with --docker would be constructed from the local copy of the image; is that right?

**Comment by style95** [comment]
As I shared on Slack, you can find images on invoker machines in case of vanilla deployment.

Invokers will use image caches to run containers for subsequent activations.

closing.
