### ISSUE TITLE
actionType

### ISSUE THREAD

**Issue by qi0523** [apache/openwhisk#5215]
I am a beginner. There is a conceptual problem about actionType. How to distinguish between ‘managed’ and ‘blackbox’? In abstract class ExecMetaData, val pull(Boolean) indicates if a container image is required from the registry to execute the action. ls it correct that if pull is  true, container images must be downloaded from the registry(..eg docker hub)?

**Comment by rabbah** [comment]
>  ls it correct that if pull is true, container images must be downloaded from the registry(..eg docker hub)?

That is correct.
