### ISSUE TITLE
openwhisk demo erro

### ISSUE THREAD

**Issue by craftsman2020** [apache/openwhisk#5227]
hi,
   the openwhisk demo in the kubernate env,use the command to create action.
   wsk action create hello ./sample/hello.js
  but the reuslt is  "Unable to create action 'hello': Put "https://47.108.*.*:31001/api/v1/namespaces/_/actions/hello?overwrite=false":   x509: cannot validate certificate for 47.108.*.*:31001 because it doesn't contain any IP SANs".
 why,can u help troubleshoot it?thanks a lot.

**Comment by ningyougang** [comment]
Can you test against controller without nginx directly? at the same check controller logs.

**Comment by craftsman2020** [comment]
how to test against controller without nginx?

**Comment by ningyougang** [comment]
The request path is, user request -> nginx-> controller(create a activationMessage) -> scheduler(create memoryQueue) -> invoker(pull the activationMessage from scheduler's memoryQueue)

I feel the problem is in nginx pod side(e.g. certificate maybe), can you check the error logs for nginx?
For my previous test, i can test against for controller without nginx directly. e.g.
```
wsk property set \
  --apihost 'http://controllerIp:controllerPort' \
  --auth 'XXXXX:XXXXXXXXXXXXXX'
```
After executed above command, then. execute below command
```
wsk action create hello ./sample/hello.js
```

**Comment by craftsman2020** [comment]
Hi

  The controllerIp:controllerPort is internet IP or internal IP?

  The wsk property have been setted,When I run the command “wsk action create hello ./sample/hello.js”

  The nginx  have no errlog.



 

 

发件人: ***@***.*** ***@***.***> 代表 ningyougang
发送时间: 2022年4月29日 8:10
收件人: apache/openwhisk ***@***.***>
抄送: craftsman2020 ***@***.***>; Author ***@***.***>
主题: Re: [apache/openwhisk] openwhisk demo erro (Issue #5227)

 

The request path is, user request -> nginx-> controller(create a activationMessage) -> scheduler(create memoryQueue) -> invoker(pull the activationMessage from scheduler's memoryQueue)

I feel the problem is in nginx pod side(e.g. certificate maybe), can you check the error logs for nginx?
For my previous test, i can test against for controller without nginx directly. e.g.

wsk property set \
  --apihost 'http://controllerIp:controllerPort' \
  --auth 'XXXXX:XXXXXXXXXXXXXX'

After executed above command, then. execute below command

wsk action create hello ./sample/hello.js

**Comment by style95** [comment]
@craftsman2020 Does it work now? or not.
Have you tried adding `-i` option to the `wsk` cli?

**Comment by craftsman2020** [comment]
it means?
wsk property set --apihost  .....

i have done it._

**Comment by style95** [comment]
You should add `-i` option for all commands.
This is to ignore a self-signed certificate.

```
wsk action list -i
```

**Comment by ningyougang** [comment]
So, after apply `-i`, the issue solved?
