### ISSUE TITLE
About Invoker

### ISSUE THREAD

**Issue by qi0523** [apache/openwhisk#5264]
In kubernetes environment，how to get ip address of the physical machine where the invoker pod is located？

**Comment by style95** [comment]
This is out of the scope of the OpenWhisk, but I believe you can get the node information with `kubectl get pod -o wide`.

**Comment by qi0523** [comment]
Thanks.
Is it true that the controller and invoker don't know their respective IP addresses, they communicate through Kafka? Controller and invoker are local akka's actorSystem, not remote akka's actorSystem, right?
If using `kubectl get pod -o wide`, is pod‘s’ name assigned by
`val assignedInvokerId = new InstanceIdAssigner(config.zookeeperHosts).setAndGetId(unique, overwriteId)` ?

**Comment by qi0523** [comment]
> This is out of the scope of the OpenWhisk, but I believe you can get the node information with `kubectl get pod -o wide`.

Thanks.
Is it true that the controller and invoker don't know their respective IP addresses, they communicate through Kafka? Controller and invoker are local akka's actorSystem, not remote akka's actorSystem, right?
If using `kubectl get pod -o wide,` is pod‘s’ name assigned by
`val assignedInvokerId = new InstanceIdAssigner(config.zookeeperHosts).setAndGetId(unique, overwriteId)` ?

**Comment by style95** [comment]
If you are using a ShardingPoolBalancer, controllers, and invokers will communicate with each other via Kafka.
IIRC, controllers form an Akka cluster to determine the number of controllers and divide the invoker resource pool.

**Comment by qi0523** [comment]
> If you are using a ShardingPoolBalancer, controllers, and invokers will communicate with each other via Kafka. IIRC, controllers form an Akka cluster to determine the number of controllers and divide the invoker resource pool.

That's right.
If using a FPCPoolBalancer, can this project [openwhisk-deploy-kube](https://github.com/apache/openwhisk-deploy-kube) be useful to deploy?

**Comment by style95** [comment]
FPCPoolBalancer is not yet applied to the project yet. It needs to be added.
