### ISSUE TITLE
How to deploy openwhisk with source code?

### ISSUE THREAD

**Issue by SirHao** [apache/openwhisk#5319]
I am trying to modify the logic of openwhisk controller and invoker for acadmic research.
How can I build Openwhisk with modifed code and deploy it into a cluster?

**Comment by style95** [comment]
You can deploy OpenWhisk with [Ansible](https://github.com/apache/openwhisk/tree/master/ansible#deploying-openwhisk-using-ansible) or a [Helm chart](https://github.com/apache/openwhisk-deploy-kube)

**Comment by SirHao** [comment]
> Thank u for help. Now I guess I can build the source code by ansible. 
But I still confused about the deploy method of using helm chart. I see lots of configure files and I guess this method will pull the Openwhisk from remote. So, does it means such method can not deploy our modified Openwhisk in our local storage?

**Comment by SirHao** [comment]
> You can deploy OpenWhisk with [Ansible](https://github.com/apache/openwhisk/tree/master/ansible#deploying-openwhisk-using-ansible) or a [Helm chart](https://github.com/apache/openwhisk-deploy-kube)

> Thank u for help. Now I guess I can build the source code by ansible. 
But I still confused about the deploy method of using helm chart. I see lots of configure files and I guess this method will pull the Openwhisk from remote. So, does it means such method can not deploy our modified Openwhisk in our local storage?

**Comment by dgrove-oss** [comment]
https://github.com/apache/openwhisk-deploy-kube#deploying-a-locally-built-docker-image

**Comment by SirHao** [comment]
> https://github.com/apache/openwhisk-deploy-kube#deploying-a-locally-built-docker-image

Thanks
