### ISSUE TITLE
error: Unable to create action and dial tcp 172.17.0.1:3233: connect: connection refused

### ISSUE THREAD

**Issue by thunderZH963** [apache/openwhisk#5336]
## Environment details:

* ansible/local
* docker-20.10.12
* ubuntu-20.04
* aarch64

## Steps to reproduce the issue:

1.   Deploy openwhisk on local(by ansible): refer to https://github.com/apache/openwhisk/tree/master/ansible.
2.  Maybe some modification has been done to make openwhisk suitable to arrch64, but finally, all images were built successfully and related containers were all running.
3.   wsk property set --apihost '172.17.0.1:3233' 
4.   wsk property set --auth `cat ansible/files/auth.guest`
5.   create a simple 'hello.js'
6.   wsk action create hello hello.js
7.   wsk list
## Outputs
'wsk action create hello hello.js' shows that,

```
error: Unable to create action 'hello': Put "http://172.17.0.1:3233/api/v1/namespaces/_/actions/hello?overwrite=false": dial tcp 172.17.0.1:3233: connect: connection refused
```

'wsk list' shows that, 
 ```
wsk namespace list
error: Unable to obtain the list of available namespaces: Get "http://172.17.0.1:3233/api/v1/namespaces": dial tcp 172.17.0.1:3233: connect: connection refused
```

wsk property set --apihost '172.17.0.1',  wsk property set --apihost '172.17.0.1:80', wsk property set --apihost '172.17.0.1:443' were all be tried, but failed.

## 'Docker ps' shows
![image](https://user-images.githubusercontent.com/48862662/196191634-ce1d2ca3-9179-43fa-b189-91e94f9fa376.png)

According to my observation, all related containers are running, especially the 'nginx'. 
I can't find which part of my deployment has gone wrong and caused the failure of the 'wsk action create'.

I also want to know how I should configure ‘--apihost' for 'wsk' and which port to check.

**Comment by style95** [comment]
Generally, the 3233 port is for standalone deployment.
I think you need to use 80 or 443.

**Comment by thunderZH963** [comment]
setting --apihost to local IP directly  is ok.

**Comment by immortalsman** [comment]
I also meet this problem，could i inquire some questions？I used local ip and 172.17.0.1:3223 are not ok.
Is it because I'm not using a docker image？My docker ps is empty。

**Comment by immortalsman** [comment]
error: Unable to create action 'hello': The connection failed, or timed out. (HTTP status code 500)

**Comment by style95** [comment]
@immortalsman 
In this issue, he deployed a standard deployment using ansible but he tried to use an endpoint for standalone deployment.
Which type of deployment are you using?

**Comment by immortalsman** [comment]
Hello，friends！Thank you for your answer.I use ansible.I changed it to the local ip address so there is no error message, but there is a new problem that I haven't solved yet.

This is my&nbsp;reference blog&nbsp;https://blog.csdn.net/supergxt/article/details/118114893
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/openwhisk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月10日(星期四) 下午2:35
***@***.***&gt;;
抄送:&nbsp;"pony ***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/openwhisk] error: Unable to create action and dial tcp 172.17.0.1:3233: connect: connection refused (Issue #5336)





 
@immortalsman
 In this issue, he deployed a standard deployment using ansible but he tried to use an endpoint for standalone deployment.
 Which type of deployment are you using?
