### ISSUE TITLE
ActivationClientProxy commit from yesterday prevents invoker from becoming healthy

### ISSUE THREAD

**Issue by bdoyle0182** [apache/openwhisk#5347]
This commit from yesterday prevents invokers from registering as healthy. https://github.com/apache/openwhisk/commit/0f4b0c220e050d408a650a8c5a90fbc54b52768a

To reproduce, deploy built invoker with commit to see that it won't become healthy. Then rebuild with the commit before it and deploy. I assume it's some race condition with the healthTestAction where the execution completes faster than the delay that was added here or something along those lines? @style95

**Comment by style95** [comment]
I am unsure if that is a culprit but the change is related to the logic before running activations.
It is to wait for the activation client proxy to be ready and the container proxy will not execute any activation unless it passes the step(client creation).
So if any activations are properly executed, the step is already passed and I think it's not related to the issue.
In my environment, all my invokers become healthy. I tried to reproduce it by restarting invokers multiple times but no invoker became unhealthy though some CI tests in my environment are still failing.
I am looking into it.
