### ISSUE TITLE
How set openwhisk web action  asynchronous ?

### ISSUE THREAD

**Issue by QWQyyy** [apache/openwhisk#5402]
We use openwhisk web action to create some data service, but we find the docment do'nt have any async action profile set, I hope you give me some suggestion to set web action async profile.

**Comment by style95** [comment]
A web action can even run on a browser with the GET method.
In this sense, a web action is only invokable in a synchronous way.

**Comment by QWQyyy** [comment]
> Web 操作甚至可以使用 GET 方法在浏览器上运行。 从这个意义上说，网络操作只能以同步方式调用。

well notes, we also think it. And we use other way to run async action.
