### ISSUE TITLE
CI scancode misconfigured

### ISSUE THREAD

**Issue by dgrove-oss** [apache/openwhisk#5417]
As discussed in #5415 the CI test isn't catching misformatted Scala code.

Looking at a recent action log, the format check is correctly identifying the problem: https://github.com/apache/openwhisk/actions/runs/5019987402/jobs/9001037966#step:3:772

My guess is that we need to fix `setup.sh` so that it fails if one of its substeps fails.

**Comment by style95** [comment]
closing as done
