### ISSUE TITLE
Invocation-level fault tolerance guarantees

### ISSUE THREAD

**Issue by cvetkovic** [apache/openwhisk#5449]
Hi people! I am aware that Github issues might not be the right place to ask questions, but Slack won't send an invitation to my email. 

Does someone know if OpenWhisk provides any fault tolerance guarantees on the invocation level? For example, if some component on the critical path of an invocation or a worker node fails during the execution of a request, will OpenWhisk try to reexecute the failed invocation, or this is left to the user to handle? 

Thanks.

**Comment by dgrove-oss** [comment]
Hi,

Sorry the slack invitation isn't woking for you.

To answer the question, OpenWhisk offers an "at most once" instead of an "at least once" execution model.  So if there is a failure during the execution of a request, the execution will not be automatically retried by OpenWhisk.  If a user wants to ensure that a request will be executed at least once, they have to track their open requests externally and resubmit requests that haven't completed within some time threshold they think is reasonable.

**Comment by style95** [comment]
@dgrove-oss 

It seems this invitation button does not work as expected.
https://openwhisk.apache.org/slack.html

The action was running on bluemix and it seems it is no longer valid.
```
$ curl -X GET https://21ef035.api-gw.mybluemix.net/openwhisk-team/slackinvite?email=user@example.com -k
404 Not Found: Requested route ('21ef035.api-gw.mybluemix.net') does not exist.
```
https://github.com/apache/openwhisk-slackinvite

Do you have any idea about it?
Maybe we need to deploy it on another cloud?
If we can't use bluemix anymore, I would look for another one.

**Comment by dgrove-oss** [comment]
@style95 -- IBM Cloud withdrew API gateway support and the action was also probably running on a really old node.js version that is no longer supported.  Definitely is not working now.   

We either need to host it somewhere else, or look for a more direct way of adding people to Slack.  It was a cute demo to use an OpenWhisk function, but there may be simpler ways to do it.

**Comment by Abhishekghosh1998** [comment]
@dgrove-oss Any quick fix on getting the slack invite link working? I am interested in joining the OpenWhisk Slack community.

**Comment by dgrove-oss** [comment]
@Abhishekghosh1998 -- the most expedient thing would be to send an email to me (groved@us.ibm.com) with your email and I will invite you to join directly from Slack.

**Comment by rabbah** [comment]
should we replace the instructions with "send email to the dev list to get an invitation"?
