### ISSUE TITLE
OpenWhisk Releases

### ISSUE THREAD

**Issue by dragndropzek** [apache/openwhisk#5451]
Hello,

I see that Whisk still has active commits to master branch, but it's been 3 years since last release.

Is there a reason for this?

I'm asking cause I wanted to deploy OpenWhisk, but I wasn't sure how long it's going to be maintained.

Thanks for amazing work!

**Comment by style95** [comment]
We are about to release the new one as the openwhisk core v2 is now available.
But anyway, we are definitely short-handed these days.
Looking for contributors :)

**Comment by dragndropzek** [comment]
I'm glad that its still active project since IBM announced on Thursday that IBM Cloud Functions will shut down October 2024. I'm infra guy so I can help with some of the deployments code (Ansible) since current Ansible looks like it can use some additional work. 

I'll try to find time and submit PR when I have something.

**Comment by style95** [comment]
@dragndropzek 
That sounds great!
Looking forward to it :)
