### ISSUE TITLE
Question: How to create an action using a custom Ubuntu docker image

### ISSUE THREAD

**Issue by Tim-C1** [apache/openwhisk#5478]
Hi all, I am new to openwhisk, my goal is to create an action using a custom ubuntu docker image, to be more specific: I would like to run some bash scripts within the custom ubuntu docker image.

I read the docs for a while but I haven't found a good solution yet, could any of you give me some advices?

**Comment by Tim-C1** [comment]
Hi, I build a image using this [runtime-docker](https://github.com/apache/openwhisk-runtime-docker.) Currently, I just put a exec file that output a json string using `echo` and does not modify anything else. But when I create an action and then invoke, it always timeout and then it will report something like "error Request accepted, but processing not completed yet."

**Comment by rabbah** [comment]
There's not information here to help you. You can confirm that your container image is properly set up by running a copy of the container locally and using https://github.com/apache/openwhisk/tree/master/tools/actionProxy to test the image.

**Comment by Tim-C1** [comment]
thanks, I already solved that.

**Comment by rabbah** [comment]
Great @Tim-C1 - if you can leave a brief comment for what the fix was it might be helpful for future reference.

**Comment by Tim-C1** [comment]
Sure! Actually this has nothing to do with openwhisk, I follow the [dockerskeleton repo](https://github.com/apache/openwhisk-runtime-docker) and do some modifications to the Dockerfile to build a custom ubuntu image, and it works. The reason why I can not run create and invoke an action is that I first run bash in the image I built then commit it, and this commit will override the default CMD specified in the Dockerfile which is used to the start actionProxy server required by Openwhisk.
