### ISSUE TITLE
Feat: Using pekko instead of akka

### ISSUE THREAD

**Issue by laglangyue** [apache/openwhisk#5479]
Akka changed the protocol, pekko is TLP

**Comment by rabbah** [comment]
This will prob be a large undertaking even though pekko is an akka fork. Are you interested in doing this?

**Comment by laglangyue** [comment]
> This will prob be a large undertaking even though pekko is an akka fork. Are you interested in doing this?

I am pekko contrributer, and have a PEKKO committee friends, and my friends and I will do our best to give it a try

**Comment by pjfanning** [comment]
this is a duplicate of https://github.com/apache/openwhisk/issues/5441
