### ISSUE TITLE
go build main.go Rename the file to exec

### ISSUE THREAD

**Issue by zijiwork** [apache/openwhisk#5501]
go build main.go Rename the file to exec, and create exec.env, cat exec.env
openwhisk/action-golang-v1.16 An error occurred during the call. wsk action invoke gozip -r --param name "openwhisk" -i
{
"error": "Cannot start action. Check logs for details."
}

**Comment by sciabarracom** [comment]
what are you trying to do exactly? are you trying to build a go action locally and then upload? You should send the source code as in the examples instead.

**Comment by zijiwork** [comment]
> what are you trying to do exactly? are you trying to build a go action locally and then upload? You should send the source code as in the examples instead.

Yes, Is it possible to build a go binary locally and compress it into zip?

**Comment by zijiwork** [comment]
```
When using action image build, it prompts "cannot download modules". How to generate exec file in offline mode. Eg: Is it possible to use go build -o exec main.go , zip -r * main.zip
```
zip -r - * | docker run -i  whisk/action-golang-v1.21 -compile main > main.zip
  adding: go.mod (deflated 20%)
  adding: go.sum (deflated 66%)
  adding: main.go (deflated 55%)
2024/08/02 06:09:16 cannot download modules
