### ISSUE TITLE
Rebuilt Invoker Not Reflecting Changes in Logs

### ISSUE THREAD

**Issue by HaoWang9909** [apache/openwhisk#5525]
## Description：
I am trying to make changes to the FunctionPullingContainerProxy.scala file in OpenWhisk’s invoker component. Specifically, I updated a log message in the Running state from "No more run activation ..." to "No more run Activation --testing-- is coming in state ...". However, after rebuilding the invoker image and redeploying OpenWhisk, the changes are not reflected in the logs.

## Environment details:

* ubuntu 22.04

## Steps to reproduce the issue:

1.   Modify the FunctionPullingContainerProxy.scala file in core/containerpool/v2:
```scala
      logging.info(
        this,
        s"No more run Activation --testing-- is coming in state: $stateName, action: ${data.action}, container: ${data.container.containerId}")
```
2. Rebuild the invoker Docker image:
```shell
./gradlew :core:invoker:clean :core:invoker:distDocker
```
3. Redeploy OpenWhisk using Ansible:
```shell
cd ansible
sudo ansible-playbook -i environments/local openwhisk.yml -e mode=clean
sudo ansible-playbook -i environments/local openwhisk.yml
```
4. Check the logs of the invoker:
```shell
cat /var/tmp/wsklogs/invoker0/invoker0_logs.log
```

## Expected Behavior

```
The log message should reflect the updated text: "No more run Activation --testing-- is coming in state ...".
```

## Observed Behavior

```
[2024-12-30T02:16:47.868Z] [INFO] [#tid_sid_unknown] [FunctionPullingContainerProxy] No more run activation is coming in state: Running, action: ExecutableWhiskAction/guest/dq@0.0.1, container: ContainerId(8ae3468b23719f4ab251254997b1487fcc49171ce1a50596da75895d41093a2a)
```

## Additional information you deem important:
* Verified that the updated code is correctly written in the source file.
* Rebuilt the invoker Docker image using :core:invoker:clean and :core:invoker:distDocker.
* Observed the Docker image timestamp, and it reflects the recent build.
* Also tried a more complex way to rebuild, but still not working.
```shell
export ENVIRONMENT=local
sudo ansible-playbook -i environments/$ENVIRONMENT openwhisk.yml -e mode=clean
sudo ansible-playbook -i environments/$ENVIRONMENT setup.yml
sudo ansible-playbook -i environments/$ENVIRONMENT prereq.yml
sudo systemctl stop couchdb
cd ..
./gradlew clean
export ENVIRONMENT=local
./gradlew distDocker
cd ansible
sudo ansible-playbook -i environments/$ENVIRONMENT couchdb.yml
sudo ansible-playbook -i environments/$ENVIRONMENT initdb.yml
sudo ansible-playbook -i environments/$ENVIRONMENT wipe.yml
sudo ansible-playbook -i environments/$ENVIRONMENT elasticsearch.yml
sudo ansible-playbook -i environments/$ENVIRONMENT openwhisk.yml
sudo ansible-playbook -i environments/$ENVIRONMENT postdeploy.yml
sudo ansible-playbook -i environments/$ENVIRONMENT apigateway.yml
sudo ansible-playbook -i environments/$ENVIRONMENT routemgmt.yml
```

**Comment by HaoWang9909** [comment]
## Issue Resolved

The issue has been resolved successfully. The problem was related to how the invoker image was specified and deployed across multiple machines. Here’s the detailed explanation:

## Root Cause

The problem occurred because:
1. Deployment Across Multiple Machines: I have a setup with two machines – one for the controller and one for the invoker. During the deployment process, there was a mismatch in how the invoker image was configured and deployed.
2. Temporary Ansible Configuration Change: At some point, I modified the ansible/roles/invoker/tasks/deploy.yml file to force the invoker to use the nightly tag from the Docker registry:
```
image: "{{ docker_registry }}openwhisk/invoker:nightly"
```
This change caused the deployment process to always pull the nightly image from the registry, ignoring any locally built or customized images.

## Solution

To resolve the issue, I followed these steps:
1. Reverted the Ansible Configuration:
I updated the ansible/roles/invoker/tasks/deploy.yml file to use the correct dynamic image configuration:
```
image: "{{ docker_registry }}{{ docker.image.prefix }}/invoker:{{ 'cov' if (coverage_enabled) else docker.image.tag }}"
```
This ensures that the invoker deployment respects the tag specified in the docker.image.tag variable.

2. Built the Invoker Image Locally:
On the machine where the invoker image was being built (controller machine), I ran:
```
./gradlew :core:invoker:clean :core:invoker:distDocker
```
3. Transferred the Image to the Invoker Machine:
- I exported the built image as invoker.tar:
- docker save -o invoker.tar whisk/invoker:latest
- Then transferred it to the invoker machine:
```
scp invoker.tar user@invoker-machine:~
```
4. Loaded the Image on the Invoker Machine:
On the invoker machine, I loaded the image:
```
docker load -i ~/invoker.tar
```
5. Redeployed OpenWhisk:
Finally, I redeployed OpenWhisk to ensure the correct image was used:
```
cd ansible
sudo ansible-playbook -i environments/local openwhisk.yml
```
## Outcome

After completing the above steps:
1. The invoker is now using the correct image.
2. My code changes are reflected in the invoker logs, confirming that the updated image is being used.

**Comment by HaoWang9909** [comment]
## Question: Simplifying Invoker Deployment in Distributed Setup

In a distributed OpenWhisk setup (separate machines for Controller and Invokers), updating the Invoker source code requires building the Docker image on the Controller machine, exporting it, transferring it to all Invoker machines, and then loading it.

Is there a simpler way to handle Invoker updates? For example:
- Can Ansible automate the image transfer?
- Is it possible to build the image directly on Invoker machines?

Looking for best practices to streamline this process. Thank you!

**Comment by HaoWang9909** [comment]
I resolved the issue by adding the following tasks to ansible/roles/invoker/tasks/deploy.yml:
```yml
- name: Save invoker Docker image
  command: docker save -o /tmp/invoker.tar whisk/invoker:latest
  delegate_to: localhost
  run_once: true

- name: Copy invoker image to all Invoker machines
  copy:
    src: /tmp/invoker.tar
    dest: /tmp/invoker.tar

- name: Load invoker Docker image on Invoker machines
  command: docker load -i /tmp/invoker.tar
```
This worked successfully, and the updated Invoker image was deployed across all machines.

**Comment by style95** [comment]
You can use a private registry to share images in a distributed environment.
`dockerRegistry` options is available while building images.

https://github.com/apache/openwhisk/tree/master/gradle#build

**Comment by HaoWang9909** [comment]
Thank you! I’ve learned something new, and I really appreciate it!

**Comment by Hyzheng-WHU** [comment]
Hello, I attempted to deploy OpenWhisk on Ubuntu 22.04 but encountered some errors that prevented a successful deployment. The official code deployment was only successful on Ubuntu 18.04. Could you please tell me what modifications you made to the code to make it run successfully on Ubuntu 22.04?

**Comment by LucasWang9909** [comment]
Hi, it's been a while, so I don't recall the exact changes I made. However, I'm pretty sure this commit contains the necessary modifications that allowed it to run on Ubuntu 22.04. You can check the changes here (https://github.com/LucasWang9909/my_openwhisk/tree/0e4cd9d9878bccab6e8324ccb305a3ade0173e58). Hope this helps!
