### ISSUE TITLE
openwhisk/tests/src/common should be relooked into

### ISSUE THREAD

**Issue by daisy-ycguo** [apache/openwhisk#827]
I think these codes [openwhisk/tests/src/common](https://github.com/openwhisk/openwhisk/tree/master/tests/src/common) are not test cases but test utilities. Some are utilities that all most all test codes depend on, such as [TestUtils.java](https://github.com/openwhisk/openwhisk/blob/master/tests/src/common/TestUtils.java). Some are usefully libraries which might be useful even for users, such as [Wsk.scala](https://github.com/openwhisk/openwhisk/blob/master/tests/src/common/Wsk.scala).

I think they should not in `openwhisk/tests` folder. `openwhisk/common` may be more suitable to keep those codes.

What's more, since we are moving some codes out of openwhisk repo, it is reasonable that the new projects have dependencies to openwhisk/common and openwhisk/core. I think it's not so reasonable that the new projects have dependencies to openwhisk/tests/src/common. That's why I suggest to move those codes out of `tests` and move them into `openwhisk/common`.

Please let me know your thoughts.
@rabbah @csantanapr 

Daisy

**Comment by rabbah** [comment]
Good idea but we're paying a high cost already for managing too many repos.
